import { standards, standardsVersion } from '../../../curriculum/standards';
import type { Skill, TaskKind } from './types';
export { standards, standardsVersion };
// Assessments cover the named numerical facet, NOT every requirement of the standard.
const practice: Record<string, [TaskKind[], string[], number?]> = {
 'K.CC.A.2': [['sequence'], []],
 'K.CC.C.7': [['compare'], ['K.CC.A.2']],
 'K.OA.A.5': [['arithmetic'], ['K.CC.A.2'], 5000],
 'K.NBT.A.1': [['placeValue'], ['K.CC.A.2']],
 '1.OA.B.4': [['missing'], ['K.OA.A.5']],
 '1.OA.C.6': [['arithmetic'], ['K.OA.A.5'], 5000],
 '1.OA.D.8': [['missing'], ['1.OA.C.6']],
 '1.NBT.B.2': [['placeValue'], ['K.NBT.A.1']],
 '1.NBT.B.3': [['compare'], ['1.NBT.B.2']],
 '1.NBT.C.4': [['arithmetic'], ['1.OA.C.6','1.NBT.B.2']],
 '1.NBT.C.5': [['arithmetic'], ['1.NBT.B.2']],
 '1.NBT.C.6': [['arithmetic'], ['1.NBT.B.2']],
 '1.G.A.3': [['fraction'], []],
 '2.OA.B.2': [['arithmetic'], ['1.OA.C.6'], 3500],
 '2.OA.C.4': [['arithmetic'], ['2.OA.B.2']],
 '2.NBT.A.1': [['placeValue'], ['1.NBT.B.2']],
 '2.NBT.A.2': [['sequence'], ['2.NBT.A.1']],
 '2.NBT.A.4': [['compare'], ['2.NBT.A.1']],
 '2.NBT.B.5': [['arithmetic'], ['2.OA.B.2','1.NBT.C.4']],
 '2.NBT.B.7': [['arithmetic'], ['2.NBT.B.5','2.NBT.A.1']],
 '2.NBT.B.8': [['arithmetic'], ['2.NBT.A.1']],
 '2.G.A.2': [['measure'], ['2.OA.C.4']],
 '2.G.A.3': [['fraction'], ['1.G.A.3']],
 '3.OA.A.1': [['arithmetic'], ['2.OA.C.4']],
 '3.OA.A.2': [['arithmetic'], ['3.OA.A.1']],
 '3.OA.A.4': [['missing'], ['3.OA.A.1','3.OA.A.2']],
 '3.OA.B.6': [['missing'], ['3.OA.A.1']],
 '3.OA.C.7': [['arithmetic'], ['3.OA.A.4'], 3500],
 '3.OA.D.9': [['sequence'], ['3.OA.C.7']],
 '3.NBT.A.1': [['round'], ['2.NBT.A.1']],
 '3.NBT.A.2': [['arithmetic'], ['2.NBT.B.7']],
 '3.NBT.A.3': [['arithmetic'], ['3.OA.C.7']],
 '3.NF.A.1': [['fraction'], ['2.G.A.3']],
 '3.NF.A.3': [['compare'], ['3.NF.A.1']],
 '3.MD.C.6': [['measure'], ['2.G.A.2']],
 '3.MD.C.7': [['measure'], ['3.OA.A.1','3.MD.C.6']],
 '3.MD.D.8': [['measure'], ['2.NBT.B.5']],
 '3.G.A.2': [['fraction'], ['3.NF.A.1']],
 '4.OA.C.5': [['sequence'], ['3.OA.D.9']],
 '4.NBT.A.1': [['placeValue'], ['2.NBT.A.1']],
 '4.NBT.A.2': [['compare','placeValue'], ['4.NBT.A.1']],
 '4.NBT.A.3': [['round'], ['3.NBT.A.1']],
 '4.NBT.B.4': [['arithmetic'], ['3.NBT.A.2']],
 '4.NBT.B.5': [['arithmetic'], ['3.OA.C.7','3.NBT.A.3']],
 '4.NBT.B.6': [['arithmetic'], ['3.OA.C.7']],
 '4.NF.A.2': [['compare'], ['3.NF.A.3']],
 '4.NF.B.3': [['arithmetic'], ['3.NF.A.1','2.OA.B.2']],
 '4.NF.B.4': [['arithmetic'], ['3.NF.A.1','3.OA.C.7']],
 '4.NF.C.5': [['arithmetic'], ['4.NF.B.3']],
 '4.NF.C.7': [['compare'], ['4.NF.A.2']],
 '4.MD.A.3': [['measure'], ['3.MD.C.7','3.MD.D.8']],
 '5.NBT.A.2': [['power'], ['4.NBT.A.1']],
 '5.NBT.A.3': [['compare'], ['4.NF.C.7']],
 '5.NBT.A.4': [['round'], ['4.NBT.A.3','5.NBT.A.3']],
 '5.NBT.B.5': [['arithmetic'], ['4.NBT.B.5']],
 '5.NBT.B.6': [['arithmetic'], ['4.NBT.B.6']],
 '5.NBT.B.7': [['arithmetic'], ['5.NBT.A.3','4.NBT.B.4']],
 '5.NF.A.1': [['arithmetic'], ['4.NF.B.3']],
 '5.NF.B.3': [['arithmetic'], ['3.OA.A.2','3.NF.A.1']],
 '5.NF.B.4': [['arithmetic'], ['4.NF.B.4']],
 '5.NF.B.7': [['arithmetic'], ['5.NF.B.3']],
 '5.MD.C.4': [['measure'], ['3.MD.C.7']],
 '5.MD.C.5': [['measure'], ['5.MD.C.4']],
 '6.RP.A.2': [['rate'], ['5.NF.B.3']],
 '6.RP.A.3': [['percent','rate'], ['6.RP.A.2']],
 '6.NS.A.1': [['arithmetic'], ['5.NF.B.4','5.NF.B.7']],
 '6.NS.B.2': [['arithmetic'], ['5.NBT.B.6']],
 '6.NS.B.3': [['arithmetic'], ['5.NBT.B.7']],
 '6.NS.B.4': [['factors'], ['3.OA.C.7']],
 '6.NS.C.7': [['compare'], ['5.NBT.A.3']],
 '6.EE.A.1': [['power'], ['5.NBT.A.2']],
 '6.EE.A.2': [['evaluate'], ['6.EE.A.1']],
 '6.EE.B.7': [['linear'], ['1.OA.D.8','5.NF.A.1']],
 '6.G.A.1': [['measure'], ['4.MD.A.3']],
 '6.G.A.2': [['measure'], ['5.MD.C.5','5.NF.B.4']],
 '6.G.A.4': [['measure'], ['5.MD.C.5']],
 '6.SP.B.5': [['statistics'], ['6.NS.B.3']],
 '7.RP.A.1': [['rate'], ['6.RP.A.2','6.NS.A.1']],
 '7.RP.A.3': [['percent'], ['6.RP.A.3']],
 '7.NS.A.1': [['arithmetic'], ['6.NS.C.7','5.NF.A.1']],
 '7.NS.A.2': [['arithmetic'], ['7.NS.A.1','6.NS.A.1']],
 '7.EE.B.4': [['linear'], ['6.EE.B.7','7.NS.A.1']],
 '7.G.B.6': [['measure'], ['6.G.A.2','6.G.A.4']],
 '7.SP.C.7': [['probability'], ['6.RP.A.2']],
 '8.EE.A.1': [['power'], ['6.EE.A.1','7.NS.A.2']],
 '8.EE.B.5': [['slope'], ['7.RP.A.1']],
 '8.EE.C.7': [['linear'], ['7.EE.B.4']],
 '8.F.A.3': [['evaluate'], ['6.EE.A.2']],
 '8.F.B.4': [['slope'], ['8.EE.B.5']],
 '8.G.B.7': [['pythagorean'], ['6.EE.A.1']],
};
export const skills: Skill[] = standards.map(s => {
 const assessed = practice[s.id];
 return { id: s.id, grade: s.grade, domain: s.domain, title: s.summary,
  standards: [s.id, ...s.components], sourceUrl: s.sourceUrl,
  prerequisites: assessed?.[1] ?? [], prerequisiteBasis: 'aha-inferred',
  taskKinds: assessed?.[0] ?? [], coverage: assessed ? 'verified-practice' : 'guided-only',
  ...(assessed?.[2] ? { fluencyTargetMs: assessed[2] } : {}) };
});
const byId = new Map(skills.map(s => [s.id, s]));
export const getSkill = (id: string): Skill | undefined => byId.get(id);
export function coverageAudit() {
 return { version: standardsVersion, standards: standards.length,
  componentStandards: standards.reduce((n,s) => n + s.components.length, 0),
  verifiedPractice: skills.filter(s => s.coverage === 'verified-practice').map(s => s.id),
  guidedOnly: skills.filter(s => s.coverage === 'guided-only').map(s => s.id),
  note: 'Verified practice assesses a numerical facet; it does not certify all requirements of a CCSS standard.' };
}

/** Available for unscored teaching too; never restrict curriculum visibility to assessable facets. */
export function getSkillNeighborhood(id:string) {
 const skill=getSkill(id);if(!skill)throw new Error('Unknown curriculum skill.');
 return {skill,standard:standards.find(s=>s.id===id)!,
  prerequisites:skill.prerequisites.map(id=>getSkill(id)!),
  next:skills.filter(s=>s.prerequisites.includes(id))};
}
