/**
 * beatlounge — Scene SNAPSHOT: a deep, serializable capture of the doc's
 * MUSICAL state. A Scene (see ../scenes/*) is a named snapshot the user curates
 * so they can evolve A → B → C and freely jump A ↔ B ↔ C. This is NOT undo/redo
 * (linear edit history) — these are explicit, named checkpoints.
 *
 * A `SceneSnapshot` is EXACTLY the subset of the doc that defines the sound:
 * tracks, harmony, loop length, tempo/meter maps, swing, master volume, buses,
 * fragment library and modulators. It deliberately EXCLUDES:
 *   - identity:  `id`, `name`        (a loaded scene keeps the song's identity)
 *   - schema/ppq: structural constants (re-asserted on load)
 *   - volatile:  `createdAt`/`updatedAt` (regenerated by the bus on commit)
 *
 * Scenes themselves live in a SEPARATE persisted store slice (see
 * ../store/scenesStore), keyed by doc id — NOT on the doc — so the live doc and
 * its undo history stay lean (a heavy snapshot per command/undo frame would
 * bloat memory + IDB). Because they aren't on the doc, there is no recursion to
 * guard against: a snapshot never contains other snapshots.
 *
 * Everything here is plain JSON (document.ts rule #1), so capture is a deep
 * clone and load is a structural merge — both pure, both unit-tested.
 */

import type {
  BeatloungeDoc,
  Bus,
  FragmentRef,
  Harmony,
  Modulator,
  Normalized,
  TempoEvent,
  MeterEvent,
  Track,
} from "./document"
import { defaultHarmony } from "./document"
import type { Grid, Tick } from "./timing"

/**
 * The musical subset of a BeatloungeDoc — everything that defines the SOUND.
 * Mirror the doc's field types so capture is structural and type-checked: if a
 * new musical field is added to the doc, TS flags the omission here.
 */
export interface SceneSnapshot {
  loopLengthTicks: Tick
  bpm: number
  tempoMap: TempoEvent[]
  meterMap: MeterEvent[]
  swing: { amount: Normalized; grid: Grid }
  masterVolume: Normalized
  tracks: Track[]
  buses: Bus[]
  fragmentLibrary: FragmentRef[]
  modulators: Modulator[]
  /** Always present in a snapshot (defaulted on capture) so load is total. */
  harmony: Harmony
}

/** Structured-clone if available, else a JSON round-trip. Both are deep + pure
 *  for the plain-JSON doc; falls back so tests/SSR (no structuredClone) work. */
const deepClone = <T>(v: T): T => {
  const sc = (globalThis as { structuredClone?: <U>(x: U) => U }).structuredClone
  if (typeof sc === "function") return sc(v)
  return JSON.parse(JSON.stringify(v)) as T
}

/**
 * Capture the current musical state of `doc` as a SceneSnapshot. Deep-clones so
 * the snapshot can never alias live doc arrays (a later edit must not mutate a
 * saved scene). `harmony` is defaulted (migration-safe) so old docs snapshot
 * cleanly and load total.
 */
export const captureSnapshot = (doc: BeatloungeDoc): SceneSnapshot =>
  deepClone({
    loopLengthTicks: doc.loopLengthTicks,
    bpm: doc.bpm,
    tempoMap: doc.tempoMap,
    meterMap: doc.meterMap,
    swing: doc.swing,
    masterVolume: doc.masterVolume,
    tracks: doc.tracks,
    buses: doc.buses,
    fragmentLibrary: doc.fragmentLibrary,
    modulators: doc.modulators ?? [],
    harmony: doc.harmony ?? defaultHarmony(),
  })

/**
 * Merge a snapshot's musical state OVER `doc`, producing a new doc. PRESERVES
 * the song's identity (`id`, `name`), structural constants (`schema`, `ppq`)
 * and `createdAt`; the bus regenerates `updatedAt` on commit. Deep-clones the
 * snapshot in so the resulting doc never aliases the stored scene (a future
 * edit must not corrupt the scene we loaded from).
 *
 * Pure: never mutates `doc` or `snap`. This IS the body of the `loadScene`
 * reducer case — exposed here so it is unit-testable without the bus.
 */
export const applySnapshot = (
  doc: BeatloungeDoc,
  snap: SceneSnapshot
): BeatloungeDoc => {
  const s = deepClone(snap)
  return {
    // identity + structural constants are preserved from the live doc
    schema: doc.schema,
    id: doc.id,
    name: doc.name,
    ppq: doc.ppq,
    createdAt: doc.createdAt,
    // musical state comes from the snapshot
    loopLengthTicks: s.loopLengthTicks,
    bpm: s.bpm,
    tempoMap: s.tempoMap,
    meterMap: s.meterMap,
    swing: s.swing,
    masterVolume: s.masterVolume,
    tracks: s.tracks,
    buses: s.buses,
    fragmentLibrary: s.fragmentLibrary,
    modulators: s.modulators,
    harmony: s.harmony,
    // updatedAt is set by the command bus on commit
    updatedAt: doc.updatedAt,
  }
}

/**
 * Structural equality of two snapshots' musical state — used to tell whether the
 * live doc still matches the last-loaded scene (the "unsaved changes" dot).
 * JSON compare is correct here because snapshots are plain JSON with stable key
 * order (built by captureSnapshot). Cheap relative to the user-gesture cadence.
 */
export const snapshotsEqual = (a: SceneSnapshot, b: SceneSnapshot): boolean =>
  JSON.stringify(a) === JSON.stringify(b)
