/**
 * beatlounge — THE WORLD-RHYTHMS CORPUS (data).
 *
 * A comprehensive, hand-authored bank of grooves from around the world, as
 * plain `Rhythm` data (see ./types). Patterns are written in cell indices on
 * each rhythm's grid; authentic enough that a musician recognises them. Lanes
 * are role-keyed (./roles maps roles → kit pitches at apply time).
 *
 * AUTHORING HELPERS (kept local so the data below reads like a score):
 *   • on(...cells)          → plain hits at those cells
 *   • accent(...cells)      → backbone/downbeat hits (flagged, vary protects)
 *   • ghost(...cells)       → quiet ghost hits (vary may add/drop first)
 *   • lane(role, hits, opt) → a Lane (opt.signature marks the backbone voice)
 *
 * Cell math: a one-bar 4/4 pattern is 4 beats × 4 = 16 sixteenth cells, so
 * cell 0 = beat 1, cell 4 = beat 2, … cell 12 = beat 4. A 6/8 pattern is
 * 2 beats × 3 = 6 cells; an Indian teental is 16 beats × 1 = 16 matra cells.
 */

import type { Hit, Lane, Rhythm, RhythmFamily, Role } from "./types"

// ----------------------------------------------------------------- authoring
const on = (...cells: number[]): Hit[] => cells.map((cell) => ({ cell }))
const accent = (...cells: number[]): Hit[] => cells.map((cell) => ({ cell, accent: true }))
const ghost = (...cells: number[]): Hit[] => cells.map((cell) => ({ cell, ghost: true }))

const lane = (
  role: Role,
  hits: Hit[],
  opt: { signature?: boolean; velocity?: number } = {}
): Lane => ({ role, hits, ...opt })

/** Merge several hit lists into one lane (so a lane can mix accents + ghosts). */
const merge = (...lists: Hit[][]): Hit[] => lists.flat()

// ================================================================ AFRO-CUBAN
const afroCuban: Rhythm[] = [
  {
    id: "son-clave-3-2",
    name: "Son Clave (3-2)",
    family: "afro-cuban",
    origin: "Cuba",
    blurb: "The keystone of Afro-Cuban music — the 3-2 son clave key pattern.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 96,
    tags: ["clave", "3-2", "son", "key-pattern"],
    lanes: [
      lane("clave", accent(0, 3, 6, 10, 12), { signature: true }),
    ],
  },
  {
    id: "son-clave-2-3",
    name: "Son Clave (2-3)",
    family: "afro-cuban",
    origin: "Cuba",
    blurb: "The 2-3 son clave — the same key pattern, started from its two side.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 96,
    tags: ["clave", "2-3", "son", "key-pattern"],
    lanes: [
      lane("clave", accent(4, 8, 12, 0, 6).sort((a, b) => a.cell - b.cell), { signature: true }),
    ],
  },
  {
    id: "rumba-clave-3-2",
    name: "Rumba Clave (3-2)",
    family: "afro-cuban",
    origin: "Cuba",
    blurb: "Rumba clave — the third stroke pushed a step later than son clave.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 100,
    tags: ["clave", "rumba", "3-2"],
    lanes: [
      lane("clave", accent(0, 3, 7, 10, 12), { signature: true }),
    ],
  },
  {
    id: "guaguanco",
    name: "Guaguancó",
    family: "afro-cuban",
    origin: "Cuba",
    blurb: "A rumba guaguancó: rumba clave over conga tumbao and palitos.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 104,
    tags: ["rumba", "guaguanco", "conga"],
    lanes: [
      lane("clave", accent(0, 3, 7, 10, 12), { signature: true }),
      lane("conga-lo", on(0, 6, 8), { velocity: 0.7 }),
      lane("conga-hi", merge(accent(10, 14), ghost(4)), { velocity: 0.8 }),
      lane("rim", on(2, 6, 10, 14), { velocity: 0.55 }),
    ],
  },
  {
    id: "cha-cha-cha",
    name: "Cha-Cha-Chá",
    family: "afro-cuban",
    origin: "Cuba",
    blurb: "The cha-cha-chá: the iconic triple step on beats 4-and-1.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 120,
    tags: ["cha-cha", "dance", "cowbell"],
    lanes: [
      lane("cowbell", accent(0, 4, 8, 12), { signature: true, velocity: 0.8 }),
      lane("conga-hi", on(12, 14), { velocity: 0.85 }),
      lane("conga-lo", on(0, 8), { velocity: 0.7 }),
      lane("guiro", on(0, 4, 6, 8, 12, 14), { velocity: 0.5 }),
    ],
  },
  {
    id: "mambo",
    name: "Mambo",
    family: "afro-cuban",
    origin: "Cuba",
    blurb: "A driving mambo: bell, conga tumbao and 2-3 clave.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 180,
    tags: ["mambo", "salsa", "bell"],
    lanes: [
      lane("clave", accent(4, 8, 12, 0, 6).sort((a, b) => a.cell - b.cell), { signature: true }),
      lane("cowbell", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.65 }),
      lane("conga-lo", on(0, 8), { velocity: 0.7 }),
      lane("conga-hi", on(6, 14), { velocity: 0.85 }),
    ],
  },
  {
    id: "songo",
    name: "Songo",
    family: "afro-cuban",
    origin: "Cuba",
    blurb: "Los Van Van's songo — a modern drum-set translation of the rumba feel.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 100,
    tags: ["songo", "drumset", "modern"],
    lanes: [
      lane("clave", accent(0, 3, 7, 10, 12), { signature: true }),
      lane("kick", on(3, 6, 11, 14), { velocity: 0.9 }),
      lane("snare", merge(accent(10), ghost(2, 6, 14)), { velocity: 0.8 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.45 }),
    ],
  },
  {
    id: "conga-comparsa",
    name: "Conga (Comparsa)",
    family: "afro-cuban",
    origin: "Cuba (Santiago)",
    blurb: "Carnival conga/comparsa — the relentless street-parade groove.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 120,
    tags: ["carnival", "comparsa", "parade"],
    lanes: [
      lane("cowbell", accent(0, 4, 8, 12), { signature: true, velocity: 0.8 }),
      lane("conga-lo", on(0, 6, 8, 14), { velocity: 0.75 }),
      lane("conga-hi", on(3, 4, 11, 12), { velocity: 0.85 }),
      lane("surdo", on(4, 12), { velocity: 0.9 }),
    ],
  },
  {
    id: "bolero-cuban",
    name: "Bolero",
    family: "afro-cuban",
    origin: "Cuba",
    blurb: "A slow Cuban bolero — tender, with sidestick and gentle clave.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 72,
    tags: ["bolero", "ballad", "slow"],
    lanes: [
      lane("clave", accent(0, 3, 6, 10, 12), { signature: true, velocity: 0.6 }),
      lane("sidestick", on(4, 12), { velocity: 0.55 }),
      lane("conga-lo", on(0, 8), { velocity: 0.5 }),
      lane("shaker", on(0, 4, 8, 12), { velocity: 0.4 }),
    ],
  },
  {
    id: "guajira",
    name: "Guajira",
    family: "afro-cuban",
    origin: "Cuba",
    blurb: "A lilting guajira in 6/8-feel — countryside son with a swung bell.",
    beats: 4,
    stepsPerBeat: 3,
    timeSig: "12/8",
    bpm: 96,
    tags: ["guajira", "6/8", "country"],
    lanes: [
      lane("clave", accent(0, 2, 4, 7, 10), { signature: true }),
      lane("cowbell", on(0, 3, 6, 9), { velocity: 0.6 }),
      lane("conga-lo", on(0, 6), { velocity: 0.65 }),
      lane("conga-hi", on(4, 10), { velocity: 0.8 }),
    ],
  },
]

// ================================================================ BRAZILIAN
const brazilian: Rhythm[] = [
  {
    id: "samba",
    name: "Samba",
    family: "brazilian",
    origin: "Brazil (Rio)",
    blurb: "The batucada samba: surdo heartbeat, ganzá drive and tamborim.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 100,
    tags: ["samba", "batucada", "carnival"],
    lanes: [
      lane("surdo", accent(4, 12), { signature: true, velocity: 0.95 }),
      lane("surdo-hi", on(0, 8), { velocity: 0.6 }),
      lane("ganza", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.45 }),
      lane("tamborim", on(0, 3, 4, 7, 8, 11, 12, 15), { velocity: 0.6 }),
      lane("caixa", merge(accent(0, 4, 8, 12), ghost(2, 6, 10, 14)), { velocity: 0.7 }),
    ],
  },
  {
    id: "bossa-nova",
    name: "Bossa Nova",
    family: "brazilian",
    origin: "Brazil (Rio)",
    blurb: "The cool bossa: a sambafied clave on the rim over a soft kick.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 130,
    tags: ["bossa", "jazz", "cool"],
    lanes: [
      lane("rim", accent(0, 3, 6, 10, 12), { signature: true, velocity: 0.6 }),
      lane("kick", on(0, 6, 8, 14), { velocity: 0.75 }),
      lane("closed-hat", on(2, 6, 10, 14), { velocity: 0.4 }),
    ],
  },
  {
    id: "partido-alto",
    name: "Partido Alto",
    family: "brazilian",
    origin: "Brazil",
    blurb: "The syncopated partido-alto pattern — the engine of modern samba.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 104,
    tags: ["partido-alto", "samba", "syncopation"],
    lanes: [
      lane("tamborim", accent(2, 3, 6, 8, 11, 14), { signature: true, velocity: 0.7 }),
      lane("surdo", on(4, 12), { velocity: 0.9 }),
      lane("ganza", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.4 }),
      lane("pandeiro", on(0, 3, 4, 7, 8, 11, 12, 15), { velocity: 0.5 }),
    ],
  },
  {
    id: "baiao",
    name: "Baião",
    family: "brazilian",
    origin: "Brazil (Northeast)",
    blurb: "Luiz Gonzaga's baião — the zabumba dum-…-tek that defines forró.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 110,
    tags: ["baiao", "forro", "northeast"],
    lanes: [
      lane("surdo", accent(0, 6), { signature: true, velocity: 0.95 }),
      lane("hi-tom", on(4, 12), { velocity: 0.7 }),
      lane("triangle", on(0, 2, 3, 4, 6, 8, 10, 11, 12, 14), { velocity: 0.45 }),
    ],
  },
  {
    id: "maracatu",
    name: "Maracatu",
    family: "brazilian",
    origin: "Brazil (Pernambuco)",
    blurb: "Maracatu de baque virado — booming alfaias and a snare entrance.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 100,
    tags: ["maracatu", "alfaia", "afro-brazilian"],
    lanes: [
      lane("surdo", accent(0, 3, 6, 8, 14), { signature: true, velocity: 0.95 }),
      lane("caixa", on(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15), { velocity: 0.45 }),
      lane("agogo", on(0, 4, 6, 10, 12), { velocity: 0.6 }),
    ],
  },
]

// ================================================================ CARIBBEAN
const caribbean: Rhythm[] = [
  {
    id: "reggaeton-dembow",
    name: "Reggaetón (Dembow)",
    family: "caribbean",
    origin: "Puerto Rico / Panama",
    blurb: "The dembow: the boom-ch-boom-chick that powers reggaetón.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 95,
    tags: ["reggaeton", "dembow", "dance"],
    lanes: [
      lane("snare", accent(3, 6, 11, 14), { signature: true, velocity: 0.85 }),
      lane("kick", on(0, 6, 8, 14), { velocity: 0.95 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.45 }),
    ],
  },
  {
    id: "reggae-one-drop",
    name: "Reggae (One Drop)",
    family: "caribbean",
    origin: "Jamaica",
    blurb: "The one-drop: beat 1 left empty, the hit lands on the THREE.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 76,
    tags: ["reggae", "one-drop", "roots"],
    lanes: [
      lane("kick", accent(8), { signature: true, velocity: 0.95 }),
      lane("snare", on(8), { velocity: 0.8 }),
      lane("rim", on(4, 12), { velocity: 0.5 }),
      lane("closed-hat", on(2, 6, 10, 14), { velocity: 0.45 }),
    ],
  },
  {
    id: "reggae-steppers",
    name: "Reggae (Steppers)",
    family: "caribbean",
    origin: "Jamaica",
    blurb: "Steppers/rockers: four-on-the-floor kick under a militant reggae feel.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 78,
    tags: ["reggae", "steppers", "rockers"],
    lanes: [
      lane("kick", accent(0, 4, 8, 12), { signature: true, velocity: 0.9 }),
      lane("snare", on(8), { velocity: 0.8 }),
      lane("rim", on(4, 12), { velocity: 0.5 }),
      lane("open-hat", on(2, 6, 10, 14), { velocity: 0.5 }),
    ],
  },
  {
    id: "dancehall",
    name: "Dancehall",
    family: "caribbean",
    origin: "Jamaica",
    blurb: "Digital dancehall — a sparse, heavy riddim built on the snare answer.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 100,
    tags: ["dancehall", "riddim", "digital"],
    lanes: [
      lane("snare", accent(4, 12), { signature: true, velocity: 0.85 }),
      lane("kick", on(0, 3, 8, 10), { velocity: 0.95 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.4 }),
    ],
  },
  {
    id: "soca",
    name: "Soca",
    family: "caribbean",
    origin: "Trinidad & Tobago",
    blurb: "Up-tempo soca — a four-on-the-floor carnival pulse with an off-beat hat.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 130,
    tags: ["soca", "carnival", "trinidad"],
    lanes: [
      lane("kick", accent(0, 4, 8, 12), { signature: true, velocity: 0.95 }),
      lane("snare", on(4, 12), { velocity: 0.8 }),
      lane("open-hat", on(2, 6, 10, 14), { velocity: 0.55 }),
      lane("cowbell", on(0, 4, 8, 12), { velocity: 0.5 }),
    ],
  },
  {
    id: "calypso",
    name: "Calypso",
    family: "caribbean",
    origin: "Trinidad & Tobago",
    blurb: "Classic calypso — a lilting two-feel with iron and a relaxed clave.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 120,
    tags: ["calypso", "iron", "two-feel"],
    lanes: [
      lane("clave", accent(0, 3, 6, 10, 12), { signature: true }),
      lane("cowbell", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.55 }),
      lane("kick", on(0, 8), { velocity: 0.85 }),
      lane("snare", on(4, 12), { velocity: 0.75 }),
    ],
  },
  {
    id: "merengue",
    name: "Merengue",
    family: "caribbean",
    origin: "Dominican Republic",
    blurb: "Fast merengue — the güira's relentless scrape over a tambora rock.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 140,
    tags: ["merengue", "guira", "tambora"],
    lanes: [
      lane("guira", accent(0, 2, 4, 6, 8, 10, 12, 14), { signature: true, velocity: 0.5 }),
      lane("conga-lo", on(0, 8), { velocity: 0.85 }),
      lane("conga-hi", on(3, 7, 11, 15), { velocity: 0.7 }),
      lane("kick", on(0, 4, 8, 12), { velocity: 0.85 }),
    ],
  },
  {
    id: "bomba",
    name: "Bomba (Sicá)",
    family: "caribbean",
    origin: "Puerto Rico",
    blurb: "Bomba sicá — the buleador ostinato that the dancer challenges.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 110,
    tags: ["bomba", "puerto-rico", "barril"],
    lanes: [
      lane("conga-lo", accent(0, 3, 8, 11), { signature: true, velocity: 0.8 }),
      lane("conga-hi", on(4, 12), { velocity: 0.85 }),
      lane("cua", on(0, 2, 4, 6, 8, 10, 12, 14).map((c) => c), { velocity: 0.5 }),
      lane("maracas", on(0, 4, 8, 12), { velocity: 0.45 }),
    ],
  },
  {
    id: "plena",
    name: "Plena",
    family: "caribbean",
    origin: "Puerto Rico",
    blurb: "Plena — the 'sung newspaper' driven by interlocking panderos.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 116,
    tags: ["plena", "pandero", "puerto-rico"],
    lanes: [
      lane("pandeiro", accent(0, 4, 8, 12), { signature: true, velocity: 0.7 }),
      lane("tambourine", on(2, 3, 6, 7, 10, 11, 14, 15), { velocity: 0.55 }),
      lane("conga-lo", on(0, 8), { velocity: 0.75 }),
    ],
  },
]

// ============================================================ NORTH AMERICAN
const northAmerican: Rhythm[] = [
  {
    id: "four-on-the-floor",
    name: "Four on the Floor (House)",
    family: "north-american",
    origin: "USA (Chicago)",
    blurb: "House music's foundation — a kick on every beat, off-beat open hats.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 124,
    tags: ["house", "four-on-the-floor", "dance"],
    lanes: [
      lane("kick", accent(0, 4, 8, 12), { signature: true, velocity: 0.95 }),
      lane("open-hat", on(2, 6, 10, 14), { velocity: 0.5 }),
      lane("closed-hat", on(0, 4, 8, 12), { velocity: 0.4 }),
      lane("clap", on(4, 12), { velocity: 0.7 }),
    ],
  },
  {
    id: "disco",
    name: "Disco",
    family: "north-american",
    origin: "USA",
    blurb: "Classic disco — four-on-the-floor with the signature off-beat open hat.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 118,
    tags: ["disco", "four-on-the-floor", "70s"],
    lanes: [
      lane("kick", accent(0, 4, 8, 12), { signature: true, velocity: 0.9 }),
      lane("snare", on(4, 12), { velocity: 0.8 }),
      lane("open-hat", on(2, 6, 10, 14), { velocity: 0.55 }),
      lane("closed-hat", on(0, 4, 8, 12), { velocity: 0.4 }),
    ],
  },
  {
    id: "boom-bap",
    name: "Hip-Hop (Boom Bap)",
    family: "north-american",
    origin: "USA (NYC)",
    blurb: "Boom-bap: a swung, dusty kick-snare with the classic 'boom… bap'.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 90,
    tags: ["hip-hop", "boom-bap", "swing"],
    lanes: [
      lane("kick", accent(0, 7, 8), { signature: true, velocity: 0.95 }),
      lane("snare", on(4, 12), { velocity: 0.85 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.45 }),
    ],
  },
  {
    id: "trap",
    name: "Trap",
    family: "north-american",
    origin: "USA (Atlanta)",
    blurb: "Trap — booming 808 kick, a clap on 3, and rolling hi-hat triplets.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 140,
    tags: ["trap", "808", "hats"],
    lanes: [
      lane("clap", accent(8), { signature: true, velocity: 0.85 }),
      lane("kick", on(0, 6, 8, 11), { velocity: 0.95 }),
      lane("closed-hat", merge(on(0, 2, 4, 6, 8, 10, 12), [{ cell: 14, ratchet: 3 }]), { velocity: 0.45 }),
    ],
  },
  {
    id: "funk-the-one",
    name: "Funk (The One)",
    family: "north-american",
    origin: "USA",
    blurb: "James Brown funk — everything serves THE ONE; a syncopated 16th kick.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 104,
    tags: ["funk", "the-one", "syncopation"],
    lanes: [
      lane("kick", accent(0), { signature: true, velocity: 0.95 }),
      lane("kick", on(3, 6, 10), { velocity: 0.8 }),
      lane("snare", merge(accent(4, 12), ghost(7, 14)), { velocity: 0.85 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.5 }),
    ],
  },
  {
    id: "motown",
    name: "Motown",
    family: "north-american",
    origin: "USA (Detroit)",
    blurb: "The Motown backbeat — tambourine on every beat over a four-feel snare.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 120,
    tags: ["motown", "backbeat", "soul"],
    lanes: [
      lane("snare", accent(4, 12), { signature: true, velocity: 0.85 }),
      lane("tambourine", on(0, 4, 8, 12), { velocity: 0.55 }),
      lane("kick", on(0, 8), { velocity: 0.9 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.4 }),
    ],
  },
  {
    id: "second-line",
    name: "New Orleans (Second Line)",
    family: "north-american",
    origin: "USA (New Orleans)",
    blurb: "The gut-bucket second-line — a rolling, syncopated street-parade groove.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 96,
    tags: ["new-orleans", "second-line", "parade"],
    lanes: [
      lane("kick", accent(0, 3, 8, 10), { signature: true, velocity: 0.9 }),
      lane("snare", merge(accent(4, 6, 12), ghost(2, 10, 14)), { velocity: 0.8 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.45 }),
    ],
  },
  {
    id: "swing",
    name: "Swing (Jazz)",
    family: "north-american",
    origin: "USA",
    blurb: "The jazz ride-cymbal swing — spang-a-lang with hat on 2 and 4.",
    beats: 4,
    stepsPerBeat: 3,
    timeSig: "4/4 swing",
    bpm: 140,
    tags: ["jazz", "swing", "ride"],
    lanes: [
      lane("ride", accent(0, 3, 5, 6, 9, 11), { signature: true, velocity: 0.7 }),
      lane("pedal-hat", on(3, 9), { velocity: 0.55 }),
      lane("kick", on(0, 6), { velocity: 0.4 }),
    ],
  },
  {
    id: "shuffle",
    name: "Shuffle",
    family: "north-american",
    origin: "USA",
    blurb: "The triplet shuffle — that loping, long-short hand on the hat.",
    beats: 4,
    stepsPerBeat: 3,
    timeSig: "4/4 shuffle",
    bpm: 110,
    tags: ["shuffle", "blues", "triplet"],
    lanes: [
      lane("closed-hat", accent(0, 2, 3, 5, 6, 8, 9, 11), { signature: true, velocity: 0.5 }),
      lane("kick", on(0, 6), { velocity: 0.9 }),
      lane("snare", on(3, 9), { velocity: 0.85 }),
    ],
  },
  {
    id: "blues-12-8",
    name: "12/8 Blues",
    family: "north-american",
    origin: "USA",
    blurb: "Slow 12/8 blues — that rolling triplet church-and-bar-room feel.",
    beats: 4,
    stepsPerBeat: 3,
    timeSig: "12/8",
    bpm: 60,
    tags: ["blues", "12/8", "slow"],
    lanes: [
      lane("ride", accent(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), { signature: true, velocity: 0.55 }),
      lane("kick", on(0, 6), { velocity: 0.9 }),
      lane("snare", on(3, 9), { velocity: 0.85 }),
    ],
  },
  {
    id: "rock-backbeat",
    name: "Rock (Backbeat)",
    family: "north-american",
    origin: "USA / UK",
    blurb: "The bedrock rock beat — eighth hats, kick on 1 & 3, snare on 2 & 4.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 120,
    tags: ["rock", "backbeat", "straight"],
    lanes: [
      lane("snare", accent(4, 12), { signature: true, velocity: 0.85 }),
      lane("kick", on(0, 8), { velocity: 0.95 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.5 }),
    ],
  },
  {
    id: "country-train",
    name: "Country (Train Beat)",
    family: "north-american",
    origin: "USA (Nashville)",
    blurb: "The 'train beat' — a chugging brush-snare sixteenth shuffle.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 132,
    tags: ["country", "train", "brushes"],
    lanes: [
      lane("snare", merge(accent(4, 12), ghost(0, 2, 6, 8, 10, 14)), { signature: true, velocity: 0.7 }),
      lane("kick", on(0, 8), { velocity: 0.9 }),
      lane("rim", on(4, 12), { velocity: 0.5 }),
    ],
  },
]

// ================================================================ ELECTRONIC
const electronic: Rhythm[] = [
  {
    id: "drum-and-bass",
    name: "Drum & Bass",
    family: "electronic",
    origin: "UK",
    blurb: "Fast breakbeat science — a chopped two-step at 174 BPM.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 174,
    tags: ["dnb", "breakbeat", "fast"],
    lanes: [
      lane("snare", accent(4, 12), { signature: true, velocity: 0.85 }),
      lane("kick", on(0, 10), { velocity: 0.95 }),
      lane("closed-hat", on(2, 6, 10, 14), { velocity: 0.45 }),
      lane("closed-hat", ghost(0, 4, 8, 12), { velocity: 0.3 }),
    ],
  },
  {
    id: "amen-break",
    name: "Amen Break",
    family: "electronic",
    origin: "USA / UK",
    blurb: "The most-sampled break ever — the Winstons' syncopated kick-snare.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 138,
    tags: ["amen", "breakbeat", "sample"],
    lanes: [
      lane("snare", accent(4, 7, 10, 12, 15), { signature: true, velocity: 0.85 }),
      lane("kick", on(0, 2, 10), { velocity: 0.95 }),
      lane("ride", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.4 }),
    ],
  },
  {
    id: "breakbeat",
    name: "Breakbeat",
    family: "electronic",
    origin: "UK / USA",
    blurb: "Big-beat breakbeat — a funky, chopped backbeat with a swung kick.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 130,
    tags: ["breakbeat", "big-beat"],
    lanes: [
      lane("snare", accent(4, 12), { signature: true, velocity: 0.85 }),
      lane("kick", on(0, 6, 8, 11), { velocity: 0.95 }),
      lane("open-hat", on(14), { velocity: 0.5 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12), { velocity: 0.4 }),
    ],
  },
  {
    id: "dub",
    name: "Dub",
    family: "electronic",
    origin: "Jamaica / UK",
    blurb: "Heavy dub — a steppers kick and a deep, spacious rim with echo room.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 70,
    tags: ["dub", "steppers", "echo"],
    lanes: [
      lane("kick", accent(0, 4, 8, 12), { signature: true, velocity: 0.95 }),
      lane("rim", on(8), { velocity: 0.7 }),
      lane("closed-hat", on(2, 6, 10, 14), { velocity: 0.4 }),
    ],
  },
  {
    id: "techno",
    name: "Techno",
    family: "electronic",
    origin: "USA (Detroit) / Germany",
    blurb: "Driving techno — a relentless four-on-the-floor with a ghosted off-beat.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 132,
    tags: ["techno", "four-on-the-floor", "machine"],
    lanes: [
      lane("kick", accent(0, 4, 8, 12), { signature: true, velocity: 0.95 }),
      lane("closed-hat", on(2, 6, 10, 14), { velocity: 0.4 }),
      lane("open-hat", on(2, 10), { velocity: 0.45 }),
      lane("rim", on(6, 14), { velocity: 0.5 }),
    ],
  },
  {
    id: "garage-2step",
    name: "UK Garage (2-Step)",
    family: "electronic",
    origin: "UK",
    blurb: "2-step garage — a skippy, shuffled kick-snare with swung sixteenths.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 132,
    tags: ["garage", "2-step", "uk", "swing"],
    lanes: [
      lane("snare", accent(4, 12), { signature: true, velocity: 0.8 }),
      lane("kick", on(0, 7, 10), { velocity: 0.95 }),
      lane("closed-hat", on(2, 5, 6, 9, 11, 14), { velocity: 0.45 }),
    ],
  },
  {
    id: "footwork",
    name: "Footwork (Juke)",
    family: "electronic",
    origin: "USA (Chicago)",
    blurb: "Chicago footwork — frantic triplet kicks and claps at 160 BPM.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 160,
    tags: ["footwork", "juke", "chicago"],
    lanes: [
      lane("kick", accent(0, 3, 5, 8, 11, 13), { signature: true, velocity: 0.9 }),
      lane("clap", on(4, 12), { velocity: 0.8 }),
      lane("closed-hat", on(2, 6, 10, 14), { velocity: 0.4 }),
    ],
  },
]

// =================================================================== AFRICAN
const african: Rhythm[] = [
  {
    id: "afrobeat",
    name: "Afrobeat",
    family: "african",
    origin: "Nigeria",
    blurb: "Fela's afrobeat — interlocking parts over a tireless shekere and bell.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 110,
    tags: ["afrobeat", "fela", "highlife"],
    lanes: [
      lane("clave", accent(0, 3, 6, 10, 12), { signature: true }),
      lane("kick", on(0, 6, 8, 14), { velocity: 0.9 }),
      lane("snare", merge(accent(4, 12), ghost(2, 6, 10, 14)), { velocity: 0.75 }),
      lane("shekere", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.45 }),
      lane("conga-hi", on(3, 11), { velocity: 0.8 }),
    ],
  },
  {
    id: "highlife",
    name: "Highlife",
    family: "african",
    origin: "Ghana",
    blurb: "Ghanaian highlife — a bright, lilting bell-driven dance groove.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 120,
    tags: ["highlife", "ghana", "bell"],
    lanes: [
      lane("agogo", accent(0, 2, 4, 7, 9, 11, 12, 14), { signature: true, velocity: 0.6 }),
      lane("conga-lo", on(0, 8), { velocity: 0.75 }),
      lane("conga-hi", on(4, 12), { velocity: 0.8 }),
      lane("shaker", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.4 }),
    ],
  },
  {
    id: "soukous",
    name: "Soukous",
    family: "african",
    origin: "DR Congo",
    blurb: "Congolese soukous — a fast, snare-rolling sebene dance feel.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 138,
    tags: ["soukous", "congo", "sebene"],
    lanes: [
      lane("snare", accent(4, 12), { signature: true, velocity: 0.8 }),
      lane("kick", on(0, 8), { velocity: 0.9 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.45 }),
      lane("conga-hi", on(2, 6, 10, 14), { velocity: 0.6 }),
    ],
  },
  {
    id: "gnawa",
    name: "Gnawa",
    family: "african",
    origin: "Morocco",
    blurb: "Gnawa — a hypnotic, swung 6/8 over the qraqeb's metallic clatter.",
    beats: 2,
    stepsPerBeat: 3,
    timeSig: "6/8",
    bpm: 90,
    tags: ["gnawa", "morocco", "6/8", "trance"],
    lanes: [
      lane("djembe", accent(0, 3), { signature: true, velocity: 0.9 }),
      lane("djembe-slap", on(2, 5), { velocity: 0.7 }),
      lane("castanets", on(0, 1, 2, 3, 4, 5), { velocity: 0.45 }),
    ],
  },
]

// ====================================================== EUROPEAN / MEDITERRANEAN
const european: Rhythm[] = [
  {
    id: "tango",
    name: "Tango",
    family: "european",
    origin: "Argentina / Uruguay",
    blurb: "The tango marcato — a strong, even four with a dramatic accent.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 116,
    tags: ["tango", "marcato", "argentina"],
    lanes: [
      lane("kick", accent(0, 4, 8, 12), { signature: true, velocity: 0.9 }),
      lane("rim", on(6, 14), { velocity: 0.6 }),
      lane("snare", on(12), { velocity: 0.7 }),
    ],
  },
  {
    id: "milonga",
    name: "Milonga",
    family: "european",
    origin: "Argentina / Uruguay",
    blurb: "Milonga — tango's older, faster cousin on a habanera bassline.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 100,
    tags: ["milonga", "habanera", "argentina"],
    lanes: [
      lane("kick", accent(0, 3, 8, 11), { signature: true, velocity: 0.9 }),
      lane("rim", on(0, 3, 6, 8, 11, 14), { velocity: 0.55 }),
    ],
  },
  {
    id: "waltz",
    name: "Waltz",
    family: "european",
    origin: "Austria / Germany",
    blurb: "The Viennese waltz — ONE-two-three, the oom-pah-pah lilt in 3/4.",
    beats: 3,
    stepsPerBeat: 4,
    timeSig: "3/4",
    bpm: 150,
    tags: ["waltz", "3/4", "oom-pah-pah"],
    lanes: [
      lane("kick", accent(0), { signature: true, velocity: 0.9 }),
      lane("snare", on(4, 8), { velocity: 0.6 }),
      lane("closed-hat", on(0, 4, 8), { velocity: 0.4 }),
    ],
  },
  {
    id: "polka",
    name: "Polka",
    family: "european",
    origin: "Central Europe",
    blurb: "The bouncing polka — a brisk oom-pah two-feel.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "2/4",
    bpm: 120,
    tags: ["polka", "oom-pah", "two-feel"],
    lanes: [
      lane("kick", accent(0, 8), { signature: true, velocity: 0.9 }),
      lane("snare", on(4, 12), { velocity: 0.75 }),
      lane("closed-hat", on(0, 2, 4, 6, 8, 10, 12, 14), { velocity: 0.45 }),
    ],
  },
  {
    id: "bulería",
    name: "Bulería (Flamenco)",
    family: "european",
    origin: "Spain (Andalusia)",
    blurb: "The 12-beat flamenco bulería compás — palmas accenting 12,3,6,8,10.",
    beats: 12,
    stepsPerBeat: 1,
    timeSig: "12 compás",
    bpm: 200,
    tags: ["flamenco", "buleria", "compas", "palmas"],
    lanes: [
      // Compás accents (0-based): 11,2,5,7,9 ↔ the traditional 12,3,6,8,10.
      lane("palmas", merge(accent(11, 2, 5, 7, 9), on(0, 1, 3, 4, 6, 8, 10)), {
        signature: true,
        velocity: 0.65,
      }),
      lane("castanets", on(11, 2, 5, 7, 9), { velocity: 0.7 }),
    ],
  },
  {
    id: "rumba-flamenca",
    name: "Rumba Flamenca",
    family: "european",
    origin: "Spain",
    blurb: "Rumba flamenca — the Gipsy-Kings clap-and-cajón party groove.",
    beats: 4,
    stepsPerBeat: 4,
    timeSig: "4/4",
    bpm: 104,
    tags: ["flamenco", "rumba", "cajon"],
    lanes: [
      lane("palmas", accent(0, 3, 4, 6, 8, 11, 12, 14), { signature: true, velocity: 0.6 }),
      lane("conga-lo", on(0, 8), { velocity: 0.85 }),
      lane("conga-slap", on(4, 12), { velocity: 0.8 }),
    ],
  },
  {
    id: "sevillanas",
    name: "Sevillanas",
    family: "european",
    origin: "Spain (Seville)",
    blurb: "Sevillanas — a bright 3/4 fair-day dance with castanets.",
    beats: 3,
    stepsPerBeat: 4,
    timeSig: "3/4",
    bpm: 140,
    tags: ["flamenco", "sevillanas", "3/4"],
    lanes: [
      lane("palmas", accent(0, 4, 8), { signature: true, velocity: 0.6 }),
      lane("castanets", on(0, 2, 4, 6, 8, 10), { velocity: 0.55 }),
      lane("conga-lo", on(0), { velocity: 0.8 }),
    ],
  },
]

// =========================================================== MIDDLE EASTERN (iqa'at)
const middleEastern: Rhythm[] = [
  {
    id: "maqsum",
    name: "Maqsūm",
    family: "middle-eastern",
    origin: "Egypt / Levant",
    blurb: "The most common Arabic rhythm — DUM-tek-…-tek-DUM-…-tek (8-beat).",
    beats: 4,
    stepsPerBeat: 2,
    timeSig: "4/4",
    bpm: 110,
    tags: ["iqa", "maqsum", "arabic"],
    lanes: [
      lane("doumbek", accent(0, 3), { signature: true, velocity: 0.95 }),
      lane("doumbek-tek", on(2, 5, 7), { velocity: 0.7 }),
    ],
  },
  {
    id: "baladi",
    name: "Baladi",
    family: "middle-eastern",
    origin: "Egypt",
    blurb: "Baladi — DUM-DUM-…-tek-…-DUM-…-tek; earthy and grounded.",
    beats: 4,
    stepsPerBeat: 2,
    timeSig: "4/4",
    bpm: 100,
    tags: ["iqa", "baladi", "arabic"],
    lanes: [
      lane("doumbek", accent(0, 1, 4), { signature: true, velocity: 0.95 }),
      lane("doumbek-tek", on(3, 5, 7), { velocity: 0.7 }),
    ],
  },
  {
    id: "saidi",
    name: "Saïdi",
    family: "middle-eastern",
    origin: "Egypt (Upper)",
    blurb: "Saïdi — DUM-…-tek-DUM-DUM-…-tek; the cane-dance rhythm with twin dums.",
    beats: 4,
    stepsPerBeat: 2,
    timeSig: "4/4",
    bpm: 108,
    tags: ["iqa", "saidi", "arabic"],
    lanes: [
      lane("doumbek", accent(0, 3, 4), { signature: true, velocity: 0.95 }),
      lane("doumbek-tek", on(2, 7), { velocity: 0.7 }),
    ],
  },
  {
    id: "ayoub",
    name: "Ayyūb",
    family: "middle-eastern",
    origin: "Egypt / Sudan",
    blurb: "Ayyūb — DUM-…-tek-DUM; a fast, trance-inducing two-beat (zār).",
    beats: 2,
    stepsPerBeat: 2,
    timeSig: "2/4",
    bpm: 120,
    tags: ["iqa", "ayoub", "zar", "trance"],
    lanes: [
      lane("doumbek", accent(0, 3), { signature: true, velocity: 0.95 }),
      lane("doumbek-tek", on(2), { velocity: 0.7 }),
    ],
  },
  {
    id: "malfuf",
    name: "Malfūf",
    family: "middle-eastern",
    origin: "Levant",
    blurb: "Malfūf — DUM-…-tek-…-tek; a quick processional 2/4 march.",
    beats: 2,
    stepsPerBeat: 4,
    timeSig: "2/4",
    bpm: 120,
    tags: ["iqa", "malfuf", "march"],
    lanes: [
      lane("doumbek", accent(0), { signature: true, velocity: 0.95 }),
      lane("doumbek-tek", on(3, 6), { velocity: 0.7 }),
    ],
  },
  {
    id: "chiftetelli",
    name: "Çiftetelli",
    family: "middle-eastern",
    origin: "Turkey / Greece",
    blurb: "Çiftetelli — a slow, sinuous 8-beat for the taqsim and veil dance.",
    beats: 4,
    stepsPerBeat: 2,
    timeSig: "4/4",
    bpm: 90,
    tags: ["iqa", "chiftetelli", "turkish", "slow"],
    lanes: [
      lane("doumbek", accent(0, 3, 4), { signature: true, velocity: 0.9 }),
      lane("doumbek-tek", on(2, 6, 7), { velocity: 0.65 }),
      lane("riq", on(0, 2, 4, 6), { velocity: 0.4 }),
    ],
  },
]

// =================================================================== INDIAN (talas)
const indian: Rhythm[] = [
  {
    id: "teental",
    name: "Teental (16)",
    family: "indian",
    origin: "India (Hindustani)",
    blurb: "Teental — the 16-matra cycle in 4+4+4+4, with tali on 1, 5 and 13.",
    beats: 16,
    stepsPerBeat: 1,
    timeSig: "16/4",
    bpm: 120,
    tags: ["tala", "teental", "16", "hindustani"],
    lanes: [
      // Tali (clap) accents: matras 1,5,13 → cells 0,4,12. Khali (wave) at 9.
      lane("tabla", merge(accent(0, 4, 12), on(1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15)), {
        signature: true,
        velocity: 0.7,
      }),
      lane("tabla-bass", on(0, 4, 12), { velocity: 0.85 }),
    ],
  },
  {
    id: "jhaptal",
    name: "Jhaptal (10)",
    family: "indian",
    origin: "India (Hindustani)",
    blurb: "Jhaptal — a 10-matra cycle grouped 2+3+2+3.",
    beats: 10,
    stepsPerBeat: 1,
    timeSig: "10/4",
    bpm: 110,
    tags: ["tala", "jhaptal", "10"],
    lanes: [
      // Vibhag accents at matras 1,3,6,8 → cells 0,2,5,7.
      lane("tabla", merge(accent(0, 2, 5, 7), on(1, 3, 4, 6, 8, 9)), {
        signature: true,
        velocity: 0.7,
      }),
      lane("tabla-bass", on(0, 5), { velocity: 0.85 }),
    ],
  },
  {
    id: "rupak",
    name: "Rupak (7)",
    family: "indian",
    origin: "India (Hindustani)",
    blurb: "Rupak — a 7-matra cycle in 3+2+2, uniquely starting on khali.",
    beats: 7,
    stepsPerBeat: 1,
    timeSig: "7/4",
    bpm: 120,
    tags: ["tala", "rupak", "7"],
    lanes: [
      // Vibhag at matras 1,4,6 → cells 0,3,5 (1 is khali but a structural beat).
      lane("tabla", merge(accent(0, 3, 5), on(1, 2, 4, 6)), { signature: true, velocity: 0.7 }),
      lane("tabla-bass", on(3, 5), { velocity: 0.85 }),
    ],
  },
  {
    id: "dadra",
    name: "Dadra (6)",
    family: "indian",
    origin: "India (light classical)",
    blurb: "Dadra — a 6-matra cycle in 3+3, the lilting light-classical feel.",
    beats: 6,
    stepsPerBeat: 1,
    timeSig: "6/4",
    bpm: 120,
    tags: ["tala", "dadra", "6"],
    lanes: [
      lane("tabla", merge(accent(0, 3), on(1, 2, 4, 5)), { signature: true, velocity: 0.7 }),
      lane("tabla-bass", on(0), { velocity: 0.85 }),
    ],
  },
  {
    id: "ektal",
    name: "Ektal (12)",
    family: "indian",
    origin: "India (Hindustani)",
    blurb: "Ektal — a 12-matra cycle in six groups of two, for slow khayal.",
    beats: 12,
    stepsPerBeat: 1,
    timeSig: "12/4",
    bpm: 96,
    tags: ["tala", "ektal", "12"],
    lanes: [
      // Tali/khali at matras 1,3,5,7,9,11 → cells 0,2,4,6,8,10.
      lane("tabla", merge(accent(0, 2, 4, 6, 8, 10), on(1, 3, 5, 7, 9, 11)), {
        signature: true,
        velocity: 0.7,
      }),
      lane("tabla-bass", on(0, 4, 8), { velocity: 0.85 }),
    ],
  },
  {
    id: "keherwa",
    name: "Keherwa (8)",
    family: "indian",
    origin: "India (light classical)",
    blurb: "Keherwa — the 8-matra dha-ge-na-ti groove behind countless folk songs.",
    beats: 8,
    stepsPerBeat: 1,
    timeSig: "8/4",
    bpm: 120,
    tags: ["tala", "keherwa", "8"],
    lanes: [
      lane("tabla", merge(accent(0, 4), on(1, 2, 3, 5, 6, 7)), { signature: true, velocity: 0.7 }),
      lane("tabla-bass", on(0, 4), { velocity: 0.85 }),
    ],
  },
]

// =================================================================== EXPORT
/** Every rhythm in the corpus, in a stable display order (family by family). */
export const RHYTHMS: Rhythm[] = [
  ...afroCuban,
  ...brazilian,
  ...caribbean,
  ...northAmerican,
  ...electronic,
  ...african,
  ...european,
  ...middleEastern,
  ...indian,
]

/** Family display metadata, in picker order. */
export const FAMILY_META: { family: RhythmFamily; label: string; blurb: string }[] = [
  { family: "afro-cuban", label: "Afro-Cuban / Latin", blurb: "Clave, rumba, mambo, cha-cha-chá" },
  { family: "brazilian", label: "Brazilian", blurb: "Samba, bossa, baião, maracatu" },
  { family: "caribbean", label: "Caribbean", blurb: "Reggaetón, reggae, soca, merengue" },
  { family: "north-american", label: "North American", blurb: "House, hip-hop, funk, rock, jazz" },
  { family: "electronic", label: "Electronic / Breaks", blurb: "DnB, techno, breakbeat, garage" },
  { family: "african", label: "African", blurb: "Afrobeat, highlife, soukous, gnawa" },
  { family: "european", label: "European / Mediterranean", blurb: "Tango, waltz, flamenco, polka" },
  { family: "middle-eastern", label: "Middle Eastern", blurb: "Maqsūm, baladi, saïdi, malfūf" },
  { family: "indian", label: "Indian Talas", blurb: "Teental, jhaptal, rupak, keherwa" },
]
