#!/bin/bash

set -e

files=(
    "00-00-00-unit-intro-foundations-of-history.md"
    "00-01-00-chapter-intro-what-is-history.md"
    "00-01-01-section-the-purpose-of-studying-history-and-its-role-in-society.md"
    "00-01-02-section-how-historical-narratives-are-shaped-by-culture-politics-and-power.md"
    "00-01-03-section-history-as-propaganda-how-the-victors-write-their-own-accounts.md"
    "00-01-04-section-how-our-understanding-of-the-past-evolves-with-new-evidence-and-perspectives.md"
    "00-01-05-section-how-this-book-was-written-the-challenges-of-historical-research-and-why-critical-thinking-is-essential.md"
    "00-02-00-chapter-intro-how-historians-study-the-past.md"
    "00-02-01-section-primary-vs-secondary-sources-how-historians-evaluate-evidence.md"
    "00-02-02-section-archaeology-and-learning-from-ruins-what-artifacts-tell-us-about-the-past.md"
    "00-02-03-section-modern-scientific-methods-in-historical-research-carbon-dating-dna-analysis-and-forensics.md"
    "00-02-04-section-fragility-of-historical-records-how-wars-weather-and-time-have-erased-much-of-the-past.md"
    "00-03-00-chapter-intro-how-time-and-history-are-measured.md"
    "00-03-01-section-bce-vs-ce-how-different-cultures-define-and-measure-historical-time.md"
    "00-03-02-section-different-calendars-throughout-history-the-julian-gregorian-islamic-and-chinese-calendars.md"
    "00-03-03-section-the-evolution-of-timekeeping-from-sundials-and-water-clocks-to-atomic-time.md"
    "00-03-04-section-misdated-events-and-the-fomenko-alternative-chronology-rewriting-history-with-radical-theories.md"
    "00-03-05-section-the-debate-over-the-dark-ages-and-missing-centuries-did-historical-forgeries-create-false-gaps-in-time.md"
    "00-04-00-chapter-intro-the-many-versions-of-history-around-the-world.md"
    "00-04-01-section-how-different-countries-teach-history-china-russia-the-us-and-other-nations-interpret-the-past-differently.md"
    "00-04-02-section-putins-russia-vs-western-historical-interpretations-rewriting-the-past-to-control-the-present.md"
    "00-04-03-section-how-world-war-ii-is-taught-differently-in-the-us-japan-germany-and-russia-national-memory-and-war-narratives.md"
    "00-04-04-section-historical-memory-and-the-israeli-palestinian-conflict-how-two-nations-remember-the-same-events-differently.md"
    "00-04-05-section-the-inevitability-of-bias-in-history-and-why-critical-thinking-is-essential-to-understanding-the-past.md"
    "01-00-00-unit-intro-the-dawn-of-humanity.md"
    "01-01-00-chapter-intro-the-origins-of-humans-and-the-pre-human-world.md"
    "01-01-01-section-the-formation-of-earth-and-the-world-before-humans.md"
    "01-01-02-section-the-rise-of-mammals-and-the-first-primates.md"
    "01-01-03-section-the-great-apes-and-the-human-ancestral-line.md"
    "01-01-04-section-the-evolution-of-humans-what-we-know-and-what-we-dont.md"
    "01-02-00-chapter-intro-human-evolution-and-the-first-hominins.md"
    "01-02-01-section-africa-as-the-birthplace-of-humans-the-evidence-and-controversies.md"
    "01-02-02-section-homo-erectus-and-the-first-migrations-out-of-africa.md"
    "01-02-03-section-who-were-the-neanderthals-and-why-did-they-go-extinct.md"
    "01-02-04-section-the-discovery-of-fire-and-how-it-transformed-humanity.md"
    "01-02-05-section-the-mystery-of-denisovans-an-unknown-human-cousin.md"
    "01-02-06-section-did-other-human-species-exist-that-we-havent-found-yet.md"
    "01-02-07-section-how-human-skin-color-evolved-and-adapted-to-climate.md"
    "01-03-00-chapter-intro-the-hunter-gatherers.md"
    "01-03-01-section-how-early-humans-lived-before-agriculture-nomadic-lifestyle-and-survival-strategies.md"
    "01-03-02-section-the-first-tools-and-the-technology-of-prehistoric-humans.md"
    "01-03-03-section-how-early-humans-hunted-and-gathered-food-strategies-and-adaptations.md"
    "01-03-04-section-the-ice-age-and-how-it-shaped-human-migration-and-settlement-patterns.md"
    "01-03-05-section-when-and-how-did-humans-first-arrive-in-the-americas-theories-and-debates.md"
    "01-03-06-section-the-first-artists-cave-paintings-symbols-and-music-as-early-culture.md"
    "01-03-07-section-the-first-burials-and-early-beliefs-about-death-afterlife-and-rituals.md"
    "01-04-00-chapter-intro-the-agricultural-revolution.md"
    "01-04-01-section-why-humans-started-farming-theories-and-evidence.md"
    "01-04-02-section-how-agriculture-led-to-permanent-settlements-and-social-complexity.md"
    "01-04-03-section-the-domestication-of-animals-and-the-birth-of-pastoralism.md"
    "01-04-04-section-early-farming-societies-around-the-world-different-paths-to-agriculture.md"
    "01-04-05-section-the-social-impact-of-agriculture-inequality-war-and-class-divisions.md"
    "01-04-06-section-the-invention-of-writing-and-early-record-keeping-in-agrarian-societies.md"
    "01-04-07-section-how-trade-and-early-money-systems-developed-in-farming-communities.md"
    "01-05-00-chapter-intro-early-religion-and-spirituality.md"
    "01-05-01-section-did-hunter-gatherers-have-gods-the-origins-of-religious-belief.md"
    "01-05-02-section-the-role-of-shamans-and-rituals-in-early-human-societies.md"
    "01-05-03-section-the-earliest-temples-and-sacred-sites-like-gobekli-tepe-and-their-meaning.md"
    "01-06-00-chapter-intro-the-role-of-women-in-early-societies.md"
    "01-06-01-section-was-prehistoric-society-matriarchal-or-patriarchal-why-we-dont-know.md"
    "01-06-02-section-womens-roles-in-agriculture-religion-and-early-economies.md"
    "01-06-03-section-how-gender-roles-changed-with-the-rise-of-agriculture-and-civilization.md"
    "01-07-00-chapter-intro-the-long-road-to-civilization.md"
    "01-07-01-section-how-some-societies-became-advanced-faster-than-others-geography-and-resources.md"
    "01-07-02-section-why-didnt-some-hunter-gatherers-adopt-agriculture-the-case-of-persistent-nomads.md"
    "01-07-03-section-how-climate-changes-shaped-early-human-migration-and-cultural-adaptation.md"
    "01-07-04-section-theories-about-lost-civilizations-before-ancient-history.md"
    "02-00-00-unit-intro-the-rise-of-civilizations.md"
    "02-01-00-chapter-intro-what-makes-a-civilization.md"
    "02-01-01-section-the-key-traits-of-a-civilization-government-trade-writing-and-religion.md"
    "02-01-02-section-the-bronze-age-and-the-emergence-of-early-states.md"
    "02-01-03-section-the-invention-of-writing-and-how-it-transformed-society.md"
    "02-01-04-section-the-first-trade-networks-and-the-rise-of-early-economies.md"
    "02-01-05-section-the-role-of-religion-and-mythology-in-early-civilizations.md"
    "02-02-00-chapter-intro-mesopotamian-civilization.md"
    "02-02-01-section-the-sumerians-and-the-first-cities-in-human-history.md"
    "02-02-02-section-cuneiform-the-first-writing-system-and-its-impact.md"
    "02-02-03-section-the-code-of-hammurabi-and-the-origins-of-law.md"
    "02-02-04-section-the-rise-and-fall-of-babylon-and-assyria.md"
    "02-02-05-section-ziggurats-mesopotamian-religion-and-their-view-of-the-gods.md"
    "02-02-06-section-the-importance-of-rivers-tigris-and-euphrates-in-mesopotamian-life.md"
    "02-02-07-section-early-warfare-and-conflicts-between-mesopotamian-city-states.md"
    "02-03-00-chapter-intro-ancient-egypt-and-nubia.md"
    "02-03-01-section-the-pharaohs-and-divine-rule-over-egyptian-society.md"
    "02-03-02-section-the-building-of-the-great-pyramids-and-monuments.md"
    "02-03-03-section-hieroglyphics-and-the-importance-of-writing-in-egypt.md"
    "02-03-04-section-the-role-of-the-nile-river-in-egyptian-society-and-economy.md"
    "02-03-05-section-religion-and-the-afterlife-mummies-and-elaborate-tombs.md"
    "02-03-06-section-the-old-middle-and-new-kingdoms-of-egypt-and-their-differences.md"
    "02-03-07-section-ancient-nubia-its-culture-trade-and-war-with-egypt.md"
    "02-04-00-chapter-intro-the-indus-valley-civilization.md"
    "02-04-01-section-the-mysterious-cities-of-harappa-and-mohenjo-daro.md"
    "02-04-02-section-early-drainage-systems-and-advanced-city-planning.md"
    "02-04-03-section-the-possible-writing-system-of-the-indus-valley-and-the-lost-script.md"
    "02-04-04-section-how-the-indus-valley-civilization-vanished-theories-and-evidence.md"
    "02-04-05-section-theories-on-the-indo-aryan-migration-and-its-impact-on-india.md"
    "02-05-00-chapter-intro-ancient-china-the-shang-and-zhou-dynasties.md"
    "02-05-01-section-the-oracle-bones-and-the-beginning-of-chinese-writing.md"
    "02-05-02-section-the-zhou-dynasty-and-the-mandate-of-heaven.md"
    "02-05-03-section-early-chinese-technologies-bronze-silk-and-irrigation.md"
    "02-05-04-section-the-warring-states-period-and-the-rise-of-the-qin-dynasty.md"
    "02-06-00-chapter-intro-the-early-jewish-people-and-their-place-in-the-ancient-world.md"
    "02-06-01-section-the-origins-of-the-hebrew-people-and-their-semitic-roots.md"
    "02-06-02-section-the-patriarchs-abraham-isaac-and-jacob.md"
    "02-06-03-section-their-relationship-with-egypt-assyria-and-babylon.md"
    "02-06-04-section-the-early-kingdoms-of-israel-and-judah.md"
    "02-06-05-section-the-babylonian-captivity-and-the-destruction-of-the-first-temple.md"
    "02-06-06-section-the-babylonian-exile-life-in-babylon-and-the-evolution-of-jewish-identity.md"
    "02-06-07-section-the-persian-conquest-of-babylon-and-the-return-to-jerusalem.md"
    "02-07-00-chapter-intro-early-civilizations-of-africa.md"
    "02-07-01-section-the-kingdom-of-kush-and-its-war-with-egypt.md"
    "02-07-02-section-the-nok-culture-and-the-earliest-use-of-iron-in-west-africa.md"
    "02-07-03-section-the-ancient-city-of-djenne-djenno-and-the-trans-saharan-trade.md"
    "02-07-04-section-the-garamantes-and-the-lost-civilization-of-the-sahara.md"
    "02-08-00-chapter-intro-early-civilizations-of-the-pacific.md"
    "02-08-01-section-the-first-humans-to-reach-australia-and-aboriginal-culture.md"
    "02-08-02-section-the-lapita-people-and-their-expansion-across-the-pacific.md"
    "02-08-03-section-navigation-and-early-boats-of-the-polynesians.md"
    "02-08-04-section-early-rituals-and-religious-practices-in-oceania.md"
    "02-09-00-chapter-intro-early-civilizations-of-the-americas.md"
    "02-09-01-section-the-caral-supe-and-norte-chico-civilizations.md"
    "02-09-02-section-the-chavin-culture-and-early-andean-societies.md"
    "02-09-03-section-the-olmecs-the-mother-culture-of-mesoamerica.md"
    "02-09-04-section-the-maya-emerge-the-first-city-states-in-central-america.md"
    "02-10-00-chapter-intro-early-civilizations-of-northern-europe.md"
    "02-10-01-section-the-peoples-of-prehistoric-europe-and-their-migrations.md"
    "02-10-02-section-cave-art-and-early-settlements-in-europe-altamira-lascaux.md"
    "02-10-03-section-megalithic-monuments-stonehenge-and-other-sites.md"
    "02-10-04-section-the-first-farmers-in-europe-and-the-spread-of-agriculture.md"
    "02-10-05-section-the-bronze-age-cultures-of-northern-and-central-europe.md"
    "02-10-06-section-the-proto-indo-european-migrations-and-their-legacy.md"
    "02-11-00-chapter-intro-the-bronze-age-collapse-and-the-dark-age.md"
    "02-11-01-section-the-mysterious-collapse-of-mediterranean-civilizations.md"
    "02-11-02-section-the-sea-peoples-and-the-end-of-the-bronze-age.md"
    "02-11-03-section-how-the-collapse-of-trade-set-humanity-back-centuries.md"
    "02-11-04-section-the-rise-of-the-iron-age-and-the-next-era-of-history.md"
    "03-00-00-unit-intro-the-classical-era.md"
    "03-01-00-chapter-intro-the-persian-empire.md"
    "03-01-01-section-cyrus-the-great-and-the-creation-of-persia.md"
    "03-01-02-section-darius-the-great-and-the-royal-road.md"
    "03-01-03-section-the-greco-persian-wars-and-the-decline-of-persia.md"
    "03-01-04-section-the-administration-and-multiculturalism-of-the-persian-empire.md"
    "03-01-05-section-zoroastrianism-and-its-lasting-influence.md"
    "03-02-00-chapter-intro-ancient-india-and-the-maurya-gupta-empires.md"
    "03-02-01-section-ashoka-the-great-and-the-spread-of-buddhism.md"
    "03-02-02-section-science-and-mathematics-in-ancient-india-zero-decimals-astronomy.md"
    "03-02-03-section-the-gupta-golden-age-art-literature-and-trade.md"
    "03-02-04-section-hinduism-and-its-influence-on-indian-statecraft.md"
    "03-02-05-section-the-role-of-buddhism-in-shaping-asian-politics.md"
    "03-03-00-chapter-intro-ancient-china-the-qin-and-han-dynasties.md"
    "03-03-01-section-the-warring-states-period-and-the-unification-of-china.md"
    "03-03-02-section-legalism-and-the-rule-of-the-qin-emperor-shi-huangdi.md"
    "03-03-03-section-the-great-wall-and-military-strategy-of-china.md"
    "03-03-04-section-the-han-dynasty-and-the-first-chinese-golden-age.md"
    "03-03-05-section-early-scientific-and-technological-advancements-in-china.md"
    "03-03-06-section-the-silk-road-and-chinas-early-global-trade-influence.md"
    "03-04-00-chapter-intro-the-jewish-people-in-the-classical-era.md"
    "03-04-01-section-the-hasmonean-kingdom-and-the-maccabean-revolt.md"
    "03-04-02-section-roman-conquest-of-judea-and-the-rise-of-herod.md"
    "03-04-03-section-the-jewish-roman-wars-and-the-destruction-of-the-second-temple.md"
    "03-04-04-section-the-diaspora-and-the-birth-of-rabbinic-judaism.md"
    "03-04-05-section-how-jews-maintained-their-identity-under-roman-rule.md"
    "03-05-00-chapter-intro-ancient-africa-and-the-rise-of-black-african-kingdoms.md"
    "03-05-01-section-carthage-the-naval-power-of-the-mediterranean.md"
    "03-05-02-section-the-garamantes-of-the-sahara-the-lost-civilization-of-the-desert.md"
    "03-05-03-section-the-kingdom-of-kush-and-its-war-with-egypt-and-rome.md"
    "03-05-04-section-the-nok-culture-and-the-earliest-use-of-iron-in-west-africa.md"
    "03-05-05-section-the-bantu-expansion-and-the-spread-of-languages-and-iron-working.md"
    "03-05-06-section-ancient-trade-networks-between-africa-and-the-wider-world.md"
    "03-06-00-chapter-intro-ancient-greece.md"
    "03-06-01-section-the-rise-of-the-polis-and-the-structure-of-greek-city-states.md"
    "03-06-02-section-athens-and-the-birth-of-democracy.md"
    "03-06-03-section-sparta-and-the-warrior-society.md"
    "03-06-04-section-the-persian-wars-and-the-rise-of-the-delian-league.md"
    "03-06-05-section-the-philosophers-socrates-plato-aristotle.md"
    "03-06-06-section-the-peloponnesian-war-and-the-decline-of-greek-power.md"
    "03-06-07-section-the-conquests-of-alexander-the-great.md"
    "03-06-08-section-the-hellenistic-world-and-the-blending-of-cultures.md"
    "03-07-00-chapter-intro-ancient-rome-from-republic-to-empire.md"
    "03-07-01-section-the-roman-republic-and-the-senate.md"
    "03-07-02-section-the-punic-wars-and-romans-vs-carthaginians.md"
    "03-07-03-section-julius-caesar-and-the-end-of-the-republic.md"
    "03-07-04-section-roman-law-and-its-influence-on-modern-legal-systems.md"
    "03-07-05-section-roman-architecture-and-engineering-aqueducts-colosseums-roads.md"
    "03-07-06-section-the-transition-from-republic-to-empire-augustus-and-the-pax-romana.md"
    "03-08-00-chapter-intro-the-roman-empire.md"
    "03-08-01-section-how-rome-became-an-empire-and-the-age-of-the-caesars.md"
    "03-08-02-section-daily-life-in-the-roman-empire-society-and-class-structure.md"
    "03-08-03-section-the-silk-road-and-trade-between-rome-and-asia.md"
    "03-08-04-section-the-rise-of-christianity-and-persecutions.md"
    "03-08-05-section-the-council-of-nicea-and-the-officialization-of-christianity.md"
    "03-08-06-section-the-decline-of-the-roman-empire-economic-and-military-collapse.md"
    "03-08-07-section-the-fall-of-rome-and-the-lasting-legacy-of-the-roman-world.md"
    "03-09-00-chapter-intro-the-americas-in-the-classical-era.md"
    "03-09-01-section-the-rise-of-the-maya-and-their-city-states.md"
    "03-09-02-section-the-olmecs-the-mother-culture-of-mesoamerica.md"
    "03-09-03-section-the-nazca-civilization-and-their-mysterious-lines.md"
    "03-09-04-section-the-moche-culture-and-their-irrigation-systems.md"
    "03-09-05-section-the-andean-civilizations-and-their-complex-societies.md"
    "03-10-00-chapter-intro-the-rise-of-powerful-migrations-and-barbarian-tribes.md"
    "03-10-01-section-the-huns-and-the-collapse-of-the-western-roman-empire.md"
    "03-10-02-section-how-the-hun-invasions-triggered-the-great-migrations.md"
    "03-10-03-section-the-germanic-tribes-and-their-role-in-reshaping-europe.md"
    "03-10-04-section-the-rise-of-the-sassanid-empire-and-the-war-with-rome.md"
    "03-11-00-chapter-intro-southeast-asia-in-the-classical-world.md"
    "03-11-01-section-the-rise-of-the-funan-and-champa-kingdoms.md"
    "03-11-02-section-the-influence-of-indian-trade-and-hinduism-in-sea.md"
    "03-11-03-section-early-buddhist-monarchies-and-temple-construction.md"
    "03-11-04-section-the-roots-of-khmer-civilization-and-the-beginnings-of-angkor.md"
    "03-11-05-section-the-maritime-trading-empires-and-their-role-in-asian-commerce.md"
    "03-12-00-chapter-intro-asian-philosophy-and-religion.md"
    "03-12-01-section-hinduism-and-its-influence-on-indian-empires.md"
    "03-12-02-section-buddhism-and-its-expansion-across-asia.md"
    "03-12-03-section-confucianism-and-the-foundation-of-chinese-statecraft.md"
    "03-12-04-section-taoism-and-the-way-of-nature.md"
    "03-12-05-section-shintoism-and-the-spiritual-roots-of-japan.md"
    "03-13-00-chapter-intro-the-classical-foundations-of-korea-and-japan.md"
    "03-13-01-section-the-mythic-origins-of-korea-and-the-first-kingdoms.md"
    "03-13-02-section-the-early-history-of-japan-and-the-yayoi-kofun-periods.md"
    "03-13-03-section-the-hairy-ainu-and-their-place-in-early-japan.md"
    "03-13-04-section-how-korea-and-japan-absorbed-chinese-influences.md"
    "03-13-05-section-shamanism-ancestor-worship-and-early-korean-and-japanese-religion.md"
    "03-14-00-chapter-intro-the-classical-era-ends-and-the-world-transforms.md"
    "03-14-01-section-the-rise-of-the-byzantine-empire-and-the-continuation-of-rome.md"
    "03-14-02-section-the-fragmentation-of-western-europe-and-the-rise-of-germanic-kingdoms.md"
    "03-14-03-section-the-fall-of-the-sassanid-empire-and-the-changing-map-of-persia.md"
    "03-14-04-section-the-post-gupta-period-and-the-fragmentation-of-india.md"
    "03-14-05-section-china-after-the-han-the-three-kingdoms-and-sui-reunification.md"
    "03-14-06-section-how-the-korean-three-kingdoms-and-japan-began-unifying.md"
    "03-14-07-section-the-jewish-diaspora-in-the-post-roman-world.md"
    "03-14-08-section-pre-islamic-arabia-and-the-spread-of-monotheism.md"
    "03-14-09-section-african-transitions-the-decline-of-carthage-and-rise-of-new-kingdoms.md"
    "03-14-10-section-mesoamerica-and-the-mayan-classic-period-expansion.md"
    "03-14-11-section-the-andes-after-the-moche-new-kingdoms-in-south-america.md"
    "03-14-12-section-how-the-classical-world-shaped-the-medieval-and-modern-world.md"
    "04-00-00-unit-intro-the-post-classical-world-and-the-forging-of-new-civilizations.md"
    "04-01-00-chapter-intro-the-byzantine-empire-and-eastern-christendom.md"
    "04-01-01-section-the-legacy-of-rome-and-the-birth-of-byzantium.md"
    "04-01-02-section-constantinople-the-city-between-worlds.md"
    "04-01-03-section-justinian-the-great-and-the-hagia-sophia.md"
    "04-01-04-section-the-orthodox-church-and-the-schism-with-rome.md"
    "04-01-05-section-the-fall-of-byzantium-and-the-rise-of-the-ottomans.md"
    "04-02-00-chapter-intro-the-rise-of-islam-and-the-caliphates.md"
    "04-02-01-section-muhammad-and-the-birth-of-islam.md"
    "04-02-02-section-the-rashidun-caliphate-and-early-muslim-expansion.md"
    "04-02-03-section-the-umayyads-and-the-spread-of-islam-to-spain-and-central-asia.md"
    "04-02-04-section-the-abbasids-and-the-flowering-of-islamic-culture.md"
    "04-02-05-section-islamic-science-medicine-and-architecture-in-the-golden-age.md"
    "04-02-06-section-trade-networks-and-the-importance-of-the-islamic-world.md"
    "04-03-00-chapter-intro-the-franks-the-holy-roman-empire-and-the-birth-of-france.md"
    "04-03-01-section-the-merovingians-and-the-rise-of-francia.md"
    "04-03-02-section-charlemagne-and-the-carolingian-renaissance.md"
    "04-03-03-section-the-holy-roman-empire-formation-and-legacy.md"
    "04-03-04-section-feudalism-and-the-structure-of-medieval-society.md"
    "04-03-05-section-medieval-technology-agriculture-castles-and-cities.md"
    "04-03-06-section-the-growth-of-languages-and-the-birth-of-national-identities.md"
    "04-04-00-chapter-intro-the-vikings-raiders-traders-and-nation-builders.md"
    "04-04-01-section-the-origins-of-the-vikings-and-their-seafaring-skills.md"
    "04-04-02-section-viking-raids-and-settlements-in-europe.md"
    "04-04-03-section-the-danelaw-and-the-viking-legacy-in-england.md"
    "04-04-04-section-vinland-and-the-viking-exploration-of-north-america.md"
    "04-04-05-section-how-the-vikings-became-kings-and-christianized.md"
    "04-05-00-chapter-intro-england-the-formation-of-a-nation.md"
    "04-05-01-section-the-anglo-saxon-kingdoms-and-their-struggles.md"
    "04-05-02-section-the-norman-conquest-of-england-and-william-the-conqueror.md"
    "04-05-03-section-the-plantagenets-and-the-growth-of-the-english-monarchy.md"
    "04-05-04-section-the-magna-carta-and-the-origins-of-limited-government.md"
    "04-05-05-section-the-hundred-years-war-and-the-rise-of-english-identity.md"
    "04-06-00-chapter-intro-the-catholic-church-power-politics-and-control-in-medieval-europe.md"
    "04-06-01-section-the-rise-of-the-papacy-and-the-churchs-political-power.md"
    "04-06-02-section-monasticism-and-the-preservation-of-knowledge.md"
    "04-06-03-section-the-inquisition-and-the-purge-of-heresy.md"
    "04-06-04-section-the-great-schism-between-rome-and-constantinople.md"
    "04-06-05-section-how-the-church-shaped-medieval-society.md"
    "04-07-00-chapter-intro-the-magyars-and-their-uncertain-origins-steppe-warriors-to-kingdom.md"
    "04-07-01-section-the-steppe-origins-of-the-magyars.md"
    "04-07-02-section-the-conquest-of-the-carpathian-basin.md"
    "04-07-03-section-the-magyar-hun-controversy-and-their-place-in-history.md"
    "04-07-04-section-the-christianization-of-hungary-and-the-rule-of-st-stephen.md"
    "04-08-00-chapter-intro-the-slavic-world-the-rise-of-kievan-rus-and-the-eastern-realms.md"
    "04-08-01-section-the-origins-of-the-slavs-and-their-expansion.md"
    "04-08-02-section-kievan-rus-and-the-adoption-of-orthodox-christianity.md"
    "04-08-03-section-the-rise-of-moscow-and-the-beginning-of-russian-statehood.md"
    "04-08-04-section-poland-lithuania-and-the-rise-of-the-commonwealth.md"
    "04-08-05-section-the-balkans-and-the-mix-of-cultures.md"
    "04-09-00-chapter-intro-the-mongol-empire-and-its-impact-on-the-world.md"
    "04-09-01-section-genghis-khan-and-the-unification-of-the-mongols.md"
    "04-09-02-section-the-conquest-of-china-and-the-yuan-dynasty.md"
    "04-09-03-section-the-mongols-in-persia-and-the-destruction-of-baghdad.md"
    "04-09-04-section-the-golden-horde-and-the-mongol-rule-of-russia.md"
    "04-09-05-section-the-silk-road-and-the-pax-mongolica.md"
    "04-09-06-section-the-decline-of-the-mongol-empire-and-its-fracturing.md"
    "04-10-00-chapter-intro-the-balkans-between-empires-war-and-culture.md"
    "04-10-01-section-the-byzantine-balkan-frontier.md"
    "04-10-02-section-the-rise-of-serbia-and-the-nemanjic-dynasty.md"
    "04-10-03-section-the-bogomils-and-the-religious-divide-in-the-balkans.md"
    "04-10-04-section-the-ottoman-invasions-and-the-battle-of-kosovo.md"
    "04-11-00-chapter-intro-the-rise-of-the-ottomans-and-the-end-of-byzantium.md"
    "04-11-01-section-the-osmanli-tribe-and-the-rise-of-the-ottoman-state.md"
    "04-11-02-section-the-conquest-of-constantinople.md"
    "04-11-03-section-the-ottoman-military-system-and-the-janissaries.md"
    "04-11-04-section-the-role-of-islam-in-the-ottoman-empire.md"
    "04-12-00-chapter-intro-jewish-history-in-the-medieval-world-diaspora-expulsions-and-resilience.md"
    "04-12-01-section-the-diaspora-and-the-spread-of-jewish-communities.md"
    "04-12-02-section-jewish-life-in-christian-and-muslim-lands.md"
    "04-12-03-section-the-rise-of-antisemitism-and-expulsions.md"
    "04-12-04-section-the-khazars-and-their-controversial-conversion.md"
    "04-13-00-chapter-intro-the-crusades-religion-war-and-the-clash-of-civilizations.md"
    "04-13-01-section-the-causes-of-the-crusades-and-the-call-of-pope-urban-ii.md"
    "04-13-02-section-the-first-crusade-and-the-conquest-of-jerusalem.md"
    "04-13-03-section-the-rise-of-saladin-and-the-muslim-counteroffensive.md"
    "04-14-00-chapter-intro-spain-the-reconquista-and-the-forging-of-identity.md"
    "04-14-01-section-muslim-rule-in-al-andalus.md"
    "04-14-02-section-the-christian-reconquest-of-spain.md"
    "04-14-03-section-the-expulsion-of-the-jews-and-muslims.md"
    "04-15-00-chapter-intro-the-african-kingdoms-and-trade-networks.md"
    "04-15-01-section-the-rise-of-ghana-and-the-gold-salt-trade.md"
    "04-15-02-section-mali-and-the-legendary-mansa-musa.md"
    "04-15-03-section-the-swainili-coast-and-the-indian-ocean-trade.md"
    "04-15-04-section-ethiopia-and-the-legacy-of-axum.md"
    "04-15-05-section-great-zimbabwe-and-the-mysteries-of-southern-africa.md"
    "04-15-06-section-the-bantu-expansion-and-the-spread-of-language-and-iron.md"
    "04-16-01-section-the-chola-dynasty-and-the-maritime-trade-empire.md"
    "04-16-02-section-the-delhi-sultanate-and-the-turco-muslim-conquest-of-india.md"
    "04-16-03-section-hinduism-buddhism-and-the-spread-of-islam-in-india.md"
    "04-16-04-section-art-science-and-mathematics-in-medieval-india.md"
    "04-17-01-section-the-tang-dynasty-and-the-expansion-of-chinese-influence.md"
    "04-17-02-section-the-silk-road-and-chinas-connection-to-the-world.md"
    "04-17-03-section-the-song-dynasty-and-the-rise-of-neo-confucianism.md"
    "04-17-04-section-chinese-inventions-paper-gunpowder-printing-and-compass.md"
    "04-17-05-section-the-mongol-conquest-of-china-and-the-yuan-dynasty.md"
    "04-18-01-section-the-heian-period-and-the-birth-of-japanese-culture.md"
    "04-18-02-section-the-rise-of-the-samurai-and-the-feudal-warrior-class.md"
    "04-18-03-section-the-mongol-invasions-and-the-kamikaze-typhoons.md"
    "04-18-04-section-korean-kingdoms-and-the-rise-of-joseon-dynasty.md"
    "04-18-05-section-the-cultural-exchanges-between-china-korea-and-japan.md"
    "04-19-01-section-the-maya-and-their-advanced-astronomy-and-writing.md"
    "04-19-02-section-the-aztec-empire-and-their-complex-society.md"
    "04-19-03-section-the-inca-empire-and-their-mountain-kingdom.md"
    "04-19-04-section-trade-networks-and-cultural-exchange-in-the-americas.md"
    "04-20-01-section-the-origin-and-spread-of-the-black-death.md"
    "04-20-02-section-the-economic-and-social-collapse-in-europe.md"
    "04-20-03-section-the-mongol-collapse-and-the-end-of-the-pax-mongolica.md"
    "04-20-04-section-the-rise-of-the-ottoman-empire.md"
    "04-21-01-section-the-ming-dynasty-and-the-restoration-of-chinese-power.md"
    "04-21-02-section-the-renaissance-and-the-rebirth-of-europe.md"
    "04-21-03-section-the-rise-of-seafaring-kingdoms-portugal-and-spain.md"
    "04-21-04-section-how-the-post-classical-world-set-the-stage-for-modern-history.md"
    "05-00-00-unit-intro-the-early-modern-world-1400-1600.md"
    "05-01-00-chapter-intro-the-renaissance-and-the-revival-of-knowledge.md"
    "05-01-01-section-the-humanist-movement-and-the-return-to-classical-ideas.md"
    "05-01-02-section-the-rise-of-printing-and-the-spread-of-knowledge.md"
    "05-01-03-section-renaissance-art-and-the-genius-of-leonardo-and-michelangelo.md"
    "05-01-04-section-science-before-the-scientific-revolution-medicine-astronomy-and-alchemy.md"
    "05-01-05-section-the-rise-of-vernacular-literature-and-the-reformation-of-learning.md"
    "05-02-00-chapter-intro-the-rise-of-monarchies-and-state-power.md"
    "05-02-01-section-the-fragmentation-of-feudalism-and-the-rise-of-absolute-kings.md"
    "05-02-02-section-the-french-monarchy-from-the-hundred-years-war-to-francis-i.md"
    "05-02-03-section-the-habsburgs-their-vast-empire-and-their-rivalry-with-france.md"
    "05-02-04-section-the-rise-of-england-the-tudor-dynasty-and-the-break-with-rome.md"
    "05-02-05-section-the-early-russian-tsars-and-the-rise-of-moscow.md"
    "05-03-00-chapter-intro-the-ottoman-empire-and-its-expansion.md"
    "05-03-01-section-the-conquest-of-constantinople-and-the-end-of-byzantium.md"
    "05-03-02-section-the-janissaries-and-the-ottoman-military-system.md"
    "05-03-03-section-suleiman-the-magnificent-and-the-height-of-ottoman-power.md"
    "05-03-04-section-the-ottoman-administration-tolerance-and-law.md"
    "05-03-05-section-the-ottoman-habsburg-rivalry-and-the-wars-in-europe.md"
    "05-04-00-chapter-intro-the-age-of-exploration-and-its-consequences.md"
    "05-04-01-section-the-search-for-new-trade-routes-and-the-expansion-of-maritime-technology.md"
    "05-04-02-section-portugal-spain-and-the-opening-of-the-atlantic-world.md"
    "05-04-03-section-the-columbian-exchange-how-food-disease-and-people-circulated.md"
    "05-04-04-section-the-conquests-of-the-aztecs-and-incas-and-the-birth-of-spanish-america.md"
    "05-04-05-section-the-emergence-of-the-transatlantic-slave-trade.md"
    "05-04-06-section-the-race-for-colonies-the-dutch-english-and-french-arrivals.md"
    "05-05-00-chapter-intro-the-americas-before-and-after-contact.md"
    "05-05-01-section-the-great-civilizations-of-the-maya-aztecs-and-incas.md"
    "05-05-02-section-native-north-american-societies-and-their-diverse-cultures.md"
    "05-05-03-section-how-smallpox-and-european-diseases-reshaped-the-new-world.md"
    "05-05-04-section-spanish-rule-in-the-americas-the-encomienda-system-and-missionary-efforts.md"
    "05-05-05-section-african-slavery-in-the-americas-and-the-forging-of-new-identities.md"
    "05-06-00-chapter-intro-the-african-kingdoms-and-the-slave-trade.md"
    "05-06-01-section-the-gold-coast-and-the-rise-of-ghana-mali-and-songhai.md"
    "05-06-02-section-the-kingdom-of-kongo-and-the-impact-of-portuguese-trade.md"
    "05-06-03-section-the-trans-saharan-trade-and-the-spread-of-islam-in-africa.md"
    "05-06-04-section-the-slave-trade-how-europeans-and-africans-shaped-the-trade.md"
    "05-06-05-section-the-swahili-coast-and-the-indian-ocean-trade-networks.md"
    "05-07-00-chapter-intro-the-ming-dynasty-and-the-power-of-china.md"
    "05-07-01-section-the-ming-revival-after-mongol-rule-and-the-restoration-of-chinese-tradition.md"
    "05-07-02-section-zheng-he-and-chinese-maritime-exploration.md"
    "05-07-03-section-the-great-wall-and-the-defense-against-northern-invasions.md"
    "05-07-04-section-the-decline-of-the-ming-and-the-rise-of-the-manchus.md"
    "05-08-00-chapter-intro-japan-and-the-warring-states-era.md"
    "05-08-01-section-the-sengoku-period-and-the-collapse-of-central-authority.md"
    "05-08-02-section-oda-nobunaga-toyotomi-hideyoshi-and-the-road-to-unification.md"
    "05-08-03-section-the-rise-of-the-tokugawa-shogunate-and-the-sealing-of-japan.md"
    "05-08-04-section-the-korean-imjin-war-and-the-ming-japanese-conflict.md"
    "05-09-00-chapter-intro-the-mughal-empire-and-the-wealth-of-india.md"
    "05-09-01-section-the-foundation-of-the-mughal-dynasty-by-babur.md"
    "05-09-02-section-akbar-the-great-and-the-blending-of-cultures.md"
    "05-09-03-section-the-golden-age-of-the-mughals-shah-jahan-and-the-taj-mahal.md"
    "05-09-04-section-the-rise-of-maratha-resistance-and-the-decline-of-the-mughals.md"
    "05-10-00-chapter-intro-the-protestant-reformation-and-religious-wars.md"
    "05-10-01-section-martin-luther-and-the-challenge-to-the-catholic-church.md"
    "05-10-02-section-the-rise-of-calvinism-and-the-variations-of-protestantism.md"
    "05-10-03-section-the-council-of-trent-and-the-catholic-counter-reformation.md"
    "05-10-04-section-the-french-wars-of-religion-and-the-struggles-for-tolerance.md"
    "05-10-05-section-the-dutch-revolt-and-the-creation-of-the-netherlands.md"
    "05-11-00-chapter-intro-the-thirty-years-war-and-the-end-of-the-reformation-era.md"
    "05-11-01-section-the-bohemian-revolt-and-the-beginning-of-conflict.md"
    "05-11-02-section-the-swedish-phase-gustavus-adolphus-and-the-turning-tide.md"
    "05-11-03-section-the-french-involvement-and-the-rise-of-cardinal-richelieu.md"
    "05-11-04-section-the-peace-of-westphalia-and-the-new-political-order-in-europe.md"
    "05-12-00-chapter-intro-the-scientific-revolution-and-the-new-way-of-thinking.md"
    "05-12-01-section-copernicus-galileo-and-the-revolution-in-astronomy.md"
    "05-12-02-section-kepler-and-newton-the-mathematization-of-science.md"
    "05-12-03-section-medical-advancements-and-the-changing-view-of-the-human-body.md"
    "05-12-04-section-the-birth-of-the-scientific-method-and-the-legacy-of-the-revolution.md"
    "05-12-05-section-how-the-early-modern-world-set-the-stage-for-the-modern-age.md"
    "06-00-00-unit-intro-the-foundations-of-the-modern-world.md"
    "06-01-00-chapter-intro-the-age-of-absolutism-monarchs-and-the-centralization-of-power.md"
    "06-01-01-section-louis-xiv-and-the-absolute-state-in-france.md"
    "06-01-02-section-the-habsburgs-and-their-fragmented-empire.md"
    "06-01-03-section-prussia-and-the-rise-of-the-military-state.md"
    "06-01-04-section-russia-the-romanovs-and-peter-the-great.md"
    "06-01-05-section-britain-the-english-civil-war-and-the-glorious-revolution.md"
    "06-01-06-section-the-decline-of-spain-and-portugal.md"
    "06-02-00-chapter-intro-the-expansion-of-global-empires-and-trade-networks.md"
    "06-02-01-section-the-dutch-golden-age-commerce-science-and-art.md"
    "06-02-02-section-the-british-and-french-colonial-rivalry-in-the-americas.md"
    "06-02-03-section-the-transatlantic-slave-trade-and-its-global-consequences.md"
    "06-02-04-section-the-spanish-empire-in-the-americas-the-silver-economy.md"
    "06-02-05-section-the-portuguese-trade-empire-in-africa-and-asia.md"
    "06-02-06-section-the-impact-of-european-contact-on-indigenous-peoples.md"
    "06-03-00-chapter-intro-the-ottoman-safavid-and-mughal-empires-in-the-17th-century.md"
    "06-03-01-section-the-peak-and-decline-of-the-ottoman-empire.md"
    "06-03-02-section-the-safavid-empire-in-persia-and-its-shia-legacy.md"
    "06-03-03-section-the-mughal-empire-under-aurangzeb-and-its-fracturing.md"
    "06-03-04-section-the-economic-and-military-competition-between-islamic-empires.md"
    "06-04-00-chapter-intro-the-rise-of-china-and-the-qing-dynasty.md"
    "06-04-01-section-the-fall-of-the-ming-and-the-rise-of-the-qing.md"
    "06-04-02-section-kangxi-and-qianlong-expansion-and-administration.md"
    "06-04-03-section-chinese-society-culture-and-technological-stagnation.md"
    "06-04-04-section-china-and-european-mercantilism-the-canton-system.md"
    "06-05-00-chapter-intro-japan-the-tokugawa-shogunate-and-the-closed-country-policy.md"
    "06-05-01-section-the-battle-of-sekigahara-and-the-establishment-of-tokugawa-rule.md"
    "06-05-02-section-the-edo-period-culture-samurai-and-economic growth.md"
    "06-05-03-section-japans-isolation-policy-and-contact-with-the-west.md"
    "06-06-00-chapter-intro-the-scientific-revolution-and-the-transformation-of-thought.md"
    "06-06-01-section-galileo-newton-and-the-laws-of-nature.md"
    "06-06-02-section-the-development-of-modern-medicine-and-anatomy.md"
    "06-06-03-section-the-rise-of-experimental-science-and-the-scientific-method.md"
    "06-06-04-section-the-conflict-between-science-and-religion.md"
    "06-07-00-chapter-intro-the-enlightenment-the-age-of-reason.md"
    "06-07-01-section-the-philosophers-locke-rousseau-voltaire-and-montesquieu.md"
    "06-07-02-section-the-enlightenment-and-political-thought-redefining-governance.md"
    "06-07-03-section-the-rise-of-secularism-and-the-challenges-to-traditional-authority.md"
    "06-07-04-section-the-impact-of-enlightenment-ideas-on-the-modern-world.md"
    "06-08-00-chapter-intro-the-crisis-of-the-old-order-and-the-roots-of-revolution.md"
    "06-08-01-section-economic-hardship-social-unrest-and-the-seeds-of-revolution.md"
    "06-08-02-section-the-american-revolutionary-thought-before-1776.md"
    "06-08-03-section-the-growing-contradictions-in-monarchical-rule-and-the-call-for-change.md"
    "06-09-00-chapter-intro-the-world-in-1750-and-the-end-of-the-old-regime.md"
    "06-09-01-section-the-global-balance-of-power-and-the-struggles-for-hegemony.md"
    "06-09-02-section-the-seven-years-war-and-its-worldwide-impact.md"
    "06-09-03-section-the-shift-toward-modern-statecraft-and-economic change.md"
    "06-09-04-section-the-prelude-to-the-revolutions-of-the-late-18th-century.md"

    "07-00-00-unit-intro-revolutions-industry-and-empire-1750-1850.md"
    "07-01-00-chapter-intro-the-american-revolution-and-the-birth-of-a-nation.md"
    "07-01-01-section-the-enlightenment-and-the-ideas-that-sparked-revolution.md"
    "07-01-02-section-the-thirteen-colonies-before-the-revolution.md"
    "07-01-03-section-the-causes-of-the-american-revolution-taxes-and-resistance.md"
    "07-01-04-section-the-war-for-independence-major-battles-and-strategy.md"
    "07-01-05-section-the-declaration-of-independence-and-its-impact.md"
    "07-01-06-section-the-constitution-and-the-creation-of-a-new-government.md"
    "07-01-07-section-the-american-revolution-in-global-context-britain-france-and-the-world.md"
    "07-02-00-chapter-intro-the-french-revolution-and-the-rise-of-napoleon.md"
    "07-02-01-section-france-before-the-revolution-the-ancien-regime.md"
    "07-02-02-section-the-storming-of-the-bastille-and-the-end-of-monarchy.md"
    "07-02-03-section-the-reign-of-terror-and-the-rise-of-radical-revolution.md"
    "07-02-04-section-napoleon-bonaparte-from-general-to-emperor.md"
    "07-02-05-section-the-napoleonic-wars-and-the-conquest-of-europe.md"
    "07-02-06-section-the-fall-of-napoleon-and-the-congress-of-vienna.md"

    "07-03-00-chapter-intro-the-haitian-revolution-and-the-fall-of-slavery-in-the-caribbean.md"
    "07-03-01-section-the-slave-economy-of-the-caribbean-and-the-french-colonies.md"
    "07-03-02-section-toussaint-louverture-and-the-revolt-against-france.md"
    "07-03-03-section-how-haiti-defeated-napoleon-and-became-the-first-black-republic.md"
    "07-03-04-section-the-impact-of-the-haitian-revolution-on-the-world.md"

    "07-04-00-chapter-intro-the-independence-movements-of-spanish-america.md"
    "07-04-01-section-the-creoles-and-the-rise-of-revolutionary-ideas-in-latin-america.md"
    "07-04-02-section-simon-bolivar-and-the-wars-of-liberation.md"
    "07-04-03-section-the-mexican-war-for-independence.md"
    "07-04-04-section-the-brazilian-independence-unique-path-to-freedom.md"
    "07-04-05-section-the-monroe-doctrine-and-u-s-policy-toward-latin-america.md"
    "07-04-06-section-the-lasting-impact-of-latin-american-independence.md"

    "07-05-00-chapter-intro-the-industrial-revolution-and-the-changing-world.md"
    "07-05-01-section-the-roots-of-industrialization-and-the-rise-of-machines.md"
    "07-05-02-section-the-textile-industry-and-the-factory-system.md"
    "07-05-03-section-steam-engines-railroads-and-the-revolution-in-transportation.md"
    "07-05-04-section-urbanization-and-the-changing-life-of-workers.md"
    "07-05-05-section-child-labor-and-the-dark-side-of-industrialization.md"
    "07-05-05-section-industrialization-opportunity-or-exploitation-the-debate-over-progress.md"
    "07-05-06-section-the-spread-of-industrialization-beyond-britain.md"

    "07-06-00-chapter-intro-the-british-empire-expands-and-the-colonial-age-strengthens.md"
    "07-06-01-section-the-british-raj-the-expansion-of-colonial-rule-in-india.md"
    "07-06-02-section-the-boer-war-and-britain-in-southern-africa.md"
    "07-06-03-section-australia-and-new-zealand-colonies-at-the-edge-of-the-world.md"
    "07-06-04-section-the-role-of-british-trade-and-the-growing-power-of-the-navy.md"

    "07-07-00-chapter-intro-africa-and-the-middle-east-in-an-age-of-change.md"
    "07-07-01-section-the-decline-of-the-ottoman-empire-and-the-rise-of-muhammad-ali.md"
    "07-07-02-section-west-african-kingdoms-and-the-growing-european-presence.md"
    "07-07-03-section-the-end-of-the-transatlantic-slave-trade-and-its-aftermath.md"
    "07-07-04-section-shaka-zulu-and-the-rise-of-the-zulu-kingdom.md"

    "07-08-00-chapter-intro-china-and-the-fall-of-the-qing-golden-age.md"
    "07-08-01-section-the-qing-dynasty-at-its-height-expansion-and-prosperity.md"
    "07-08-02-section-corruption-and-internal-weakness-in-the-late-qing.md"
    "07-08-03-section-the-white-lotus-rebellion-and-the-first-major-anti-qing-uprising.md"
    "07-08-04-section-the-first-opium-war-and-the-treaty-of-nanjing.md"
    "07-08-05-section-the-opening-of-china-treaty-ports-and-western-influence.md"

    "07-09-00-chapter-intro-japan-and-the-isolation-of-the-tokugawa-shogunate.md"
    "07-09-01-section-the-sakoku-policy-and-japans-closure-to-the-world.md"
    "07-09-02-section-the-samurai-class-and-the-rigid-feudal-hierarchy.md"
    "07-09-03-section-american-gunboats-and-the-forced-opening-of-japan.md"

    "07-10-00-chapter-intro-the-political-and-social-revolutions-of-europe.md"
    "07-10-01-section-the-1848-revolutions-and-the-rise-of-nationalism.md"
    "07-10-02-section-the-rise-of-socialism-and-the-ideas-of-karl-marx.md"
    "07-10-03-section-the-abolition-of-serfdom-and-the-changing-landscape-of-europe.md"
    "07-10-04-section-romanticism-art-literature-and-the-spirit-of-nationalism.md"

    "07-11-00-chapter-intro-the-united-states-expands-and-moves-toward-civil-war.md"
    "07-11-01-section-the-louisiana-purchase-and-westward-expansion.md"
    "07-11-02-section-the-war-of-1812-and-its-consequences.md"
    "07-11-03-section-the-indian-removal-act-and-the-trail-of-tears.md"
    "07-11-04-section-the-cherokee-nation-and-native-american-resistance.md"
    "07-11-05-section-the-republic-of-texas.md"
    "07-11-05-section-the-mexican-american-war-and-the-new-territories.md"
    "07-11-06-section-california-and-the-gold-rush.md"
    "07-11-07-section-the-growing-divide-over-slavery.md"
    "07-11-08-section-the-road-to-civil-war.md"

    "07-12-00-chapter-intro-the-end-of-an-era-and-the-world-on-the-brink-of-change.md"
    "07-12-01-section-the-shift-in-global-power-structures.md"
    "07-12-02-section-the-early-movements-for-womens-rights-and-social-reform.md"
    "07-12-03-section-the-world-in-1850-and-the-stage-set-for-modern-history.md"

    "08-00-00-unit-intro-the-age-of-empire-industry-and-ideology-1850-1914.md"

    "08-01-00-chapter-intro-the-second-industrial-revolution-and-the-new-age-of-technology.md"
    "08-01-01-section-the-shift-to-steel-electricity-and-mass-production.md"
    "08-01-02-section-the-rise-of-railroads-telegraphs-and-global-communication.md"
    "08-01-03-section-the-oil-and-chemical-industries-and-the-modern-corporation.md"
    "08-01-04-section-the-rise-of-consumerism-and-the-birth-of-modern-advertising.md"
    "08-01-05-section-urbanization-and-the-rise-of-megacities.md"
    "08-01-06-section-the-changing-nature-of-work-and-the-factory-system.md"

    "08-02-00-chapter-intro-the-american-civil-war-reconstruction-and-the-rise-of-the-us.md"
    "08-02-01-section-the-divide-between-north-and-south-slavery-economics-and-politics.md"
    "08-02-02-section-the-secession-crisis-and-the-outbreak-of-the-civil-war.md"
    "08-02-03-section-the-military-campaigns-and-strategy-of-the-civil-war.md"
    "08-02-04-section-the-emancipation-proclamation-and-the-end-of-slavery.md"
    "08-02-05-section-reconstruction-and-the-struggles-for-racial-equality.md"
    "08-02-06-section-the-rise-of-industrial-america-and-the-gilded-age.md"
    "08-02-07-section-the-westward-expansion-and-the-end-of-the-frontier.md"

    "08-03-00-chapter-intro-the-unification-of-nations-germany-italy-and-the-rise-of-nationalism.md"
    "08-03-01-section-the-italian-unification-mazzini-cavour-and-garibaldi.md"
    "08-03-02-section-otto-von-bismarck-and-the-unification-of-germany.md"
    "08-03-03-section-the-franco-prussian-war-and-the-fall-of-the-second-french-empire.md"
    "08-03-04-section-the-rise-of-nationalism-and-its-impact-on-european-stability.md"
    "08-03-05-section-the-dual-monarchy-of-austria-hungary-and-its-fragile-union.md"

    "08-04-00-chapter-intro-the-native-american-struggles-resistance-and-loss-of-sovereignty.md"
    "08-04-01-section-the-continued-westward-expansion-and-the-displacement-of-native-peoples.md"
    "08-04-02-section-the-indian-wars-the-plains-conflicts-and-the-fall-of-the-sioux.md"
    "08-04-03-section-the-ghost-dance-movement-and-the-wounded-knee-massacre.md"
    "08-04-04-section-the-dawes-act-and-the-forced-assimilation-of-native-americans.md"
    "08-04-05-section-the-loss-of-indigenous-land-and-the-reservations-system.md"

    "08-05-00-chapter-intro-the-scramble-for-africa-and-the-new-colonial-order.md"
    "08-05-01-section-the-berlin-conference-and-the-partitioning-of-africa.md"
    "08-05-02-section-british-colonialism-in-egypt-sudan-and-south-africa.md"
    "08-05-03-section-the-congo-free-state-and-the-horrors-of-leopold-ii.md"
    "08-05-04-section-french-algeria-and-the-maghreb.md"
    "08-05-05-section-resistance-to-colonialism-the-ashanti-madagascar-and-the-mahdist-revolt.md"
    "08-05-06-section-the-boer-wars-and-the-end-of-independent-afrikaans-rule.md"
    "08-05-07-section-the-economic-exploitation-of-africa-mines-rubber-and-railroads.md"

    "08-06-00-chapter-intro-the-meiji-restoration-and-the-rise-of-modern-japan.md"
    "08-06-01-section-the-fall-of-the-tokugawa-shogunate-and-the-opening-of-japan.md"
    "08-06-02-section-the-meiji-reforms-and-the-industrialization-of-japan.md"
    "08-06-03-section-the-sino-japanese-war-and-the-annexation-of-taiwan.md"
    "08-06-04-section-the-russo-japanese-war-and-japan-as-an-emerging-power.md"
    "08-06-05-section-the-korean-annexation-and-the-expansion-of-japanese-empire.md"

    "08-07-00-chapter-intro-the-fall-of-imperial-china-and-the-rise-of-republicanism.md"
    "08-07-01-section-the-taiping-rebellion-and-the-costliest-civil-war-in-history.md"
    "08-07-02-section-the-opium-wars-and-the-forced-opening-of-china.md"
    "08-07-03-section-the-self-strengthening-movement-and-failed-modernization.md"
    "08-07-04-section-the-boxer-rebellion-and-the-eight-nation-alliance.md"
    "08-07-05-section-the-xinhai-revolution-and-the-collapse-of-the-qing-dynasty.md"

    "08-08-00-chapter-intro-the-british-raj-and-the-rise-of-indian-nationalism.md"
    "08-08-01-section-the-indian-rebellion-of-1857-and-the-end-of-the-mughal-empire.md"
    "08-08-02-section-the-british-raj-and-the-governance-of-india.md"
    "08-08-03-section-the-rise-of-the-indian-national-congress-and-early-independence-movements.md"
    "08-08-04-section-economic-exploitation-british-textiles-railroads-and-plantations.md"
    "08-08-05-section-the-social-reforms-and-the-role-of-education-in-india.md"

    "08-09-00-chapter-intro-the-growth-of-socialism-anarchism-and-revolutionary-ideas.md"
    "08-09-01-section-the-marxist-revolutionary-vision-and-the-communist-manifesto.md"
    "08-09-02-section-the-rise-of-trade-unions-and-the-labor-movement.md"
    "08-09-03-section-the-paris-commune-and-the-first-experiment-in-socialism.md"
    "08-09-04-section-the-growth-of-anarchist-movements-and-their-challenges-to-state-power.md"
    "08-09-05-section-the-birth-of-revolutionary-terrorism-and-political-assassinations.md"

    "08-10-00-chapter-intro-science-medicine-and-the-cultural-revolutions-of-the-19th-century.md"
    "08-10-01-section-the-darwinian-revolution-and-the-impact-of-evolutionary-theory.md"
    "08-10-02-section-the-germ-theory-of-disease-and-the-modernization-of-medicine.md"
    "08-10-03-section-psychoanalysis-and-the-rise-of-freudian-thought.md"
    "08-10-04-section-modern-art-literature-and-the-philosophical-movements-of-the-late-19th-century.md"

    "08-11-00-chapter-intro-the-rise-of-global-finance-and-economic-transformation.md"
    "08-11-01-section-the-end-of-wildcat-banking-and-the-birth-of-central-banks.md"
    "08-11-02-section-the-gold-standard-the-bimetallism-debate-and-monetary-policy.md"
    "08-11-03-section-the-rise-of-stock-markets-and-modern-corporate-capitalism.md"
    "08-11-04-section-the-panic-of-1873-and-the-long-depression.md"
    "08-11-05-section-the-creation-of-the-federal-reserve-and-the-financial-landscape-of-1914.md"
    "08-11-06-section-economic-imperialism-how-finance-dominated-the-colonial-world.md"

    "08-12-00-chapter-intro-the-balkan-crises-and-the-road-to-global-conflict.md"
    "08-12-01-section-the-ottoman-empire-the-sick-man-of-europe-and-the-rise-of-balkan-nationalism.md"
    "08-12-02-section-the-balkan-wars-and-the-collapse-of-ottoman-rule-in-europe.md"
    "08-12-03-section-the-assassination-of-archduke-franz-ferdinand-and-the-final-spark.md"

    "08-13-00-chapter-intro-the-world-in-1914-on-the-brink-of-the-great-war.md"
    "08-13-01-section-the-global-empires-of-1914.md"
    "08-13-02-section-the-race-for-dreadnoughts-and-the-rise-of-modern-military-tech.md"
    "08-13-03-section-the-alliance-systems-and-the-balance-of-power.md"
    "08-13-04-section-the-final-days-before-the-guns-of-august.md"

    "09-00-00-unit-intro-the-world-between-war-and-revolution-1914-1929.md"

    "09-01-00-chapter-intro-world-war-i-the-war-to-end-all-wars.md"
    "09-01-01-section-the-origins-of-world-war-i-alliances-militarism-and-nationalism.md"
    "09-01-02-section-the-assassination-of-archduke-franz-ferdinand-and-the-july-crisis.md"
    "09-01-03-section-the-western-front-trench-warfare-and-the-stalemate.md"
    "09-01-04-section-the-eastern-front-russian-failures-and-the-collapse-of-the-tsar.md"
    "09-01-05-section-the-ottoman-front-and-the-armenian-genocide.md"
    "09-01-05-section-global-war-the-middle-east-africa-and-the-war-at-sea.md"
    "09-01-06-section-technology-and-horror-poison-gas-tanks-and-airplanes.md"
    "09-01-07-section-the-united-states-enters-the-war-and-the-final-offensives.md"
    "09-01-08-section-the-armistice-of-1918-and-the-fallout-of-total-war.md"

    "09-02-00-chapter-intro-the-russian-revolution-and-the-birth-of-the-soviet-union.md"
    "09-02-01-section-the-tsarist-autocracy-and-the-struggles-of-prewar-russia.md"
    "09-02-02-section-the-february-revolution-the-collapse-of-the-romanovs.md"
    "09-02-03-section-the-rise-of-the-bolsheviks-lenin-and-the-october-revolution.md"
    "09-02-04-section-the-russian-civil-war-reds-vs-whites-and-the-making-of-the-ussr.md"
    "09-02-05-section-war-communism-and-the-devastation-of-russian-society.md"
    "09-02-06-section-lenin-the-new-economic-policy-and-the-consolidation-of-power.md"

    "09-03-00-chapter-intro-the-postwar-order-and-the-fragile-peace.md"
    "09-03-01-section-the-treaty-of-versailles-and-the-punishment-of-germany.md"
    "09-03-02-section-the-league-of-nations-hope-and-failure-in-global-diplomacy.md"
    "09-03-03-section-the-redrawing-of-borders-in-europe-and-the-rise-of-new-states.md"
    "09-03-04-section-the-weimar-republic-and-the-struggles-of-postwar-germany.md"
    "09-03-05-section-the-rise-of-fascism-in-italy-and-the-march-on-rome.md"

    "09-04-00-chapter-intro-the-1920s-in-europe-politics-culture-and-instability.md"
    "09-04-01-section-the-french-and-british-empires-after-the-war.md"
    "09-04-02-section-the-irish-war-of-independence-and-the-creation-of-the-irish-free-state.md"
    "09-04-03-section-the-economic-struggles-of-germany-and-hyperinflation.md"
    "09-04-04-section-the-dawning-of-totalitarianism-mussolini-and-the-fascist-state.md"
    "09-04-05-section-the-rise-of-hitler-and-the-birth-of-the-nazi-party.md"

    "09-05-00-chapter-intro-the-united-states-and-the-roaring-twenties.md"
    "09-05-01-section-the-economic-boom-and-the-age-of-consumerism.md"
    "09-05-02-section-prohibition-and-the-rise-of-organized-crime.md"
    "09-05-03-section-the-harlem-renaissance-and-the-changing-culture-of-america.md"
    "09-05-04-section-the-1920s-women's-movement-and-the-right-to-vote.md"
    "09-05-05-section-immigration-restrictions-and-the-rise-of-the-kkk.md"
    "09-05-06-section-the-stock-market-bubble-and-the-warning-signs-of-collapse.md"

    "09-06-00-chapter-intro-latin-america-nationalism-military-coups-and-economic-struggles.md"
    "09-06-01-section-the-mexican-revolution-and-the-new-political-order.md"
    "09-06-02-section-the-us-in-latin-america-dollar-diplomacy-and-interventions.md"
    "09-06-03-section-nationalism-and-economic-crisis-in-argentina-and-brazil.md"
    "09-06-04-section-economic-dependence-on-the-us-and-the-struggle-for-sovereignty.md"

    "09-07-00-chapter-intro-africa-under-colonial-rule-resistance-and-exploitation.md"
    "09-07-01-section-the-league-of-nations-mandates-and-the-repartitioning-of-africa.md"
    "09-07-02-section-resistance-movements-in-kenya-algeria-and-west-africa.md"
    "09-07-03-section-the-rise-of-pan-africanism-and-early-nationalist-movements.md"
    "09-07-04-section-the-economic-exploitation-of-africa-rubber-mines-and-forced-labor.md"

    "09-08-00-chapter-intro-the-middle-east-the-fall-of-the-ottomans-and-the-new-mandates.md"
    "09-08-01-armenian-genocide-and-the-fall-of-the-ottomans.md"
    "09-08-01-section-the-sykes-picot-agreement-and-the-birth-of-modern-borders.md"
    "09-08-02-section-the-balfour-declaration-and-the-seeds-of-the-israeli-palestinian-conflict.md"
    "09-08-03-section-the-rise-of-secular-nationalism-in-turkey-and-the-mustafa-kemal-reforms.md"
    "09-08-04-section-the-arab-nationalist-movements-and-the-struggles-for independence.md"

    "09-09-00-chapter-intro-china-and-japan-warlords-revolts-and-expansion.md"
    "09-09-01-section-the-warlord-era-and-the-fragmentation-of-china.md"
    "09-09-02-section-the-rise-of-the-chinese-communist-party-and-the-nationalists.md"
    "09-09-03-section-japan's-expansion-the-invasion-of-manchuria-and-militarism.md"
    "09-09-04-section-the-treaty-of-washington-and-japan's-place-in-the-global-order.md"

    "09-10-00-chapter-intro-india-gandhi-and-the-growing-call-for-independence.md"
    "09-10-01-section-the-continued-rule-of-the-british-raj-and-growing tensions.md"
    "09-10-02-section-mahatma-gandhi-and-the-nonviolent-resistance-movement.md"
    "09-10-03-section-the-salt-march-and-the-rise-of-indian-nationalism.md"
    "09-10-04-section-the-1929-lahore-resolution-and-the-call-for-complete-independence.md"

    "09-11-00-chapter-intro-the-end-of-the-1920s-and-the-crash-of-1929.md"
    "09-11-01-section-the-global-economic-boom-and-its-structural-weaknesses.md"
    "09-11-02-section-the-wall-street-crash-of-1929-and-the-beginning-of-the-great-depression.md"
    "09-11-03-section-how-the-crash-affected-global-economies-and-markets.md"
    "09-11-04-section-the-political-fallout-of-the-crash-the-rise-of-extremism.md"

    "10-00-00-unit-intro-the-great-depression-totalitarianism-and-world-war-ii-1929-1945.md"
    "10-01-00-chapter-intro-the-great-depression-and-its-aftermath.md"
    "10-01-01-section-the-wall-street-crash-of-1929-and-the-collapse-of-global-markets.md"
    "10-01-02-section-mass-unemployment-breadlines-and-the-human-cost-of-depression.md"
    "10-01-03-section-keynesian-economics-and-the-debate-over-government-intervention.md"
    "10-01-04-section-the-new-deal-franklin-d-roosevelt-and-america's-response.md"
    "10-01-05-section-how-the-great-depression-fueled-fascism-in-europe.md"
    "10-01-06-section-global-impacts-the-dust-bowl-latin-america-and-colonial-economies.md"
    "10-01-07-section-japan's-economic-crisis-and-the-rise-of-militarism.md"

    "10-02-00-chapter-intro-the-rise-of-fascism-communism-and-militarism.md"
    "10-02-01-section-mussolini-and-the-italian-fascist-state.md"
    "10-02-02-section-hitler-nazism-and-the-collapse-of-weimar-germany.md"
    "10-02-03-section-stalin-and-the-soviet-union-five-year-plans-and-political-purges.md"
    "10-02-04-section-the-spanish-civil-war-a-dress-rehearsal-for-world-war.md"
    "10-02-05-section-japan's-invasion-of-manchuria-and-the-failure-of-the-league-of-nations.md"
    "10-02-06-section-the-invasion-of-ethiopia-and-the-beginning-of-axis-expansion.md"

    "10-03-00-chapter-intro-hitler's-war-the-outbreak-of-world-war-ii.md"
    "10-03-01-section-the-molotov-ribbentrop-pact-and-the-invasion-of-poland.md"
    "10-03-02-section-the-fall-of-france-and-the-blitzkrieg-strategy.md"
    "10-03-03-section-the-battle-of-britain-and-churchill's-defiance.md"
    "10-03-04-section-operation-barbarossa-the-nazi-invasion-of-the-soviet-union.md"
    "10-03-05-section-the-holocaust-begins-the-nuremberg-laws-and-ghettos.md"
    "10-03-06-section-us-isolationism-and-the-lend-lease-act.md"

    "10-04-00-chapter-intro-the-pacific-war-japan's-expansion-and-america's-entry.md"
    "10-04-01-section-the-greater-east-asia-co-prosperity-sphere-and-japanese-expansion.md"
    "10-04-02-section-the-attack-on-pearl-harbor-and-the-us-declaration-of-war.md"
    "10-04-03-section-the-fall-of-the-philippines-and-the-bataan-death-march.md"
    "10-04-04-section-the-battle-of-midway-and-the-turning-point-in-the-pacific.md"

    "10-05-00-chapter-intro-the-allies-strike-back.md"
    "10-05-01-section-the-battle-of-stalingrad-the-bloodiest-battle-in-history.md"
    "10-05-02-section-the-north-africa-campaign-rommel-vs-the-allies.md"
    "10-05-03-section-the-invasion-of-italy-and-the-fall-of-mussolini.md"
    "10-05-04-section-d-day-the-normandy-landings-and-the-liberation-of-france.md"
    "10-05-05-section-the-allied-bombing-campaigns-on-germany-and-japan.md"
    "10-05-06-section-the-holocaust-death-camps-and-the-final-solution.md"

    "10-06-00-chapter-intro-the-end-of-world-war-ii-and-the-new-world-order.md"
    "10-06-01-section-the-battle-of-the-bulge-hitler's-final-gamble.md"
    "10-06-02-section-the-soviet-offensive-and-the-fall-of-berlin.md"
    "10-06-03-section-the-yalta-conference-and-the-shaping-of-postwar-europe.md"
    "10-06-04-section-the-battle-of-iwo-jima-and-the-firebombing-of-japan.md"
    "10-06-05-section-the-manhattan-project-and-the-use-of-the-atomic-bomb.md"
    "10-06-06-section-japan's-surrender-the-end-of-empire-and-the-american-occupation.md"

    "10-07-00-chapter-intro-the-aftermath-of-war-and-the-beginning-of-a-new-era.md"
    "10-07-01-section-the-nuremberg-trials-and-the-punishment-of-nazi-war-criminals.md"
    "10-07-02-section-the-rebuilding-of-europe-and-the-marshall-plan.md"
    "10-07-03-section-the-division-of-germany-and-the-iron-curtain.md"
    "10-07-04-section-the-founding-of-the-united-nations-and-the-new-world-order.md"
    "10-07-05-section-the-seeds-of-the-cold-war-us-vs-soviet-tensions.md"

    "11-00-00-unit-intro-the-postwar-world-and-the-early-cold-war-1945-1962.md"

    "11-01-00-chapter-intro-the-aftermath-of-world-war-ii-and-the-division-of-the-world.md"
    "11-01-01-section-the-yalta-and-potsdam-conferences-and-the-shaping-of-the-postwar-order.md"
    "11-01-02-section-the-occupation-of-germany-and-japan.md"
    "11-01-03-section-how-the-us-and-ussr-emerged-as-superpowers.md"
    "11-01-04-section-the-first-signs-of-cold-war-rivalry-in-europe-and-asia.md"

    "11-02-00-chapter-intro-the-nuremberg-trials-and-the-search-for-justice.md"
    "11-02-01-section-the-charges-against-nazi-leaders-and-the-legal-precedents-set.md"
    "11-02-02-section-the-defense-arguments-and-the-question-of-individual-responsibility.md"
    "11-02-03-section-the-verdicts-and-executions-of-top-nazi-officials.md"
    "11-02-04-section-the-long-term-impact-of-nuremberg-on-international-law.md"

    "11-03-00-chapter-intro-the-marshall-plan-and-the-economic-reconstruction-of-europe.md"
    "11-03-01-section-the-devastation-of-european-economies-after-wwii.md"
    "11-03-02-section-the-us-strategy-of-containment-through-economic-aid.md"
    "11-03-03-section-the-success of the-marshall-plan-and-the-rise-of-western-europe.md"
    "11-03-04-section-the-soviet-reaction-and-the-division-of-the-continent.md"

    "11-04-00-chapter-intro-the-division-of-germany-and-the-iron-curtain-descends.md"
    "11-04-01-section-how-germany-was-split-into-western-and-soviet-controlled-zones.md"
    "11-04-02-section-the-foundation-of-east-and-west-germany.md"
    "11-04-03-section-churchill's-iron-curtain-speech-and-the-hardening-of-divisions.md"
    "11-04-04-section-early-escape-attempts-and-repression-in-the-east.md"

    "11-05-00-chapter-intro-the-founding-of-the-united-nations-and-the-first-global-conflicts.md"
    "11-05-01-section-the-formation-of-the-un-and-the-promise-of-peace.md"
    "11-05-02-section-the-structure-of-the-security-council-and-the-veto-power.md"
    "11-05-03-section-the-un's-early failures-in-mediation.md"
    "11-05-04-section-the-un's-role-in-the-palestinian-mandate-and-korean-war.md"

    "11-06-00-chapter-intro-the-creation-of-israel-and-the-first-arab-israeli-war.md"
    "11-06-01-section-the-british-mandate-in-palestine-and-the-jewish-arab-conflict.md"
    "11-06-02-section-the-un-partition-plan-and-the-establishment-of-israel.md"
    "11-06-03-section-the-1948-war-between-israel-and-the-arab-states.md"
    "11-06-04-section-the-palestinian-refugee-crisis-and-the-birth-of-the-long-conflict.md"

    "11-07-00-chapter-intro-the-chinese-civil-war-and-the-triumph-of-mao.md"
    "11-07-01-section-the-long-struggle-between-the-communists-and-nationalists.md"
    "11-07-02-section-the-us-failure-to-support-chiang-kai-shek.md"
    "11-07-03-section-the-communist-victory-and-the-establishment-of-the-prc.md"
    "11-07-04-section-the-fate-of-taiwan-and-the-division-of-china.md"

    "11-08-00-chapter-intro-the-korean-war-the-first-hot-war-of-the-cold-war.md"
    "11-08-01-section-the-division-of-korea-after-world-war-ii.md"
    "11-08-02-section-north-korea's-invasion-and-the-united-nations-response.md"
    "11-08-03-section-the-chinese-counterattack-and-the-stalemate.md"
    "11-08-04-section-the-armistice-and-the-divided-korean-peninsula.md"

    "11-09-00-chapter-intro-the-beginning-of-global-decolonization.md"
    "11-09-01-section-the-collapse-of-european-colonial-empires.md"
    "11-09-02-section-the-independence-struggles-in-asia-and-africa.md"
    "11-09-03-section-the-role-of-the-us-and-ussr-in-decolonization.md"
    "11-09-04-section-the-newly-independent-states-and-their-political-struggles.md"

    "11-10-00-chapter-intro-the-partition-of-india-and-the-violent-birth-of-two-nations.md"
    "11-10-01-section-the-end-of-british-rule-in-india.md"
    "11-10-02-section-hindu-muslim-conflict-and-the-creation-of-pakistan.md"
    "11-10-03-section-the-massacres-and-refugee-crisis-of-1947.md"
    "11-10-04-section-nehru-jinnah-and-the-long-term-implications-of-partition.md"

    "11-11-00-chapter-intro-the-indochina-conflict-and-the-fall-of-french-colonialism.md"
    "11-11-01-section-the-french-return-to-indochina-and-the-viet-minh-resistance.md"
    "11-11-02-section-ho-chi-minh-and-the-communist-insurgency.md"
    "11-11-03-section-the-battle-of-dien-bien-phu-and-the-french-defeat.md"
    "11-11-04-section-the-geneva-accords-and-the-division-of-vietnam.md"

    "11-12-00-chapter-intro-the-algerian-war-and-the-decline-of-french-imperial-power.md"
    "11-12-01-section-the-rise-of-the-fnl-and-the-fight-for-algerian-independence.md"
    "11-12-02-section-the-french-military-response-and-the-use-of-torture.md"
    "11-12-03-section-de-gaulle's-return-to-power-and-the-end-of-the-war.md"
    "11-12-04-section-the-fallout-of-algerian-independence-for-france-and-the-pied-noirs.md"

    "11-13-00-chapter-intro-the-soviet-union-after-stalin-the-rise-of-khrushchev.md"
    "11-13-01-section-stalin's-death-and-the-struggle-for-power.md"
    "11-13-02-section-khrushchev's-secret-speech-and-the-destalinization-campaign.md"
    "11-13-03-section-the-soviet-economic-reforms-and-failures.md"
    "11-13-04-section-the-hungarian-revolution-of-1956-and-soviet-repression.md"

    "11-14-00-chapter-intro-the-space-race-begins-and-the-rise-of-nuclear-weapons.md"
    "11-14-01-section-the-development-of-the-hydrogen-bomb-and-thenuclear-arms-race.md"
    "11-14-02-section-sputnik-and-the-soviet-lead-in-space.md"
    "11-14-03-section-the-us-response-nasa-and-the-military-uses-of-space.md"
    "11-14-04-section-the-growing threat of nuclear war and arms control talks.md"

    "11-15-00-chapter-intro-the-iranian-coup-of-1953-and-the-us-global-intervention-strategy.md"
    "11-15-01-section-mossadegh's-nationalization-of-iranian-oil.md"
    "11-15-02-section-operation-ajax-the-cia's-overthrow-of-mossadegh.md"
    "11-15-03-section-the-shah's-rule-and-the-beginning-of-us-iranian-tensions.md"
    "11-15-04-section-how-the-coup-set-the-stage-for-future-us-covert operations.md"

    "11-16-00-chapter-intro-the-guatemalan-coup-of-1954-and-the-cia's-covert-wars.md"
    "11-16-01-section-the-reforms-of-jacobo-arbenz-and-us-corporate-interests.md"
    "11-16-02-section-operation-pbsuccess-and-the-military-overthrow.md"
    "11-16-03-section-the-aftermath-the-rise-of-military-dictatorships-in-latin-america.md"
    "11-16-04-section-how-guatemala-set-a-model-for-future-us-interventions.md"

    "11-17-00-chapter-intro-the-suez-crisis-the-final-humiliation-of-the-british-empire.md"
    "11-17-01-section-nasser-and-the-nationalization-of-the-suez-canal.md"
    "11-17-02-section-the-anglo-french-israeli-invasion-and-us-opposition.md"
    "11-17-03-section-the-collapse-of-british-french-power-in-the-middle-east.md"
    "11-17-04-section-the-suez-crisis-as-a-turning-point-for-postwar geopolitics.md"

    "11-18-00-chapter-intro-the-sino-soviet-split-and-the-crisis-of-global-communism.md"
    "11-18-01-section-the-growing-tensions-between-moscow-and-beijing.md"
    "11-18-02-section-mao's-ideological-rejection-of-soviet-revisionism.md"
    "11-18-03-section-the-border conflicts and proxy struggles.md"
    "11-18-04-section-the-split's impact on communist movements worldwide.md"

    "11-19-00-chapter-intro-the-great-leap-forward-and-the-deadliest-famine-in-human-history.md"
    "11-19-01-section-mao's-vision-for-rapid-industrialization.md"
    "11-19-02-section-the-collectivization-disaster-and-famine.md"
    "11-19-03-section-party-infighting-and-the-reckoning with the failure.md"
    "11-19-04-section-the-legacy-of-the-great-leap-forward-in-modern-china.md"

    "11-20-00-chapter-intro-the-rise-of-castro-and-the-cuban-revolution.md"
    "11-20-01-section-the-conditions in cuba before the revolution.md"
    "11-20-02-section-castro's-guerrilla-war and the fall of batista.md"
    "11-20-03-section-the-us reaction to castro's rise and early tensions.md"
    "11-20-04-section-the-transformation of cuba into a socialist state.md"

    "11-21-00-chapter-intro-the-bay-of-pigs-fiasco-and-the-us-anti-communist-crusade.md"
    "11-21-01-section-the-origins-of-the-plan-the-cia-and-cuban-exiles.md"
    "11-21-02-section-the-failed-invasion-and-castro's-decisive victory.md"
    "11-21-03-section-the-impact-on-us-latin-american-policy.md"
    "11-21-04-section-how-the-bay-of-pigs-led-directly-to-the-cuban-missile-crisis.md"

    "11-22-00-chapter-intro-mccarthyism-the-red-scare-and-the-hunt-for-communists.md"
    "11-22-01-section-the-origins-of-anti-communism-in-america-and-the-soviet-threat.md"
    "11-22-02-section-joseph-mccarthy-the-hollywood-blacklist-and-political-purges.md"
    "11-22-03-section-the-army-mccarthy-hearings-and-the-downfall-of-mccarthy.md"
    "11-22-04-section-the-lasting-impact-of-mccarthyism-on-us-politics-and-culture.md"
    "11-22-05-section-the-venona-files-and-what-we-now-know-about-soviet-infiltration.md"

    "11-23-00-chapter-intro-the-western-economic-boom-and-the-rise-of-consumer-culture.md"
    "11-23-01-section-the-postwar-economic miracle-in-western-europe.md"
    "11-23-02-section-the-us-suburban-boom-the-rise-of-the-middle-class-and-credit.md"
    "11-23-03-section-the-japanese-economic-recovery-and-the-zaibatsu-reforms.md"
    "11-23-04-section-the-globalization-of-american-consumer culture-and-advertising.md"

    "11-24-00-chapter-intro-the-early-civil-rights-movements-in-the-united-states.md"
    "11-24-01-section-the-legal-battle-against-segregation-brown-v-board.md"
    "11-24-02-section-rosa-parks-the-montgomery-bus-boycott-and-the-rise-of-mlk.md"
    "11-24-03-section-the-little-rock-nine-and-the-resistance-to-integration.md"
    "11-24-04-section-the-early-struggles-of-black-activists-against-systemic-racism.md"

    "11-25-00-chapter-intro-the-berlin-crisis-and-the-construction-of-the-berlin-wall.md"
    "11-25-01-section-the-mass-exodus-from-east-germany-and-soviet-concerns.md"
    "11-25-02-section-the-building-of-the-wall-and-the-sealing-of-berlin.md"
    "11-25-03-section-western-reactions-and-kennedy's-defiant-stance.md"
    "11-25-04-section-how-the-wall-symbolized-the-deepening-divide-of-the-cold-war.md"

    "11-26-00-chapter-intro-the-cuban-missile-crisis-the-world-on-the-brink-of-nuclear-war.md"
    "11-26-01-section-the-discovery-of-soviet-missiles-in-cuba.md"
    "11-26-02-section-the-us-naval-blockade-and-kennedy's-deadline.md"
    "11-26-03-section-the-tense-negotiations-and-the-last-minute-deal.md"
    "11-26-04-section-the-aftermath-how-the-world-narrowly-avoided-disaster.md"

    "11-27-00-chapter-intro-the-aftermath-of-1962-and-the-new-global-order.md"
    "11-27-01-section-the-us-soviet-hotline-and-the-shift-in-cold-war-strategy.md"
    "11-27-02-section-the-impact-of-the-crisis-on-latin-america-and-the-third-world.md"
    "11-27-03-section-the-early-1960s-international-power-shifts-and-alliances.md"
    "11-27-04-section-how-1962-set-the-stage-for-the-turbulence-of-the-late-60s.md"



    "08-00-00-the-21st-century-and-the-future.md"

    "08-01-00-globalization-and-the-digital-revolution.md"
    "08-01-01-the-internet-and-the-information-age.md"
    "08-01-02-the-rise-of-social-media-and-its-impact-on-politics-and-culture.md"
    "08-01-03-the-role-of-media-and-propaganda-in-modern-history.md"
    "08-01-04-how-mass-media-shaped-public-opinion-in-the-20th-century.md"
    "08-01-05-the-rise-of-social-media-and-its-political-influence.md"
    "08-01-06-mass-surveillance-and-the-modern-security-state.md"

    "08-02-00-the-changing-geopolitical-landscape.md"
    "08-02-01-the-us-china-competition-and-economic-war.md"
    "08-02-02-the-rise-of-china-and-the-belt-and-road-initiative.md"
    "08-02-03-chinas-economic-rise-and-global-trade-influence.md"
    "08-02-04-the-geopolitical-strategies-of-the-belt-and-road-initiative.md"
    "08-02-05-the-role-of-private-military-companies-in-modern-conflicts.md"

    "08-03-00-modern-society-and-the-future-of-governance.md"
    "08-03-01-the-changing-nature-of-governance-and-sovereignty-in-a-digital-age.md"
    "08-03-02-the-modern-migration-crisis-and-global-demographics.md"
    "08-03-03-the-impact-of-mass-migration-on-europe-and-the-us.md"
    "08-03-04-demographic-changes-and-future-population-trends.md"
    "08-03-05-the-role-of-big-tech-in-governance-and-society.md"
    "08-03-06-how-google-facebook-and-ai-are-shaping-the-modern-world.md"
    "08-03-07-the-debate-over-privacy-and-digital-surveillance.md"

    "08-04-00-the-future-of-humanity-possibilities-and-perils.md"
    "08-04-01-existential-risks-to-humanity-nuclear-war-biotech-ai.md"
    "08-04-02-the-impact-of-automation-and-artificial-intelligence-on-society.md"
    "08-04-03-how-technological-change-could-shape-the-economy-and-workforce.md"
    "08-04-04-the-future-of-money-decentralization-digital-currencies-and-global-trade.md"
    "08-04-05-the-role-of-scientific-advancements-in-medicine-and-longevity.md"
    "08-04-06-space-exploration-and-the-possibility-of-human-settlement-beyond-earth.md"
    "08-04-07-utopian-and-dystopian-visions-of-the-future.md"
    "08-04-08-the-challenges-and-opportunities-of-a-globalized-world.md"
    "08-04-09-how-human-values-and-culture-might-evolve-in-the-coming-centuries.md"

    # The Modern Surveillance State (21st Century)
    "08-05-00-the-rise-of-the-modern-surveillance-state.md"
    "08-05-01-edward-snowden-wikileaks-and-digital-leaks.md"
    "08-05-02-how-governments-use-ai-and-mass-data-for-control.md"
    "08-05-03-chinas-social-credit-system-and-the-future-of-surveillance.md"
)

# Loop through files and run `corpora workon`
for file in "${files[@]}"; do
    corpora infer "$file" --check ./build.sh
    git add .
    git commit -m "Add $file"
    corpora sync --noinput
done
