// Regenerate src/data/npcCorpus.ts with all 51 canonical languages:
//  - rekey ko -> ko-polite (preserving the existing polite Korean)
//  - merge the 24 NEW languages from translations.json (matched by English)
//  - emit each MultiLangText with keys in CANONICAL_ORDER
// Fails loudly if any field can't be fully populated.
import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { loadCorpus, corpusPath } from "./loadCorpus.mjs"
import { CANONICAL_ORDER, NEW, REKEY } from "./langs.mjs"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const corpus = await loadCorpus()
const translations = JSON.parse(
  await readFile(path.join(__dirname, "translations.json"), "utf8")
)

const errors = []

const buildField = (mlt, where) => {
  const out = {}
  for (const [k, v] of Object.entries(mlt)) {
    out[REKEY[k] ?? k] = v
  }
  const en = mlt.en
  const tr = translations[en]
  if (!tr) {
    errors.push(`${where}: no translations for "${en}"`)
    return out
  }
  for (const lang of NEW) {
    const val = tr[lang]
    if (typeof val !== "string" || val.trim() === "") {
      errors.push(`${where}: missing ${lang} for "${en}"`)
      continue
    }
    out[lang] = val
  }
  const missing = CANONICAL_ORDER.filter((l) => out[l] === undefined)
  if (missing.length) errors.push(`${where}: missing keys ${missing.join(",")} for "${en}"`)
  return out
}

const fmtMlt = (mlt) =>
  "{ " +
  CANONICAL_ORDER.map((l) => `${JSON.stringify(l)}: ${JSON.stringify(mlt[l])}`).join(", ") +
  " }"

const blocks = corpus.map((enc) => {
  const offering = buildField(enc.offering, `${enc.id}.offering`)
  const responses = enc.responses.map((r, i) => {
    const text = buildField(r.text, `${enc.id}.responses[${i}](${r.type})`)
    return `      { "type": ${JSON.stringify(r.type)}, "text": ${fmtMlt(text)} },`
  })
  return [
    "  {",
    `    "id": ${JSON.stringify(enc.id)},`,
    `    "npcType": ${JSON.stringify(enc.npcType)},`,
    `    "offering": ${fmtMlt(offering)},`,
    "    \"responses\": [",
    ...responses,
    "    ],",
    "  },",
  ].join("\n")
})

if (errors.length) {
  console.error(`apply FAILED with ${errors.length} error(s):`)
  for (const e of errors.slice(0, 50)) console.error("  " + e)
  process.exit(1)
}

const header =
  "import type { NPCCorpus } from \"./npcCorpusTypes\"\n\n" +
  "// Generated by scripts/i18n/apply.mjs. Source of truth for the English text\n" +
  "// and structure is this file; translations are authored in scripts/i18n/.\n" +
  "// All 51 corpan languages are present per field (see scripts/i18n/langs.mjs).\n\n" +
  "export const npcCorpus: NPCCorpus = [\n"

const out = header + blocks.join("\n") + "\n]\n"
await writeFile(corpusPath, out)
console.log(`Regenerated npcCorpus.ts: ${corpus.length} encounters, 51 languages each.`)
