// Generate review-by-language.md: for each NEW language, a table of
// English source -> translation for all sources, so quality can be eyeballed
// end-to-end per language. Reads translations.json.
import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { NEW, LANG_NAMES } from "./langs.mjs"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const sources = JSON.parse(
  await readFile(path.join(__dirname, "sources.json"), "utf8")
)
const translations = JSON.parse(
  await readFile(path.join(__dirname, "translations.json"), "utf8")
)

const esc = (s) => String(s ?? "").replace(/\|/g, "\\|")

let md = "# Quest-Ear NPC corpus — translation review\n\n"
md += `${sources.length} source strings × ${NEW.length} new languages. `
md += "Generated by scripts/i18n/review.mjs. Eyeball each language below.\n\n"
md += "Languages: " + NEW.map((l) => `${LANG_NAMES[l]} (${l})`).join(", ") + "\n"

for (const lang of NEW) {
  md += `\n## ${LANG_NAMES[lang]} (\`${lang}\`)\n\n`
  md += "| English | " + lang + " |\n|---|---|\n"
  for (const src of sources) {
    md += `| ${esc(src)} | ${esc(translations[src]?.[lang])} |\n`
  }
}

await writeFile(path.join(__dirname, "review-by-language.md"), md)
console.log(`Wrote review-by-language.md (${sources.length} rows × ${NEW.length} langs)`)
