export const LANGUAGE_NAMES: Record<string, string> = {
    en: "English",
    es: "Spanish",
    fr: "French",
    it: "Italian",
    "pt-BR": "Portuguese (BR)",
    de: "German",
    pl: "Polish",
    ru: "Russian",
    hu: "Hungarian",
    tr: "Turkish",
    ar: "Arabic",
    fa: "Persian",
    hi: "Hindi",
    bn: "Bengali",
    th: "Thai",
    vi: "Vietnamese",
    id: "Indonesian",
    "zh-Hans": "Chinese (Simplified)",
    "zh-Hant": "Chinese (Traditional)",
    "ko-polite": "Korean (Polite)",
    ja: "Japanese",
    ta: "Tamil",
    te: "Telugu",
    kn: "Kannada",
    mr: "Marathi",
    gu: "Gujarati",
    "pa-Guru": "Punjabi (Gurmukhi)",
    "pa-Arab": "Punjabi (Shahmukhi)",
    ur: "Urdu",
};


export const RTL_LANGUAGES = ["ar", "he", "fa", "pa-Arab", "ur"];

export const DOMAIN_NAMES: Record<string, string> = {
    travel: "Travel",
    business: "Business",
    education: "Education",
    social: "Social",
    health: "Health",
    housing: "Housing",
    numbers: "Numbers",
    civic: "Civic",
    technology: "Technology",
    environment: "Environment",
    emergency: "Emergency",
    culture: "Culture",
    everyday: "Everyday",
};
