export const LANGUAGE_NAMES: Record<string, string> = {
    en: "English",
    es: "Spanish",
    fr: "French",
    it: "Italian",
    "pt-BR": "Portuguese (BR)",
    de: "German",
    sv: "Swedish",
    no: "Norwegian",
    da: "Danish",
    nl: "Dutch",
    pl: "Polish",
    ru: "Russian",
    hu: "Hungarian",
    fi: "Finnish",
    tr: "Turkish",
    el: "Greek",
    he: "Hebrew",
    ar: "Arabic",
    fa: "Persian",
    hi: "Hindi",
    bn: "Bengali",
    th: "Thai",
    vi: "Vietnamese",
    id: "Indonesian",
    ms: "Malay",
    sw: "Swahili",
    "zh-Hans": "Chinese (Simplified)",
    "zh-Hant": "Chinese (Traditional)",
    "ko-polite": "Korean (Polite)",
    ja: "Japanese",
    ta: "Tamil",
    te: "Telugu",
    kn: "Kannada",
    mr: "Marathi",
    gu: "Gujarati",
    "pa-Guru": "Punjabi (Gurmukhi)",
    "pa-Arab": "Punjabi (Shahmukhi)",
    ur: "Urdu",
    ne: "Nepali",
    "pt-PT": "Portuguese (PT)",
    hr: "Croatian",
    sr: "Serbian",
    uk: "Ukrainian",
    bg: "Bulgarian",
    ro: "Romanian",
    ca: "Catalan",
    "yue-Hant-HK": "Cantonese",
    cs: "Czech",
    lt: "Lithuanian",
    sk: "Slovak",
    sl: "Slovenian",
};


export const RTL_LANGUAGES = ["ar", "he", "fa", "pa-Arab", "ur"];

export const DOMAIN_NAMES: Record<string, string> = {
    travel: "Travel",
    business: "Business",
    education: "Education",
    social: "Social",
    health: "Health",
    housing: "Housing",
    numbers: "Numbers",
    civic: "Civic",
    technology: "Technology",
    environment: "Environment",
    emergency: "Emergency",
    culture: "Culture",
    everyday: "Everyday",
};
