#!/usr/bin/env node
// Regenerates ../strings.ts — the cap-pronounce chrome-string subset —
// from the pronunciation-coach pack's full i18n table (the pack keeps its
// 5k-line table for pack chrome; the capability carries ONLY the keys its
// round/result UI renders, per capability-modules.md §2.5/§4.1).
//
// Run with node >= 22 (type stripping):
//   node packs/shared/capabilities/pronounce/scripts/gen-strings.mjs
import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import path from "node:path"

const here = path.dirname(fileURLToPath(import.meta.url))
const i18nPath = path.resolve(
  here,
  "../../../../pronunciation-coach/src/i18n.ts",
)
const { en, LOCALES } = await import(i18nPath)

const KEYS = [
  // round chrome
  "holdToSpeak",
  "loadingModel",
  "listeningReleaseToStop",
  "scoring",
  "bootLoading",
  "scoringUnavailableTitle",
  "scoringUnavailableSub",
  // result view
  "resultTryAgain",
  "resultCouldntHear",
  "resultPerfect",
  "resultNailedIt",
  "resultGreat",
  "resultPrettyGood",
  "resultCloseKeepGoing",
  "resultKeepPracticing",
  "heardYouSay",
  "couldntMakeOutWords",
  "chipSoundedFaint",
  "chipSoundedGarbled",
  "chipCouldntMakeOut",
  "chipWordsDidntMatch",
  "chipDifferentScript",
  "hintMoveCloser",
  // aria / errors the round surfaces
  "ariaClose",
  "ariaSpeakWord",
  "ariaPlayHeard",
  "errStartRecording",
  "errScoringFailed",
]

const pick = (dict) => {
  const out = {}
  for (const k of KEYS) {
    if (dict && typeof dict[k] === "string") out[k] = dict[k]
  }
  return out
}

const locales = {}
for (const [code, dict] of Object.entries(LOCALES)) {
  const subset = pick(dict)
  if (Object.keys(subset).length > 0) locales[code] = subset
}

const banner = `// GENERATED by scripts/gen-strings.mjs — do not hand-edit translations.
// Source of truth: packs/pronunciation-coach/src/i18n.ts (full pack table).
// This is the ~29-key chrome subset the cap-pronounce round/result UI
// renders (capability-modules.md §2.5). Regenerate after i18n.ts changes:
//   node packs/shared/capabilities/pronounce/scripts/gen-strings.mjs
`

const body = `${banner}
export type CapPronounceStringKey =
${KEYS.map((k) => `  | ${JSON.stringify(k)}`).join("\n")}

type Dict = Record<CapPronounceStringKey, string>

const en: Dict = ${JSON.stringify(pick(en), null, 2)}

const LOCALES: Record<string, Partial<Dict>> = ${JSON.stringify(locales, null, 2)}

const baseLocale = (lang: string): string => lang.split("-")[0]

/** Translate \`key\` into \`lang\`: full code first (zh-Hant / pa-Arab win
 *  their script), then base, then English per-key — never blank. */
export function capPronounceT(
  key: CapPronounceStringKey,
  lang: string,
  params?: Record<string, string>,
): string {
  const loc = baseLocale(lang)
  const s = LOCALES[lang]?.[key] ?? LOCALES[loc]?.[key] ?? en[key]
  if (!params) return s
  return Object.entries(params).reduce(
    (acc, [k, v]) => acc.split(\`{\${k}}\`).join(v),
    s,
  )
}
`

writeFileSync(path.resolve(here, "../strings.ts"), body)
console.log(
  `wrote strings.ts: ${KEYS.length} keys x ${Object.keys(locales).length + 1} locales`,
)
