#!/usr/bin/env node
/**
 * Aggregate every JSON file under `src/locales/` into a single
 * generated ESM module at `src/locales.generated.js`.
 *
 * Why: Vite library-mode IIFE builds don't include files referenced
 * only via `import.meta.glob({ eager: true })`. Static imports
 * resolve correctly though, so we generate one module that imports
 * each locale and re-exports them as a `{ <lang>: <bundle> }` map.
 *
 * Run automatically before `vite build` via the `prebuild` npm
 * script. Idempotent — safe to re-run when locales change.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const packRoot = path.resolve(__dirname, "..")
const localesDir = path.join(packRoot, "src", "locales")
const outPath = path.join(packRoot, "src", "locales.generated.js")

const files = readdirSync(localesDir)
  .filter((f) => f.endsWith(".json"))
  .sort()

const banner = `// Auto-generated by scripts/build-locales.mjs — do not edit by hand.
// Source: src/locales/*.json (one file per corpan locale).
`

const entries = files.map((f) => {
  const lang = f.replace(/\.json$/, "")
  const raw = readFileSync(path.join(localesDir, f), "utf8")
  // Validate JSON shape, but emit the raw text so we preserve
  // formatting and Unicode. Wrap in a JS object literal.
  JSON.parse(raw)
  return `  ${JSON.stringify(lang)}: ${raw.trimEnd()},`
})

const body = `${banner}
const LOCALES = {
${entries.join("\n")}
}

export default LOCALES
`

writeFileSync(outPath, body, "utf8")
console.log(
  `[build-locales] wrote ${files.length} locales → ${path.relative(packRoot, outPath)}`,
)
