"""Shared helpers for the Journey course-pack pipeline.

Spec: corpan/docs/journey/specs/course-pack.md (normative).

This module carries:
  - repo path resolution,
  - the canonical ItemRef serialization helpers (mirror of the ONE contract
    helper in corpan-app/src/contentPacks/activityContract.ts, R2),
  - ACTIVITY_TYPES loaded from the SYNCED contract copy (never hand-copied,
    R4 — packs/sdk/activityContract.ts is generated by
    `node packs/sdk/sync-contract.mjs` and CI keeps it byte-identical to the
    authoritative corpan-app file),
  - the vendored 54-language list (settings.ts ALL_LANGUAGES, gate V-5),
  - the full SQLite DDL (course-pack.md §2, incl. build-time text_len),
  - CEFR difficulty anchors + shared constants.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

HERE = Path(__file__).resolve().parent          # corpan/dja/journey_pack
DJA_DIR = HERE.parent                           # corpan/dja
CORPAN_DIR = DJA_DIR.parent                     # corpan
SYNCED_CONTRACT = CORPAN_DIR / "packs" / "sdk" / "activityContract.ts"

JOURNEY_SCHEMA_VERSION = 1

# ---------------------------------------------------------------------------
# ItemRef — canonical serialization (course-pack.md §1 / contract R2).
# Python mirror of itemRefKey()/parseItemRef() in activityContract.ts.
# kind and source never contain ":"; id may — parse on the FIRST TWO colons.
# ---------------------------------------------------------------------------

ITEM_KINDS = (
    "phrase", "word", "char", "segment", "grammarNode", "phoneme", "concept",
)


@dataclass(frozen=True)
class ItemRef:
    kind: str
    source: str
    id: str


def item_ref_key(ref: ItemRef) -> str:
    return f"{ref.kind}:{ref.source}:{ref.id}"


def parse_item_ref(s: str) -> Optional[ItemRef]:
    i = s.find(":")
    if i < 0:
        return None
    j = s.find(":", i + 1)
    if j < 0:
        return None
    return ItemRef(kind=s[:i], source=s[i + 1:j], id=s[j + 1:])


# ---------------------------------------------------------------------------
# ACTIVITY_TYPES — read from the synced contract copy (R4). We PARSE the
# generated TypeScript rather than keeping a second hand-written list, so the
# Python pipeline can never drift from the contract: sync-contract.mjs --check
# already gates the TS copies, and we read one of those synced copies.
# ---------------------------------------------------------------------------

_ACTIVITY_TYPES_RE = re.compile(
    r"export\s+const\s+ACTIVITY_TYPES\s*=\s*\{(.*?)\n\}", re.S,
)
_ACTIVITY_ROW_RE = re.compile(r"^\s*([a-z][a-z0-9_]*)\s*:\s*\{", re.M)


def load_activity_types(contract_path: Path = SYNCED_CONTRACT) -> List[str]:
    """Keys of the ACTIVITY_TYPES registry, from the synced contract copy."""
    if not contract_path.exists():
        raise FileNotFoundError(
            f"synced activity contract not found at {contract_path} — "
            "run `node packs/sdk/sync-contract.mjs` from the corpan repo root"
        )
    src = contract_path.read_text(encoding="utf-8")
    m = _ACTIVITY_TYPES_RE.search(src)
    if not m:
        raise ValueError(
            f"could not locate `export const ACTIVITY_TYPES` in {contract_path}"
        )
    keys = _ACTIVITY_ROW_RE.findall(m.group(1))
    if not keys:
        raise ValueError(
            f"ACTIVITY_TYPES block in {contract_path} parsed to zero entries"
        )
    return keys


# `<packId>:<name>` pack-provided activity types (contract §ActivitySpec).
PACK_ACTIVITY_TYPE_RE = re.compile(r"^[a-z][a-z0-9_]*:[a-z][a-z0-9_-]*$")


# ---------------------------------------------------------------------------
# Canonical 54 language codes — vendored from
# corpan-app/src/store/settings.ts ALL_LANGUAGES (gate V-5).
# ---------------------------------------------------------------------------

ALL_LANGUAGES = [
    "en", "es", "ca", "fr", "it", "ro", "pt-PT", "pt-BR",
    "de", "nl",
    "no", "sv", "da",
    "fi", "hu",
    "lt",
    "pl", "cs", "sk", "sl", "hr", "sr",
    "bg", "uk", "ru",
    "el", "tr",
    "he", "ar", "fa", "ur", "pa-Arab",
    "pa-Guru", "hi", "ne", "bn", "mr", "gu", "kn", "te", "ta",
    "th", "vi", "id", "jv", "su", "ms", "tl",
    "sw",
    "zh-Hans", "zh-Hant", "yue-Hant-HK", "ko-polite", "ja",
]
assert len(ALL_LANGUAGES) == 54

# ---------------------------------------------------------------------------
# CEFR anchors (course-pack.md §6.2 step 5; adaptivity §2.3).
# ---------------------------------------------------------------------------

CEFR_CENTERS = {
    "preA1": -3.5, "A0": -3.5, "A1": -3.0, "A2": -1.5,
    "B1": 0.0, "B2": 1.5, "C1": 3.0, "C2": 4.0,
}
CEFR_ARC_VALUES = ("preA1", "A1", "A2", "B1", "B2", "C1", "C2")

# House copy hygiene (gate V-13). Absolutes banned in user-facing copy plus
# the "flagging" pet peeve. Checked case-insensitively as standalone words.
BANNED_COPY_WORDS = (
    "forever", "never", "100%", "entirely", "always", "guaranteed",
    "flag", "flags", "flagging", "flagged",
)

SLOT_TYPES = (
    "review.retrieve",
    "input.listen", "input.read", "input.picture",
    "practice.pick", "practice.match", "practice.order", "practice.cloze",
    "practice.minimal-pair",
    "produce.speak", "produce.write", "produce.translate",
    "fluency.game-round", "fluency.shadow", "fluency.timed-review",
    "grammar.note", "meta.recap",
)

ITEM_SELECTORS = (
    "due", "new", "unit", "known", "grammar-node", "l1-phoneme", "rare", "none",
)

RARE_CARD_TYPES = ("delight", "minigame", "etymology", "story")

# R13 / gate V-9: providers a v0.1 unit anchor (or rare-card provider) may
# reference. beatlounge/hover_runner/tutomaton/stargate are v0.2 swaps.
V01_ANCHOR_PROVIDERS = (
    "lingo_hero", "earthgate", "cap-segment-player", "corpan_city",
    "cap-pronounce", "cap-squeeze",
)

SPINE_ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")


def unit_id_re(target: str) -> re.Pattern:
    """V-15 unit-id grammar for an underscore-canonical target subtag."""
    return re.compile(
        rf"^{re.escape(target)}\.(a0|a1|a2|b1|b2|c1|c2)\.u\d{{2}}$"
    )


def arc_id_re(target: str) -> re.Pattern:
    return re.compile(rf"^{re.escape(target)}\.arc\d+$")


def underscore_lang(code: str) -> str:
    """Hyphens→underscores, lowercase — the installer-canonical subtag form."""
    return code.lower().replace("-", "_")


def nfc_len(text: str) -> int:
    """NFC code-point length (items.text_len, course-pack.md §2)."""
    return len(unicodedata.normalize("NFC", text))


# ---------------------------------------------------------------------------
# SQLite DDL — course-pack.md §2, verbatim structure (incl. text_len).
# PRAGMAs are applied separately by the builder.
# ---------------------------------------------------------------------------

DDL = """
CREATE TABLE pack_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
) WITHOUT ROWID;

CREATE TABLE arcs (
    id          TEXT    PRIMARY KEY,
    arc_index   INTEGER NOT NULL UNIQUE,
    cefr        TEXT    NOT NULL
                CHECK (cefr IN ('preA1','A1','A2','B1','B2','C1','C2')),
    title_key   TEXT    NOT NULL
);

CREATE TABLE units (
    id               TEXT    PRIMARY KEY,
    arc_id           TEXT    NOT NULL REFERENCES arcs(id),
    unit_index       INTEGER NOT NULL,
    theme_key        TEXT    NOT NULL,
    cando_keys_json  TEXT    NOT NULL,
    vocab_rank_lo    INTEGER,
    vocab_rank_hi    INTEGER,
    phrase_domains_json TEXT,
    anchor_provider  TEXT,
    anchor_config_json TEXT,
    UNIQUE (arc_id, unit_index)
);
CREATE INDEX idx_units_arc ON units(arc_id, unit_index);

CREATE TABLE skills (
    id            TEXT PRIMARY KEY,
    unit_id       TEXT NOT NULL REFERENCES units(id),
    kind          TEXT NOT NULL
                  CHECK (kind IN ('grammar','vocab','phonology','script','function')),
    title_key     TEXT NOT NULL,
    difficulty_b  REAL NOT NULL
);
CREATE INDEX idx_skills_unit ON skills(unit_id);

CREATE TABLE skill_edges (
    from_skill TEXT NOT NULL REFERENCES skills(id),
    to_skill   TEXT NOT NULL REFERENCES skills(id),
    PRIMARY KEY (from_skill, to_skill),
    CHECK (from_skill <> to_skill)
) WITHOUT ROWID;
CREATE INDEX idx_skill_edges_to ON skill_edges(to_skill);

CREATE TABLE grammar_nodes (
    id            TEXT    PRIMARY KEY,
    skill_id      TEXT    NOT NULL REFERENCES skills(id),
    node_order    INTEGER NOT NULL UNIQUE,
    cefr          TEXT    NOT NULL,
    title_key     TEXT    NOT NULL,
    note_key      TEXT    NOT NULL,
    late_acquired INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_grammar_nodes_skill ON grammar_nodes(skill_id);

CREATE TABLE items (
    id            TEXT    PRIMARY KEY,
    kind          TEXT    NOT NULL
                  CHECK (kind IN ('phrase','word','char','segment',
                                  'grammarNode','phoneme','concept')),
    source        TEXT    NOT NULL,
    ref_id        TEXT    NOT NULL,
    unit_id       TEXT    NOT NULL REFERENCES units(id),
    intro_order   INTEGER NOT NULL UNIQUE,
    difficulty_b  REAL    NOT NULL,
    importance    INTEGER NOT NULL DEFAULT 2
                  CHECK (importance BETWEEN 0 AND 3),
    is_probe      INTEGER NOT NULL DEFAULT 0,
    substitutable INTEGER NOT NULL DEFAULT 0,
    freq_rank     INTEGER,
    text_len      INTEGER NOT NULL DEFAULT 0,
    UNIQUE (kind, source, ref_id)
);
CREATE INDEX idx_items_unit  ON items(unit_id);
CREATE INDEX idx_items_intro ON items(intro_order);
CREATE INDEX idx_items_probe ON items(is_probe) WHERE is_probe = 1;

CREATE TABLE item_skills (
    item_id  TEXT NOT NULL REFERENCES items(id),
    skill_id TEXT NOT NULL REFERENCES skills(id),
    PRIMARY KEY (item_id, skill_id)
) WITHOUT ROWID;
CREATE INDEX idx_item_skills_skill ON item_skills(skill_id);

CREATE TABLE lesson_recipes (
    id          TEXT PRIMARY KEY,
    title_key   TEXT NOT NULL,
    est_minutes REAL NOT NULL
);

CREATE TABLE recipe_slots (
    recipe_id      TEXT    NOT NULL REFERENCES lesson_recipes(id),
    slot_index     INTEGER NOT NULL,
    slot_type      TEXT    NOT NULL,
    activity_types_json TEXT NOT NULL,
    item_selector  TEXT    NOT NULL
                   CHECK (item_selector IN ('due','new','unit','known','grammar-node',
                                            'l1-phoneme','rare','none')),
    params_json    TEXT,
    optional       INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (recipe_id, slot_index)
) WITHOUT ROWID;

CREATE TABLE unit_lessons (
    unit_id      TEXT    NOT NULL REFERENCES units(id),
    lesson_index INTEGER NOT NULL,
    recipe_id    TEXT    NOT NULL REFERENCES lesson_recipes(id),
    params_json  TEXT,
    PRIMARY KEY (unit_id, lesson_index)
) WITHOUT ROWID;

CREATE TABLE checkpoints (
    id          TEXT PRIMARY KEY,
    scope       TEXT NOT NULL CHECK (scope IN ('unit','arc')),
    unit_id     TEXT REFERENCES units(id),
    arc_id      TEXT REFERENCES arcs(id),
    recipe_id   TEXT NOT NULL REFERENCES lesson_recipes(id),
    pass_score  REAL NOT NULL DEFAULT 0.8,
    params_json TEXT,
    CHECK ((scope = 'unit') = (unit_id IS NOT NULL)),
    CHECK ((scope = 'arc')  = (arc_id  IS NOT NULL))
);
CREATE UNIQUE INDEX idx_checkpoints_unit ON checkpoints(unit_id) WHERE unit_id IS NOT NULL;
CREATE UNIQUE INDEX idx_checkpoints_arc  ON checkpoints(arc_id)  WHERE arc_id  IS NOT NULL;

CREATE TABLE rare_cards (
    id            TEXT    PRIMARY KEY,
    card_type     TEXT    NOT NULL
                  CHECK (card_type IN ('delight','minigame','etymology','story')),
    rarity_weight INTEGER NOT NULL,
    min_unit_id   TEXT REFERENCES units(id),
    provider      TEXT,
    item_id       TEXT REFERENCES items(id),
    coverage_gate REAL,
    params_json   TEXT
);
CREATE INDEX idx_rare_cards_type ON rare_cards(card_type);

CREATE TABLE l1_overlays (
    l1           TEXT NOT NULL,
    overlay_type TEXT NOT NULL
                 CHECK (overlay_type IN ('contrastive_note','cognate_credit',
                                         'phoneme_pair')),
    ref_kind     TEXT NOT NULL
                 CHECK (ref_kind IN ('grammarNode','unit','item','course')),
    ref_id       TEXT NOT NULL,
    string_key   TEXT,
    payload_json TEXT,
    PRIMARY KEY (l1, overlay_type, ref_kind, ref_id)
) WITHOUT ROWID;
CREATE INDEX idx_l1_overlays_l1 ON l1_overlays(l1);

CREATE TABLE strings (
    key  TEXT NOT NULL,
    lang TEXT NOT NULL,
    text TEXT NOT NULL,
    PRIMARY KEY (key, lang)
) WITHOUT ROWID;
"""


def sha256_file(path: Path) -> str:
    import hashlib

    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def git_short_sha(repo_dir: Path = CORPAN_DIR) -> str:
    import subprocess

    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(repo_dir), capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"
