# Generated by Django 5.1.2 on 2025-09-27 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cor", "0003_translation_romanization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Narrator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cor.language"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "description_pack",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional pack whose entries form a translatable description for this pack.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="describes_packs",
                        to="cor.pack",
                    ),
                ),
                (
                    "narrator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packs",
                        to="cor.narrator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="narrator",
            name="description_pack",
            field=models.ForeignKey(
                blank=True,
                help_text="Pack whose entries describe this narrator. Blank title = internal use only.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="narrator_descriptions",
                to="cor.pack",
            ),
        ),
        migrations.CreateModel(
            name="PackEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packs",
                        to="cor.entry",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="cor.pack",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("pack", "order")},
            },
        ),
    ]
