# Generated by Django 5.1.2 on 2025-11-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cor", "0004_narrator_pack_narrator_description_pack_packentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="level",
            field=models.CharField(
                choices=[
                    ("A0", "A0"),
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                max_length=3,
            ),
        ),
    ]
