PHRASES = [
    # Pronouns & be/have basics
    ("I am here", ["everyday", "social"]),
    ("I am not here", ["everyday", "social"]),
    ("Are you there?", ["everyday", "social"]),
    ("You are there", ["everyday", "social"]),
    ("He is here", ["everyday", "social"]),
    ("Where is he?", ["everyday", "social"]),
    ("She is here", ["everyday", "social"]),
    ("She is not here", ["everyday", "social"]),
    ("It is here", ["everyday", "social"]),
    ("It is not here", ["everyday", "social"]),
    ("We are ready", ["everyday", "social"]),
    ("We are not ready", ["everyday", "social"]),
    ("Are you all ready?", ["everyday", "social"]),
    ("They are late", ["everyday", "social"]),
    ("They are on time", ["everyday", "social"]),
    ("This is mine", ["everyday", "social"]),
    ("That is yours", ["everyday", "social"]),
    ("These are ours", ["everyday", "social"]),
    ("Those are theirs", ["everyday", "social"]),
    ("Someone is outside", ["everyday", "housing"]),
    ("No one is home", ["housing", "everyday"]),
    ("Who is there?", ["everyday", "social"]),
    ("Whose bag is this?", ["everyday", "travel", "social"]),
    ("Which one is it?", ["everyday", "social"]),
    # Polarity / logic / connectors
    ("Yes please", ["social", "everyday"]),
    ("No thank you", ["social", "everyday"]),
    ("Maybe later", ["everyday", "numbers"]),
    ("That is correct", ["everyday", "social"]),
    ("That is wrong", ["everyday", "social"]),
    ("That is enough", ["everyday", "social"]),
    ("Too much sugar", ["everyday", "health"]),
    ("Too little time", ["everyday", "numbers"]),
    ("Same as this", ["everyday", "social"]),
    ("Different from this", ["everyday", "social"]),
    ("Because I am new", ["everyday", "social"]),
    ("Because it is late", ["everyday", "numbers"]),
    ("Because it is closed", ["everyday", "business"]),
    ("Because I feel sick", ["health", "everyday"]),
    ("Tea or coffee?", ["everyday", "social"]),
    ("This and that", ["everyday", "social"]),
    # Names & identity
    ("What is your name?", ["social", "everyday"]),
    ("My name is Sam", ["social", "everyday"]),
    ("Your full name please", ["social", "everyday"]),
    ("First name please", ["social", "everyday"]),
    ("Last name please", ["social", "everyday"]),
    ("This is my family", ["social", "everyday"]),
    ("He is my friend", ["social", "everyday"]),
    ("She is my friend", ["social", "everyday"]),
    ("I am a teacher", ["education", "social"]),
    ("I am a student", ["education", "social"]),
    ("I am a doctor", ["health", "social"]),
    ("I am a worker", ["business", "social"]),
    ("She is my boss", ["business", "social"]),
    ("My colleague is here", ["business", "social", "everyday"]),
    ("I am a guest", ["travel", "social"]),
    ("You are the host", ["social", "everyday"]),
    # People nouns simple
    ("He is a man", ["social", "everyday"]),
    ("She is a woman", ["social", "everyday"]),
    ("The child is sleeping", ["social", "everyday"]),
    ("We are a group", ["social", "everyday"]),
    ("Many people here", ["social", "everyday"]),
    ("A few people here", ["social", "everyday"]),
    # Core questions: who/what/when/where/why/how
    ("Who are you?", ["social", "everyday"]),
    ("What is this?", ["everyday", "social"]),
    ("What is that?", ["everyday", "social"]),
    ("When do you open?", ["everyday", "business"]),
    ("When do you close?", ["everyday", "business"]),
    ("Where are you?", ["everyday", "social"]),
    ("Where is the bathroom?", ["everyday", "travel", "housing"]),
    ("Why is it closed?", ["everyday", "business"]),
    ("How do I pay?", ["everyday", "business"]),
    ("How much is this?", ["everyday", "business"]),
    ("How many tickets?", ["travel", "numbers", "everyday"]),
    ("How long is it?", ["everyday", "numbers"]),
    ("How far is it?", ["travel", "numbers"]),
    ("How old are you?", ["social", "numbers"]),
    ("How often is it?", ["everyday", "numbers"]),
    ("What time is it?", ["numbers", "everyday"]),
    ("Which bus is this?", ["travel", "numbers"]),
    # Time basics (varied)
    ("Right now", ["numbers", "everyday"]),
    ("Not right now", ["numbers", "everyday"]),
    ("Later today", ["numbers", "everyday"]),
    ("Very soon", ["numbers", "everyday"]),
    ("Before noon", ["numbers", "everyday"]),
    ("After lunch", ["numbers", "everyday"]),
    ("Early morning", ["numbers", "everyday"]),
    ("Late night", ["numbers", "everyday"]),
    ("In a moment", ["numbers", "everyday"]),
    ("In ten minutes", ["numbers", "everyday"]),
    ("In one hour", ["numbers", "everyday"]),
    ("All day today", ["numbers", "everyday"]),
    ("Every morning", ["numbers", "everyday"]),
    ("Every afternoon", ["numbers", "everyday"]),
    ("Every evening", ["numbers", "everyday"]),
    ("Next Wednesday", ["numbers", "everyday"]),
    ("Last year", ["numbers", "everyday"]),
    ("This year", ["numbers", "everyday"]),
    ("This Friday night", ["numbers", "everyday"]),
    ("Next Saturday morning", ["numbers", "everyday"]),
    ("Last Sunday evening", ["numbers", "everyday"]),
    ("Next week", ["numbers", "everyday"]),
    ("Last month", ["numbers", "everyday"]),
    ("This month", ["numbers", "everyday"]),
    ("This weekend", ["numbers", "everyday"]),
    ("Today only", ["numbers", "everyday"]),
    ("Tomorrow morning", ["numbers", "everyday"]),
    ("Yesterday afternoon", ["numbers", "everyday"]),
    # Numbers in use (0–20, tens, 100, 1000)
    ("Zero sugar please", ["numbers", "everyday"]),
    ("One ticket please", ["travel", "numbers", "everyday"]),
    ("Two waters please", ["everyday", "numbers"]),
    ("Three years more", ["numbers", "everyday"]),
    ("Only four left", ["everyday", "numbers"]),
    ("Five minutes left", ["numbers", "everyday"]),
    ("Six people here", ["numbers", "social"]),
    ("Seven days total", ["numbers", "everyday"]),
    ("Eight o'clock now", ["numbers", "everyday"]),
    ("Nine bags only", ["everyday", "numbers"]),
    ("Ten rooms available", ["housing", "numbers"]),
    ("Eleven seats free", ["travel", "numbers"]),
    ("Twelve months total", ["numbers", "everyday"]),
    ("Thirteen stops ahead", ["travel", "numbers"]),
    ("Fourteen students today", ["education", "numbers"]),
    ("Fifteen minutes late", ["numbers", "everyday"]),
    ("Sixteen floors up", ["housing", "numbers"]),
    ("Seventeen miles away", ["travel", "numbers"]),
    ("Eighteen dollars total", ["everyday", "numbers"]),
    ("Nineteen questions left", ["education", "numbers"]),
    ("Twenty minutes please", ["numbers", "everyday"]),
    ("Thirty minutes max", ["numbers", "everyday"]),
    ("Forty items only", ["everyday", "numbers"]),
    ("Fifty percent off", ["everyday", "business"]),
    ("Sixty pages total", ["education", "numbers"]),
    ("Seventy years old", ["social", "numbers"]),
    ("Eighty steps more", ["everyday", "numbers"]),
    ("Ninety days left", ["numbers", "everyday"]),
    ("One hundred people", ["social", "numbers"]),
    ("One thousand dollars", ["everyday", "numbers"]),
    # Place & direction
    ("Come here please", ["everyday", "social"]),
    ("Go there please", ["everyday", "travel"]),
    ("Very near here", ["everyday", "travel"]),
    ("Very far away", ["travel", "everyday"]),
    ("Turn left here", ["travel", "everyday"]),
    ("Turn right here", ["travel", "everyday"]),
    ("Go straight ahead", ["travel", "everyday"]),
    ("Go upstairs please", ["housing", "everyday"]),
    ("Go downstairs please", ["housing", "everyday"]),
    ("Inside the house", ["housing", "everyday"]),
    ("Outside the house", ["housing", "everyday"]),
    ("I am at home", ["housing", "everyday"]),
    ("I am at work", ["business", "everyday"]),
    ("I am at school", ["education", "everyday"]),
    ("At the hotel", ["travel", "housing"]),
    ("The restaurant is near", ["everyday", "travel", "business"]),
    ("The shop is open", ["everyday", "business"]),
    ("The bathroom is there", ["everyday", "housing"]),
    ("Across the street", ["travel", "everyday"]),
    ("In the city", ["travel", "everyday"]),
    ("In this country", ["travel", "everyday"]),
    ("In the world", ["travel", "everyday"]),
    ("By the window", ["housing", "everyday"]),
    ("At the corner", ["travel", "everyday"]),
    ("On the left side", ["travel", "everyday"]),
    ("On the right side", ["travel", "everyday"]),
    ("Go back please", ["travel", "everyday"]),
    ("Stop here please", ["travel", "everyday"]),
    # Objects & small actions
    ("Where is my phone?", ["technology", "everyday"]),
    ("My computer is slow", ["technology", "everyday"]),
    ("I lost my bag", ["travel", "everyday"]),
    ("I lost my wallet", ["travel", "everyday"]),
    ("This is my passport", ["travel", "civic"]),
    ("I need a ticket", ["travel", "everyday"]),
    ("Pay by card", ["everyday", "business", "technology"]),
    ("I have cash", ["everyday", "business"]),
    ("I need the key", ["housing", "travel"]),
    ("Open the door", ["housing", "everyday"]),
    ("Close the door", ["housing", "everyday"]),
    ("Open the window", ["housing", "everyday"]),
    ("Close the window", ["housing", "everyday"]),
    ("On the table", ["everyday", "housing"]),
    ("Under the table", ["everyday", "housing"]),
    ("On the chair", ["everyday", "housing"]),
    ("On the bed", ["housing", "everyday"]),
    ("Drive the car", ["travel", "everyday"]),
    ("Take the bus", ["travel", "everyday"]),
    ("Take the train", ["travel", "everyday"]),
    ("Take the airplane", ["travel"]),
    ("I need paper", ["everyday", "education"]),
    ("I need a pen", ["everyday", "education"]),
    ("I read a book", ["education", "culture", "everyday"]),
    ("Charge my phone", ["technology", "everyday"]),
    ("Free charger please", ["technology", "everyday"]),
    # Food & drink
    ("A cup of water", ["everyday", "health"]),
    ("A bottle of water", ["everyday", "health"]),
    ("Tap water please", ["everyday", "health"]),
    ("I need water", ["everyday", "health"]),
    ("I need food", ["everyday", "health"]),
    ("Fresh fruit please", ["everyday", "health"]),
    ("I want coffee", ["everyday", "social"]),
    ("I want tea", ["everyday", "social"]),
    ("No sugar please", ["everyday", "health"]),
    ("A little sugar", ["everyday", "health"]),
    ("No spicy please", ["everyday", "health"]),
    ("A little spicy", ["everyday", "health"]),
    ("No plastic bag", ["everyday", "environment"]),
    ("A paper bag", ["everyday", "environment"]),
    ("Enjoy your meal", ["social", "everyday"]),
    # Shopping & restaurant
    ("Menu please", ["everyday", "business"]),
    ("Bill please", ["everyday", "business"]),
    ("One more please", ["everyday", "business"]),
    ("One moment please", ["everyday", "social"]),
    ("Table for two", ["everyday", "social"]),
    ("Do you have wifi?", ["technology", "travel", "everyday"]),
    ("What is the password?", ["technology", "everyday"]),
    ("Do you take card?", ["everyday", "business"]),
    ("Card or cash?", ["everyday", "business"]),
    ("Can I pay later?", ["everyday", "business"]),
    ("I need a receipt", ["everyday", "business"]),
    ("I am just looking", ["everyday", "business"]),
    ("Can I try this?", ["everyday", "business"]),
    ("I will take it", ["everyday", "business"]),
    ("Do you have this?", ["everyday", "business"]),
    ("In a larger size", ["everyday", "business"]),
    ("In a smaller size", ["everyday", "business"]),
    ("In another color", ["everyday", "business"]),
    # Quality & states
    ("The light is on", ["housing", "everyday"]),
    ("The light is off", ["housing", "everyday"]),
    ("This is good", ["everyday", "social"]),
    ("This is bad", ["everyday", "social"]),
    ("Too big for me", ["everyday", "business"]),
    ("Too small for me", ["everyday", "business"]),
    ("The line is short", ["everyday", "business"]),
    ("The wait is long", ["everyday", "business"]),
    ("This is new", ["everyday", "business"]),
    ("That is old", ["everyday", "business"]),
    ("Very cheap here", ["everyday", "business"]),
    ("Very expensive here", ["everyday", "business"]),
    ("The bus is fast", ["travel", "everyday"]),
    ("The wifi is slow", ["technology", "everyday"]),
    ("I am busy now", ["business", "everyday"]),
    ("I have free time", ["everyday", "social"]),
    ("The store is open", ["everyday", "business"]),
    ("The store is closed", ["everyday", "business"]),
    ("The room is clean", ["housing", "everyday"]),
    ("The room is dirty", ["housing", "everyday"]),
    ("The music is loud", ["culture", "social", "everyday"]),
    ("The room is quiet", ["housing", "everyday"]),
    ("This is easy", ["everyday", "education"]),
    ("This is difficult", ["everyday", "education"]),
    ("The soup is hot", ["everyday", "health"]),
    ("The water is cold", ["everyday", "health"]),
    ("The view is beautiful", ["travel", "culture"]),
    ("This looks ugly", ["everyday", "social"]),
    ("This is interesting", ["everyday", "education"]),
    ("That is boring", ["everyday", "education"]),
    ("This is important", ["everyday", "business"]),
    ("That is possible", ["everyday", "social"]),
    # Ability, desire, knowledge
    ("I can help", ["everyday", "social"]),
    ("Can you help?", ["everyday", "social"]),
    ("Please help me", ["everyday", "social"]),
    ("I want this", ["everyday", "business"]),
    ("I need that", ["everyday", "business"]),
    ("I like this", ["everyday", "social"]),
    ("I do not like this", ["everyday", "social"]),
    ("I love this", ["everyday", "social"]),
    ("I live here", ["housing", "social"]),
    ("I work here", ["business", "social"]),
    ("I study here", ["education", "social"]),
    ("I speak English", ["social", "education"]),
    ("Do you understand?", ["everyday", "education"]),
    ("I understand now", ["everyday", "education"]),
    ("I do not understand", ["everyday", "education"]),
    ("I know this", ["everyday", "education"]),
    ("I am learning", ["education", "everyday"]),
    ("I teach English", ["education", "social"]),
    ("I see you", ["social", "everyday"]),
    ("I hear you", ["social", "everyday"]),
    ("Please listen carefully", ["education", "everyday"]),
    # Simple future / intent
    ("I will eat", ["everyday", "health"]),
    ("I will drink", ["everyday", "health"]),
    ("I will buy this", ["everyday", "business"]),
    ("I will sell this", ["business", "everyday"]),
    ("I will pay cash", ["everyday", "business"]),
    ("Please give me that", ["everyday", "social"]),
    ("Please take this", ["everyday", "social"]),
    ("Please put it here", ["everyday", "social"]),
    ("I will get it", ["everyday", "business"]),
    ("Help me find it", ["everyday", "social"]),
    ("I lost it", ["everyday", "travel"]),
    ("I will call you", ["everyday", "technology"]),
    ("Please wait here", ["everyday", "social"]),
    ("Please show me", ["everyday", "education"]),
    ("I will try", ["everyday", "education"]),
    ("Please stop here", ["travel", "everyday"]),
    ("Let us start", ["everyday", "education"]),
    ("Please walk slowly", ["everyday", "health"]),
    ("I will run", ["everyday", "health"]),
    ("Please sit down", ["everyday", "social"]),
    ("Please stand up", ["everyday", "social"]),
    ("We will travel", ["travel", "everyday"]),
    # Introductions & origins
    ("Where are you from?", ["social", "travel"]),
    ("I am from here", ["social", "everyday"]),
    ("I am not from here", ["social", "travel"]),
    ("I live near here", ["housing", "everyday"]),
    ("I live far away", ["travel", "social"]),
    # Transport & navigation
    ("Where is the bus stop?", ["travel", "everyday"]),
    ("Where is the station?", ["travel", "everyday"]),
    ("Where is the airport?", ["travel", "everyday"]),
    ("Please call a taxi", ["travel", "everyday"]),
    ("Which platform is it?", ["travel", "numbers"]),
    ("Which bus is this?", ["travel", "numbers"]),
    ("The train station please", ["travel", "everyday"]),
    ("The gate number please", ["travel", "numbers"]),
    ("Ticket counter please", ["travel", "everyday"]),
    ("Platform number please", ["travel", "numbers"]),
    ("Seat number please", ["travel", "numbers"]),
    ("Now boarding soon", ["travel", "everyday"]),
    ("One transfer only", ["travel", "everyday"]),
    ("Departure time please", ["travel", "numbers"]),
    ("Arrival time please", ["travel", "numbers"]),
    ("Show me the map", ["travel", "everyday"]),
    ("Show me the way", ["travel", "everyday"]),
    ("Drop me here please", ["travel", "everyday"]),
    # Clarifications
    ("Can you repeat that?", ["everyday", "education"]),
    ("Speak slowly please", ["everyday", "education"]),
    ("One more time", ["everyday", "education"]),
    ("What does this mean?", ["everyday", "education"]),
    ("How do you say this?", ["education", "everyday"]),
    ("Spell it please", ["education", "everyday"]),
    # Social expressions (greetings / goodwill)
    ("Hello", ["social", "everyday"]),
    ("Hi there", ["social", "everyday"]),
    ("Welcome!", ["social", "everyday"]),
    ("You are welcome", ["social", "everyday"]),
    ("Goodbye for now", ["social", "everyday"]),
    ("See you later", ["social", "everyday"]),
    ("See you soon", ["social", "everyday"]),
    ("Good morning", ["social", "everyday"]),
    ("Good afternoon", ["social", "everyday"]),
    ("Good evening", ["social", "everyday"]),
    ("Good night", ["social", "everyday"]),
    ("Nice to meet you", ["social", "everyday"]),
    ("Pleasure to meet you", ["social", "everyday"]),
    ("Well done team", ["social", "business"]),
    ("Best wishes", ["social", "everyday"]),
    ("Get well soon", ["social", "health"]),
    ("Safe travels", ["travel", "social"]),
    ("Sleep well", ["social", "everyday"]),
    ("Take care please", ["social", "everyday"]),
    ("Have a nice day", ["social", "everyday"]),
    ("Have a safe trip", ["travel", "social"]),
    ("Welcome back", ["social", "everyday"]),
    ("Long time no see", ["social", "everyday"]),
    ("Cheers!", ["culture", "social"]),
    ("To your health!", ["culture", "health"]),
    ("Congratulations to you", ["social", "everyday"]),
    ("Happy birthday", ["culture", "social"]),
    # Politeness & apologies
    ("Thank you", ["social", "everyday"]),
    ("Thank you very much", ["social", "everyday"]),
    ("Many thanks", ["social", "everyday"]),
    ("Please", ["social", "everyday"]),
    ("Excuse me please", ["social", "everyday"]),
    ("I am sorry", ["social", "everyday"]),
    ("No problem", ["social", "everyday"]),
    ("My mistake", ["social", "everyday"]),
    ("All good now", ["social", "everyday"]),
    # Functional particles / adverbs
    ("Here you go", ["everyday", "social"]),
    ("This one only", ["everyday", "business"]),
    ("That one only", ["everyday", "business"]),
    ("Like this one", ["everyday", "business"]),
    ("Not the same", ["everyday", "education"]),
    ("Same as before", ["everyday", "education"]),
    ("Different from this", ["everyday", "education"]),
    ("Again please", ["everyday", "education"]),
    ("Together with me", ["social", "everyday"]),
    ("Alone for now", ["everyday", "social"]),
    ("Already did that", ["everyday", "education"]),
    ("Not yet done", ["everyday", "education"]),
    ("Maybe later today", ["numbers", "everyday"]),
    ("Very good then", ["everyday", "social"]),
    ("A little bit", ["everyday", "education"]),
    ("A little more", ["everyday", "education"]),
    ("Much less please", ["everyday", "business"]),
    ("More of this", ["everyday", "business"]),
    ("Less of that", ["everyday", "business"]),
    ("Also this one", ["everyday", "business"]),
    ("Only this one", ["everyday", "business"]),
    ("First time here", ["everyday", "education"]),
    ("Last one left", ["everyday", "business"]),
    ("Right over there", ["everyday", "travel"]),
    # Health & feelings
    ("I am very hungry", ["health", "everyday"]),
    ("I am very thirsty", ["health", "everyday"]),
    ("I am very tired", ["health", "everyday"]),
    ("I feel sick", ["health", "everyday"]),
    ("I feel cold", ["health", "environment"]),
    ("I feel hot", ["health", "environment"]),
    ("I feel nervous", ["health", "everyday"]),
    ("I feel better now", ["health", "everyday"]),
    # Work & study micro
    ("I have a meeting", ["business", "everyday"]),
    ("I am on a call", ["business", "technology"]),
    ("I have a class", ["education", "everyday"]),
    ("Homework is easy", ["education", "everyday"]),
    ("Homework is hard", ["education", "everyday"]),
    # Contact & info
    ("What is the address?", ["civic", "travel"]),
    ("What is your number?", ["technology", "social"]),
    ("What is your email?", ["technology", "social"]),
    ("Write it here please", ["everyday", "education"]),
    # Weather small talk
    ("It is very hot", ["environment", "everyday"]),
    ("It is very cold", ["environment", "everyday"]),
    ("It is raining now", ["environment", "everyday"]),
    ("It is sunny today", ["environment", "everyday"]),
    ("It is windy today", ["environment", "everyday"]),
    # Simple comparisons
    ("This is better", ["everyday", "education"]),
    ("That is worse", ["everyday", "education"]),
    ("This is cheaper", ["everyday", "business"]),
    ("That is slower", ["everyday", "travel"]),
    ("This is faster", ["everyday", "travel"]),
    # Location confirmations
    ("Is this the place?", ["travel", "everyday"]),
    ("Is that the line?", ["travel", "everyday"]),
    ("Is this my seat?", ["travel", "everyday"]),
    ("Is that my stop?", ["travel", "everyday"]),
    # App / service basics
    ("Do you have an app?", ["technology", "everyday"]),
    ("Free wifi here?", ["technology", "travel", "everyday"]),
    ("Weak signal here", ["technology", "everyday"]),
    ("Strong signal here", ["technology", "everyday"]),
    # Emergencies & safety
    ("Danger stay back", ["emergency", "civic"]),
    ("This is an emergency", ["emergency", "health"]),
    ("Help me please", ["emergency", "social"]),
    ("Call the police", ["emergency", "civic"]),
    ("Go to the hospital", ["health", "emergency"]),
    ("Call an ambulance", ["emergency", "health"]),
    ("I need medicine", ["health", "everyday"]),
    ("I have an allergy", ["health", "everyday"]),
    ("I have pain", ["health", "everyday"]),
    ("It really hurts", ["health", "everyday"]),
    ("I lost my passport", ["emergency", "travel", "civic"]),
    ("My bag was stolen", ["emergency", "travel", "civic"]),
    ("I lost my phone", ["emergency", "technology", "travel"]),
    ("I need clean water", ["everyday", "health"]),
    ("I need some food", ["everyday", "health"]),
    ("I need a doctor", ["health", "emergency"]),
    ("I feel unsafe", ["emergency", "everyday"]),
    ("Please stay with me", ["emergency", "social"]),
    ("Show me the exit", ["emergency", "travel"]),
    ("I need help now", ["emergency", "social"]),
]
