import games from "@/data/dynawalla-games.json";
import { artOf, hueClass } from "@/lib/dynawalla/art";
import { shapesOf, type Shape } from "@/lib/dynawalla/motifs";

/**
 * The Dynawalla catalogue, as the site sees it.
 *
 * `data/dynawalla-games.json` is generated by
 * `web/scripts/generate-dynawalla-games.js` from each game's own
 * `dynawalla/games/<game>/pack.json` — the same manifest the app packages and
 * ships. Every name, description and skill below is the pack's own words, not
 * marketing copy written about it. It regenerates on every build, so do not
 * edit the JSON or restate any of it as prose here.
 */
export interface DynawallaGame {
  readonly id: string;
  readonly slug: string;
  readonly name: string;
  readonly description: string;
  readonly version: string;
  readonly minAge: number | null;
  readonly skills: readonly string[];
  /** Whether `public/dynawalla/shots/<slug>.webp` exists. Detected at build. */
  readonly hasShot: boolean;
}

export const DYNAWALLA_GAMES = games as unknown as DynawallaGame[];

export function getGame(slug: string): DynawallaGame | undefined {
  return DYNAWALLA_GAMES.find((g) => g.slug === slug);
}

const NUMBER_WORDS = [
  "zero", "one", "two", "three", "four", "five", "six", "seven", "eight",
  "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen",
  "sixteen", "seventeen", "eighteen", "nineteen", "twenty",
];

/**
 * How many games there are, spelled out, for use in prose.
 *
 * Never write the number in copy. The App Store description said "Twenty-seven
 * games" for weeks after the catalogue had settled at twenty-five, because a
 * count written by hand has nothing that fails when it stops being true. This
 * reads the generated catalogue, so it cannot drift from it.
 */
export function gameCountWord(): string {
  const n = DYNAWALLA_GAMES.length;
  if (n <= 20) return NUMBER_WORDS[n];
  if (n < 100) {
    const tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty",
      "seventy", "eighty", "ninety"][Math.floor(n / 10)];
    const ones = n % 10;
    return ones === 0 ? tens : `${tens}-${NUMBER_WORDS[ones]}`;
  }
  return String(n);
}

/** The same, with an initial capital, for the start of a sentence or heading. */
export function gameCountWordTitle(): string {
  const word = gameCountWord();
  return word.charAt(0).toUpperCase() + word.slice(1);
}

/* ------------------------------------------------------------------ *
 * Subjects
 *
 * Derived from the skill id, exactly as the app derives them: the second
 * segment of `dw.add.column.add-no-regroup` is the subject. There is
 * deliberately no per-game table — a game whose subject this build has never
 * heard of keeps every other subject it matches rather than vanishing.
 * ------------------------------------------------------------------ */

export const DOMAIN_IDS = ["ns", "add", "mul", "div", "frac", "alg"] as const;
export type DomainId = (typeof DOMAIN_IDS)[number];

export const DOMAIN_NAMES: Record<DomainId, string> = {
  ns: "Number sense",
  add: "Addition & subtraction",
  mul: "Multiplication",
  div: "Division",
  frac: "Fractions",
  alg: "Equality & algebra",
};

const isDomainId = (value: string): value is DomainId =>
  (DOMAIN_IDS as readonly string[]).includes(value);

export function domainOfSkill(skill: string): DomainId | null {
  const parts = skill.split(".");
  if (parts.length < 2 || parts[0] !== "dw") return null;
  const second = parts[1] ?? "";
  return isDomainId(second) ? second : null;
}

export function domainsOf(skills: readonly string[]): readonly DomainId[] {
  const found = new Set<DomainId>();
  for (const skill of skills) {
    const domain = domainOfSkill(skill);
    if (domain !== null) found.add(domain);
  }
  return DOMAIN_IDS.filter((d) => found.has(d));
}

/* ------------------------------------------------------------------ *
 * Skill names
 *
 * The curriculum's own `title` and `learnerGoal` are i18n KEYS
 * (`dw.skill.add.facts.add-within-ten.title`) and nothing in the repository
 * resolves them yet, so there is no authored English string to read. What
 * follows is the skill id written out in English and nothing more — every
 * entry is derivable from its id, so this is a rendering, not a description of
 * what the skill teaches. Do not add pedagogy here; if the curriculum ever
 * ships a string catalogue, delete this table and read that instead.
 * ------------------------------------------------------------------ */
const SKILL_LABELS: Record<string, string> = {
  "dw.ns.compare.whole-numbers": "Comparing whole numbers",

  "dw.add.facts.add-within-ten": "Addition facts within ten",
  "dw.add.facts.subtract-within-ten": "Subtraction facts within ten",
  "dw.add.facts.add-across-ten": "Addition facts across ten",
  "dw.add.facts.subtract-across-ten": "Subtraction facts across ten",
  "dw.add.column.add-no-regroup": "Column addition without regrouping",
  "dw.add.column.subtract-no-regroup": "Column subtraction without regrouping",
  "dw.add.regroup.add-multidigit": "Multi-digit addition with regrouping",
  "dw.add.regroup.add-short-addend": "Adding a short addend with regrouping",
  "dw.add.regroup.subtract-multidigit": "Multi-digit subtraction with regrouping",
  "dw.add.regroup.subtract-short-subtrahend":
    "Subtracting a short subtrahend with regrouping",
  "dw.add.regroup.subtract-across-zero": "Subtracting across zero",
  "dw.add.regroup.subtract-tenths": "Subtracting tenths with regrouping",

  "dw.mul.facts.tables-within-five": "Times tables within five",
  "dw.mul.facts.tables-to-twelve": "Times tables to twelve",
  "dw.mul.scale.times-power-of-ten": "Multiplying by a power of ten",
  "dw.mul.multidigit.times-one-digit": "Multiplying by a one-digit number",
  "dw.mul.multidigit.times-two-digit": "Multiplying by a two-digit number",
  "dw.mul.multidigit.long-multiplication": "Long multiplication",

  "dw.div.facts.division-facts": "Division facts",
  "dw.div.whole.divide-exact": "Division without a remainder",
  "dw.div.whole.zero-in-the-quotient": "Zero in the quotient",

  "dw.frac.compare.same-numerator": "Comparing fractions with the same numerator",
  "dw.frac.compare.unlike-fractions": "Comparing unlike fractions",
  "dw.frac.equivalence.build-equivalent": "Building equivalent fractions",
  "dw.frac.equivalence.lowest-terms": "Lowest terms",
  "dw.frac.arith.add-like-denominators": "Adding fractions with like denominators",
  "dw.frac.arith.add-unlike-denominators":
    "Adding fractions with unlike denominators",
  "dw.frac.arith.subtract-fractions": "Subtracting fractions",
  "dw.frac.arith.multiply-by-a-whole": "Multiplying a fraction by a whole number",
  "dw.frac.arith.multiply-fractions": "Multiplying fractions",

  "dw.alg.equality.balance-meaning": "The meaning of the equals sign",
  "dw.alg.equality.missing-addend": "Finding a missing addend",
  "dw.alg.equality.missing-subtrahend": "Finding a missing subtrahend",
  "dw.alg.equality.unknown-minuend": "Finding an unknown minuend",
  "dw.alg.equality.missing-factor": "Finding a missing factor",
};

/**
 * A skill's name. A skill this build has never heard of falls back to its own
 * last segment rather than disappearing — the same posture the app takes with
 * an unknown subject.
 */
export function skillLabel(skill: string): string {
  const known = SKILL_LABELS[skill];
  if (known) return known;
  const last = skill.split(".").pop() ?? skill;
  const words = last.replace(/-/g, " ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

/* ------------------------------------------------------------------ *
 * Screenshots
 *
 * Captured from the real build in the iOS Simulator. `hasShot` is DETECTED by
 * the generator from the presence of `public/dynawalla/shots/<slug>.webp`, not
 * declared, so adding or deleting a file is the whole change. A game without
 * one shows its key art alone rather than a placeholder or another game\'s
 * picture.
 * ------------------------------------------------------------------ */
export function shotFor(slug: string): string | null {
  const game = DYNAWALLA_GAMES.find((g) => g.slug === slug);
  return game?.hasShot ? `/dynawalla/shots/${slug}.webp` : null;
}

/**
 * The absolute image to show when a page is shared.
 *
 * Next replaces a parent's `openGraph` wholesale rather than merging it, so a
 * page that sets `openGraph` without `images` ends up with NO og:image — which
 * is what every game page shipped with. This always resolves: the game's own
 * screenshot where one was captured, and the catalogue otherwise.
 */
export function ogImageFor(slug: string): string {
  const shot = shotFor(slug);
  return `https://encorpora.io${shot ?? "/dynawalla/shots/catalog.webp"}`;
}

/* ------------------------------------------------------------------ *
 * Key art
 * ------------------------------------------------------------------ */

export interface GameArt {
  readonly hueClassName: string;
  readonly shapes: readonly Shape[];
}

/**
 * The same picture the app draws, computed the same way.
 *
 * `artOf` hashes the pack id into a hue and a motif; `shapesOf` turns the
 * motif into geometry through a seeded PRNG. Both are pure, so the card on
 * this page and the card on a phone are the same drawing.
 */
export function artFor(packId: string): GameArt {
  const spec = artOf(packId);
  return {
    hueClassName: hueClass(spec.hue),
    shapes: shapesOf(spec.motif, rngFor(spec.seed)),
  };
}

function rngFor(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
