# Generated by Django 5.1.2 on 2025-03-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hexagram",
            name="english_name",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
