# Generated by Django 5.1.2 on 2025-03-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0002_hexagram_english_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hexagram",
            name="english_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
