# Generated by Django 5.1.2 on 2025-03-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0003_alter_hexagram_english_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="hexagram",
            name="judgment_pinyin",
            field=models.TextField(blank=True, help_text="Judgment in Pinyin"),
        ),
        migrations.AddField(
            model_name="line",
            name="text_pinyin",
            field=models.TextField(blank=True, help_text="Pinyin for the line"),
        ),
    ]
