# Generated by Django 5.1.2 on 2025-03-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0004_hexagram_judgment_pinyin_line_text_pinyin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="line",
            options={"ordering": ["hexagram", "line_number"]},
        ),
        migrations.RenameField(
            model_name="hexagram",
            old_name="chinese_name",
            new_name="name_zh",
        ),
    ]
