# Generated by Django 5.1.2 on 2025-03-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0005_alter_line_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hexagram",
            old_name="english_name",
            new_name="name_en",
        ),
    ]
