# Generated by Django 5.1.2 on 2025-03-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0006_rename_english_name_hexagram_name_en"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hexagram",
            options={"ordering": ["number"]},
        ),
    ]
