# Generated by Django 5.1.2 on 2025-03-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0007_alter_hexagram_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=1, unique=True)),
                ("pinyin", models.CharField(blank=True, max_length=10)),
                (
                    "etymology",
                    models.TextField(
                        blank=True, help_text="Full historical breakdown in English"
                    ),
                ),
            ],
            options={
                "ordering": ["character"],
            },
        ),
    ]
