# Generated by Django 5.1.2 on 2025-03-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0009_phrase_translation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hexagram",
            old_name="pinyin",
            new_name="name_pinyin",
        ),
    ]
