# Generated by Django 5.1.2 on 2025-03-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0010_rename_pinyin_hexagram_name_pinyin"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="style",
            field=models.CharField(
                choices=[("ancient", "Ancient")], default="ancient", max_length=10
            ),
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("phrase", "language", "style")},
        ),
    ]
