# Generated by Django 5.1.2 on 2025-04-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0011_translation_style_alter_translation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="attribution",
            field=models.CharField(
                blank=True, help_text="Attribution for the translation", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="style",
            field=models.CharField(
                choices=[("ancient", "Ancient"), ("wilhelm", "Wilhelm")],
                default="ancient",
                max_length=10,
            ),
        ),
    ]
