# Generated by Django 5.1.2 on 2025-04-03 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0012_translation_attribution_alter_translation_style"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("phrase", "language", "style", "attribution")},
        ),
    ]
