# Generated by Django 5.1.2 on 2025-04-03 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0013_alter_translation_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="changing_hexagram",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="primary_hexagram",
        ),
        migrations.AlterField(
            model_name="consultation",
            name="compact_representation",
            field=models.CharField(
                help_text="Compact representation of the consultation, e.g., 678967",
                max_length=6,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ConsultationInterpretation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Interpretation text for the consultation"
                    ),
                ),
                (
                    "attribution",
                    models.CharField(
                        blank=True,
                        help_text="Attribution for the interpretation",
                        max_length=255,
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretations",
                        to="iching.consultation",
                    ),
                ),
            ],
        ),
    ]
