# Generated by Django 5.1.2 on 2025-04-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0014_remove_consultation_changing_hexagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hexagram",
            name="name_es",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
