# Generated by Django 5.1.2 on 2025-04-13 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0015_hexagram_name_es"),
    ]

    operations = [
        migrations.CreateModel(
            name="Explanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                ("text", models.TextField()),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanations",
                        to="iching.phrase",
                    ),
                ),
            ],
            options={
                "ordering": ["phrase", "language"],
            },
        ),
    ]
