# Generated by Django 5.1.2 on 2025-04-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iching", "0016_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="explanation",
            name="attribution",
            field=models.CharField(
                blank=True, help_text="Attribution for the explanation", max_length=255
            ),
        ),
        migrations.AlterUniqueTogether(
            name="explanation",
            unique_together={("phrase", "language", "attribution")},
        ),
    ]
