# Generated by Django 5.1.2 on 2025-04-27 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="history_cou_name_32dc26_idx",
        ),
        migrations.AddField(
            model_name="theme",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="themes",
                to="history.course",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="theme",
            unique_together={("name", "course")},
        ),
    ]
