# Generated by Django 5.1.2 on 2025-04-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_theme_remove_course_history_cou_name_32dc26_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Who",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Birth date", null=True),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Death date", null=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whos",
                        to="history.course",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "course")},
            },
        ),
    ]
