use std::{env, fs, path::PathBuf};

#[path = "build_support/client_id.rs"]
mod client_id;

#[path = "build_support/android_bridge.rs"]
mod android_bridge;

fn main() {
    free2z_client_id();
    println!("cargo:rerun-if-changed=android/oauth-intent.xml");
    // Do not trust NDK detection alone: our NDK 28 diagnostic still produced
    // 4 KiB ELF LOAD segments without an explicit application link policy.
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("android") {
        println!("cargo:rustc-link-arg=-Wl,-z,max-page-size=16384");
        println!("cargo:rustc-link-arg=-Wl,-z,common-page-size=16384");
        tauri_plugin::mobile::update_android_manifest(
            "AHA FREE2Z AUTH",
            "activity",
            include_str!("android/oauth-intent.xml").to_owned(),
        )
        .expect("AHA OAuth callback could not be registered");
        native_bridge();
    }
    tauri_build::build()
}

/// Bakes the public Free2Z client id into the crate as `AHA_FREE2Z_CLIENT_ID_RESOLVED` (empty when
/// unconfigured). The env var alone does not survive `tauri ios build`; see `build_support/client_id.rs`.
fn free2z_client_id() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let file = manifest.join(client_id::FILE);
    println!("cargo:rerun-if-env-changed={}", client_id::ENV_VAR);
    // The directory always exists (its .gitignore is tracked), so watching it never forces a rerun.
    println!(
        "cargo:rerun-if-changed={}",
        file.parent().expect("config directory").display()
    );
    let from_env = env::var(client_id::ENV_VAR).ok();
    let from_file = match fs::read_to_string(&file) {
        Ok(text) => Some(text),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => panic!("cannot read {}: {e}", file.display()),
    };
    let id = client_id::resolve(from_env.as_deref(), from_file.as_deref())
        .unwrap_or_else(|why| panic!("invalid Free2Z client id configuration: {why}"));
    if id.is_none() {
        println!(
            "cargo:warning=No Free2Z client id ({} or {}); this build has sign-in disabled",
            client_id::ENV_VAR,
            client_id::FILE
        );
    }
    println!(
        "cargo:rustc-env={}={}",
        client_id::RESOLVED_VAR,
        id.unwrap_or_default()
    );
}

/// The generated MainActivity gets a small native bridge with two parts.
///
/// System bars: the studio's light/dark theme follows the WebView's `prefers-color-scheme`, but
/// Android WebView does not always agree with the system night mode (a Samsung S26 on Android 16
/// reported light in night mode), and the template's one-shot `enableEdgeToEdge()` picks icons from
/// the system setting at launch and never again. So the frontend reports the scheme it renders, and
/// every change of it, and the icons follow that.
///
/// Keyboard: the keyboard overlays the page (adjustResize under edge-to-edge, with the IME inset kept
/// from the WebView), and its height is pushed to the page on every animation frame, so only the
/// answer dock moves, in step with it. Without this the system panned the window and the page's own
/// dock math moved the dock too: the answer bounced to mid-screen and the problem left the screen.
///
/// The Android project is regenerated by `tauri android init` (CI, every release), so this patches
/// it beside the manifest patch; it panics if the template drifts. A project patched by #868 (forced
/// dark icons) or #917 (the system-bars bridge alone) is restored first.
fn native_bridge() {
    println!("cargo:rerun-if-env-changed=TAURI_ANDROID_PROJECT_PATH");
    println!("cargo:rerun-if-env-changed=WRY_ANDROID_PACKAGE");
    let (Some(project), Ok(package)) = (
        env::var_os("TAURI_ANDROID_PROJECT_PATH"),
        env::var("WRY_ANDROID_PACKAGE"),
    ) else {
        return; // A plain `cargo build`/`check` for Android outside the Tauri CLI.
    };
    let mut path = PathBuf::from(project).join("app/src/main/java");
    path.extend(package.split('.'));
    path.push("MainActivity.kt");
    println!("cargo:rerun-if-changed={}", path.display());
    let source =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let patched = match android_bridge::patch_main_activity(&source) {
        Ok(Some(patched)) => patched,
        Ok(None) => return,
        Err(why) => panic!("{} {why}", path.display()),
    };
    let modified = fs::metadata(&path).and_then(|m| m.modified());
    fs::write(&path, patched).unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
    // Keep the template's timestamp so the watch above does not rerun this script (and rebuild
    // the crate) merely because the script itself rewrote the file.
    let restored = modified.and_then(|modified| {
        fs::File::options()
            .write(true)
            .open(&path)
            .and_then(|f| f.set_modified(modified))
    });
    if let Err(e) = restored {
        println!(
            "cargo:warning=patched {} but could not restore its timestamp ({e}); the next build reruns build.rs once",
            path.display()
        );
    }
}
