use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=AHA_FREE2Z_CLIENT_ID");
    println!("cargo:rerun-if-changed=android/oauth-intent.xml");
    // Do not trust NDK detection alone: our NDK 28 diagnostic still produced
    // 4 KiB ELF LOAD segments without an explicit application link policy.
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("android") {
        println!("cargo:rustc-link-arg=-Wl,-z,max-page-size=16384");
        println!("cargo:rustc-link-arg=-Wl,-z,common-page-size=16384");
        tauri_plugin::mobile::update_android_manifest(
            "AHA FREE2Z AUTH",
            "activity",
            include_str!("android/oauth-intent.xml").to_owned(),
        )
        .expect("AHA OAuth callback could not be registered");
        status_bar_follows_rendered_theme();
    }
    tauri_build::build()
}

const DEFAULT_EDGE_TO_EDGE: &str = "    enableEdgeToEdge()\n";
const LIGHT_STATUS_BAR: &str = "    enableEdgeToEdge(statusBarStyle = SystemBarStyle.light(Color.TRANSPARENT, Color.TRANSPARENT))\n";
const LIGHT_STATUS_BAR_IMPORTS: &str =
    "import android.graphics.Color\nimport androidx.activity.SystemBarStyle\n";
const ACTIVITY_CLASS: &str = "class MainActivity : TauriActivity() {\n";
const BRIDGE_MARKER: &str = "// AHA system-bars bridge";
const BRIDGE: &str = r#"  // AHA system-bars bridge (added by aha/aha-app/src-tauri/build.rs; src/ui/systemBars.ts calls it).
  override fun onWebViewCreate(webView: android.webkit.WebView) {
    webView.addJavascriptInterface(AhaSystemBars(this), "ahaSystemBars")
  }
"#;
const BRIDGE_CLASS: &str = r#"
/** Status-bar and navigation-bar icons contrast with the theme the WebView actually renders. */
private class AhaSystemBars(private val activity: android.app.Activity) {
  @android.webkit.JavascriptInterface
  fun setDark(dark: Boolean) {
    activity.runOnUiThread {
      val bars = androidx.core.view.WindowCompat.getInsetsController(activity.window, activity.window.decorView)
      bars.isAppearanceLightStatusBars = !dark
      bars.isAppearanceLightNavigationBars = !dark
    }
  }
}
"#;

/// The studio's light/dark theme follows the WebView's `prefers-color-scheme`, but Android WebView
/// does not always agree with the system night mode (a Samsung S26 on Android 16 reported light in
/// night mode), and the template's one-shot `enableEdgeToEdge()` picks icons from the system setting
/// at launch and never again. Either way the icons can end up white on the cream page. So the
/// generated MainActivity gets a tiny JavaScript bridge: the frontend reports the scheme it renders,
/// and every change of it, and the icons follow that. The Android project is regenerated by
/// `tauri android init` (CI, every release), so this patches it beside the manifest patch; it panics
/// if the template drifts. A project patched by #868 (forced dark icons) is restored first.
fn status_bar_follows_rendered_theme() {
    println!("cargo:rerun-if-env-changed=TAURI_ANDROID_PROJECT_PATH");
    println!("cargo:rerun-if-env-changed=WRY_ANDROID_PACKAGE");
    let (Some(project), Ok(package)) = (
        env::var_os("TAURI_ANDROID_PROJECT_PATH"),
        env::var("WRY_ANDROID_PACKAGE"),
    ) else {
        return; // A plain `cargo build`/`check` for Android outside the Tauri CLI.
    };
    let mut path = PathBuf::from(project).join("app/src/main/java");
    path.extend(package.split('.'));
    path.push("MainActivity.kt");
    println!("cargo:rerun-if-changed={}", path.display());
    let source =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    if source.contains(BRIDGE_MARKER) {
        return;
    }
    let source = source
        .replacen(LIGHT_STATUS_BAR, DEFAULT_EDGE_TO_EDGE, 1)
        .replacen(LIGHT_STATUS_BAR_IMPORTS, "", 1);
    assert!(
        source.matches(ACTIVITY_CLASS).count() == 1
            && source.matches(DEFAULT_EDGE_TO_EDGE).count() == 1
            && !source.contains("onWebViewCreate"),
        "{} no longer matches the Tauri template this build patches; update build.rs",
        path.display()
    );
    let patched =
        source.replacen(ACTIVITY_CLASS, &format!("{ACTIVITY_CLASS}{BRIDGE}\n"), 1) + BRIDGE_CLASS;
    let modified = fs::metadata(&path).and_then(|m| m.modified());
    fs::write(&path, patched).unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
    // Keep the template's timestamp so the watch above does not rerun this script (and rebuild
    // the crate) merely because the script itself rewrote the file.
    let restored = modified.and_then(|modified| {
        fs::File::options()
            .write(true)
            .open(&path)
            .and_then(|f| f.set_modified(modified))
    });
    if let Err(e) = restored {
        println!(
            "cargo:warning=patched {} but could not restore its timestamp ({e}); the next build reruns build.rs once",
            path.display()
        );
    }
}
