# Generated by Django 5.1.2 on 2025-04-22 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char",
                    models.CharField(
                        help_text="The single-character jamo, e.g. 'ㄱ', 'ㅏ'.",
                        max_length=1,
                        unique=True,
                    ),
                ),
                (
                    "unicode_codepoint",
                    models.CharField(
                        help_text="Unicode codepoint, e.g. 'U+1100'.", max_length=10
                    ),
                ),
                (
                    "jamo_type",
                    models.CharField(
                        choices=[("L", "Initial"), ("V", "Medial"), ("T", "Final")],
                        help_text="Type of jamo: Initial (L), Medial (V), or Final (T).",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jamo",
                "verbose_name_plural": "Jamo",
                "ordering": ["jamo_type", "unicode_codepoint"],
            },
        ),
        migrations.CreateModel(
            name="HangulSyllable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "syllable",
                    models.CharField(
                        help_text="The composed syllable character, e.g. '가'.",
                        max_length=1,
                        unique=True,
                    ),
                ),
                (
                    "codepoint",
                    models.CharField(
                        help_text="Unicode codepoint for the syllable, e.g. 'U+AC00'.",
                        max_length=10,
                    ),
                ),
                (
                    "final",
                    models.ForeignKey(
                        blank=True,
                        help_text="Final jamo component (optional).",
                        limit_choices_to={"jamo_type": "T"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_syllables",
                        to="kore.jamo",
                    ),
                ),
                (
                    "initial",
                    models.ForeignKey(
                        help_text="Initial jamo component.",
                        limit_choices_to={"jamo_type": "L"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initial_syllables",
                        to="kore.jamo",
                    ),
                ),
                (
                    "medial",
                    models.ForeignKey(
                        help_text="Medial jamo component.",
                        limit_choices_to={"jamo_type": "V"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medial_syllables",
                        to="kore.jamo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hangul Syllable",
                "verbose_name_plural": "Hangul Syllables",
                "ordering": ["codepoint"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_korean",
                    models.CharField(
                        help_text="The headword in Korean script.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "romanization",
                    models.CharField(
                        help_text="Revised Romanization of the word.", max_length=100
                    ),
                ),
                (
                    "pronunciation",
                    models.CharField(
                        blank=True,
                        help_text="Pronunciation guide (e.g. IPA).",
                        max_length=100,
                    ),
                ),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("N", "Noun"),
                            ("V", "Verb"),
                            ("ADJ", "Adjective"),
                            ("ADV", "Adverb"),
                            ("P", "Particle"),
                        ],
                        help_text="Part of speech.",
                        max_length=5,
                    ),
                ),
                (
                    "frequency_rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Frequency rank in a reference corpus (1 = most frequent).",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Word",
                "verbose_name_plural": "Words",
                "ordering": ["frequency_rank", "text_korean"],
                "indexes": [
                    models.Index(
                        fields=["text_korean"], name="kore_word_text_ko_b6d5f9_idx"
                    ),
                    models.Index(
                        fields=["frequency_rank"], name="kore_word_frequen_373913_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_korean",
                    models.TextField(help_text="Example sentence in Korean."),
                ),
                (
                    "text_english",
                    models.TextField(help_text="English translation of the sentence."),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Vocabulary words appearing in this sentence.",
                        related_name="sentences",
                        to="kore.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentence",
                "verbose_name_plural": "Sentences",
                "ordering": [models.OrderBy(models.F("id"))],
            },
        ),
        migrations.CreateModel(
            name="Definition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ko", "Korean")],
                        help_text="Definition language.",
                        max_length=2,
                    ),
                ),
                ("text", models.TextField(help_text="The definition text.")),
                (
                    "word",
                    models.ForeignKey(
                        help_text="The word this definition belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definitions",
                        to="kore.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Definition",
                "verbose_name_plural": "Definitions",
                "ordering": ["language"],
                "unique_together": {("word", "language", "text")},
            },
        ),
    ]
