# Generated by Django 5.1.2 on 2025-04-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="cefr_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                default="",
                help_text="CEFR level of the sentence.",
                max_length=2,
            ),
        ),
    ]
