# Generated by Django 5.1.2 on 2025-04-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="number",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
