# Generated by Django 5.1.2 on 2025-04-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrary", "0002_unit_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
