# Generated by Django 5.1.2 on 2025-05-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrary", "0003_course_summary_exercise_summary_lesson_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="markdown",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="markdown",
            field=models.TextField(blank=True),
        ),
    ]
