# Generated by Django 5.1.2 on 2025-05-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrary", "0004_exercise_markdown_lesson_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="number",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
