# Generated by Django 5.1.2 on 2025-05-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrary", "0005_lesson_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="study_markdown",
            field=models.TextField(blank=True),
        ),
    ]
