# Generated by Django 5.1.2 on 2025-05-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itrary", "0006_lesson_study_markdown"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["number"]},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["number"]},
        ),
        migrations.AlterUniqueTogether(
            name="exercise",
            unique_together={("lesson", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("unit", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("course", "name")},
        ),
    ]
