# Generated by Django 5.1.2 on 2025-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itrary", "0007_alter_lesson_options_alter_unit_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="intro_markdown",
            field=models.TextField(blank=True),
        ),
    ]
